"""World 4: Coral Cove (Levels 1 to 30, 210 unique words)."""
from __future__ import annotations

# Format: (text, meaning, sentence, hint, syllables, mistake, alt)
WORLD_4_LEVELS = [
    # L1: 4-5 letter ocean foundation
    [
        ("wave", "A long body of water curling into an arched crest and breaking on shore.", "A gentle turquoise wave broke softly against the white sandy shore.", "WAYV", "wave", "Saying 'wev' with short 'e'.", "A curling turquoise ocean wave breaking with white seafoam on sand"),
        ("tide", "The alternate rising and falling of the sea due to gravitational forces.", "At low tide, children explored colorful starfish in the shallow tide pools.", "TYD", "tide", "Saying 'teed' with long 'e'.", "Ocean water gently receding along a sandy beach leaving wet patterns"),
        ("reef", "A ridge of jagged rock, coral, or sand just above or below the sea.", "Schools of bright tropical fish swam through the vibrant coral reef.", "REEF", "reef", "Saying 'rif' with short 'i'.", "A colorful underwater coral reef teeming with swimming yellow fish"),
        ("clam", "A marine bivalve mollusk with a hinged two-part shell.", "The giant clam opened its colorful scalloped shell on the ocean floor.", "KLAM", "clam", "Saying 'klem' with short 'e'.", "A colorful giant clam on a coral seabed showing blue and purple mantle"),
        ("crab", "A crustacean with a broad carapace, stalked eyes, and pincers.", "A little hermit crab scuttled sideways across the warm wet sand.", "KRAB", "crab", "Saying 'kreb' with short 'e'.", "A bright red shore crab with pincers walking on golden beach sand"),
        ("gull", "A long-winged web-footed seabird with grey and white plumage.", "A seagull glided effortlessly on the ocean breeze over the beach.", "GUHL", "gull", "Saying 'gool' with long 'oo'.", "A white seagull with grey wingtips soaring against a sunny blue sky"),
        ("dune", "A mound or ridge of sand formed by the wind on the coast.", "Sea oats grew along the crest of the sandy coastal dune.", "DOON", "dune", "Saying 'dun' with short 'u'.", "Rolling coastal sand dunes with green sea oats overlooking the ocean"),
    ],
    # L2: 5-letter marine life & coastal objects
    [
        ("shark", "A long-bodied predatory marine fish with a cartilaginous skeleton.", "A gentle nurse shark rested peacefully on the sandy ocean floor.", "SHAHRK", "shark", "Saying 'shork' with wrong vowel.", "A sleek grey reef shark swimming gracefully through clear blue water"),
        ("whale", "A very large marine mammal with a streamlined hairless body.", "The blue whale breached majestically, spraying a fountain of water.", "WAYL", "whale", "Saying 'wal' with flat 'a'.", "A massive blue whale tail fluke lifting out of the ocean water"),
        ("coral", "A hard stony substance formed by marine polyps in reefs.", "Pink and golden branches of coral created an underwater forest.", "KOR-uhl", "cor-al", "Saying 'kuh-ral' with wrong stress.", "Branching pink and orange staghorn coral colonies in clear sea water"),
        ("diver", "A person who dives underwater, especially with scuba gear.", "The scuba diver photographed colorful sea anemones on the reef.", "DY-ver", "di-ver", "Saying 'dee-ver' with long 'e'.", "A scuba diver in a black wetsuit with a mask swimming near coral"),
        ("shell", "The hard protective outer case of a marine mollusk.", "She picked up a smooth pink spiral conch shell from the surf.", "SHEL", "shell", "Saying 'shall' with short 'a'.", "A shiny pink and cream spiral seashell resting on wet beach sand"),
        ("beach", "A pebbly or sandy shore, especially by the ocean between high and low water marks.", "Children built grand sandcastles along the sunny ocean beach.", "BEECH", "beach", "Saying 'bitch' with short 'i'.", "A tropical white sand beach lined with leaning green coconut palms"),
        ("ocean", "A very large expanse of sea, in particular each of the main areas.", "Sunlight sparkled across the vast expanse of the deep blue ocean.", "OH-shuhn", "o-cean", "Saying 'oh-see-uhn' with three syllables.", "A panoramic view of deep sapphire blue ocean extending to the horizon"),
    ],
    # L3: 5-letter nautical & coastal terms
    [
        ("float", "To rest or move on or near the surface of a liquid without sinking.", "The colorful foam buoy floated steadily on top of the gentle waves.", "FLOHT", "float", "Saying 'flot' with short 'o'.", "A bright yellow mooring buoy floating peacefully on blue ocean waves"),
        ("pearl", "A hard, glistening object produced within the soft tissue of a mollusk.", "Inside the oyster shell rested a lustrous, perfectly round white pearl.", "PURL", "pearl", "Saying 'peerl' with long 'e'.", "An open oyster shell revealing a glowing luminous round white pearl"),
        ("squid", "An elongated, fast-swimming cephalopod with ten arms.", "The playful reef squid changed its iridescent colors in the reef.", "SKWID", "squid", "Saying 'skweed' with long 'e'.", "A translucent Caribbean reef squid hovering gracefully in clear blue water"),
        ("shrimp", "A small free-swimming crustacean with an elongated body.", "A tiny banded cleaner shrimp danced upon the sea anemone.", "SHRIMP", "shrimp", "Saying 'srimp' and dropping 'sh'.", "A colorful red and white banded coral cleaner shrimp on a sea anemone"),
        ("spongy", "Like a sponge; porous, soft, and absorbent in nature.", "A soft spongy sea sponge filtered nutrients from the ocean current.", "SPUHN-jee", "spon-gy", "Saying 'spohn-gy' with hard 'g'.", "A bright yellow tube sponge growing on a coral reef in clear water"),
        ("spray", "Liquid sent through the air in tiny droplets.", "Salty sea spray splashed refreshing mist over the boat's bow.", "SPRAY", "spray", "Saying 'spree' with long 'e'.", "White sea spray crashing against a dark coastal rock in sunlight"),
        ("sloop", "A small sailing boat with a single mast and a fore-and-aft rig.", "The white sloop glided effortlessly across the sheltered harbor.", "SLOOP", "sloop", "Saying 'slup' with short 'u'.", "A single-masted white sailboat sloop sailing across sunny blue water"),
    ],
    # L4: 6-letter marine creatures & mammals
    [
        ("dolphin", "A small gregarious toothed whale with a beaklike snout.", "A pod of dolphins leaped playfully alongside the sailing ship.", "DAHL-fin", "dol-phin", "Saying 'dole-fin' with long 'o'.", "Two playful grey bottlenose dolphins jumping out of blue ocean water"),
        ("walrus", "A large flippered marine mammal with long tusks.", "The mighty walrus hauled itself onto the floating ice floe.", "WAWL-ruhs", "wal-rus", "Saying 'val-rus' with 'v' sound.", "A large brown walrus with long white ivory tusks resting on an ice floe"),
        ("turtle", "A marine reptile with a bony shell and flippers for swimming.", "A green sea turtle glided gracefully over the sea grass meadow.", "TUR-tuhl", "tur-tle", "Saying 'toor-tle' with long 'oo'.", "A gentle sea turtle swimming with flippers in crystal clear turquoise water"),
        ("salmon", "A large edible fish with pink flesh that migrates to spawn.", "Silvery salmon leaped upstream against the rushing river rapids.", "SAM-uhn", "sal-mon", "Pronouncing the silent 'l' as in 'sal-mon'.", "A silver and pink salmon jumping out of foaming river rapids"),
        ("seabed", "The bottom of the ocean or sea; the sea floor.", "Starfish and sand dollars carpeted the golden sandy seabed.", "SEE-bed", "sea-bed", "Saying 'see-bad' with short 'a'.", "Rippled golden sand on the ocean seabed with swimming tropical fish"),
        ("anchor", "A heavy metal device cast overboard to keep a ship in place.", "The sailor dropped the heavy iron anchor into the calm cove.", "ANG-ker", "an-chor", "Saying 'an-chore' with 'ch' sound.", "A classic iron ship anchor resting on the sandy ocean floor near coral"),
        ("harbor", "A sheltered body of water where ships may dock safely.", "Fishing boats docked securely along the stone piers of the harbor.", "HAHR-ber", "har-bor", "Saying 'hor-ber' with wrong vowel.", "A picturesque coastal fishing harbor with colorful boats and calm water"),
    ],
    # L5: 6-letter ocean vessels & navigation
    [
        ("vessel", "A ship or large boat for traveling on water.", "The research vessel carried scientists to study the coral reef.", "VES-uhl", "ves-sel", "Saying 'vass-uhl' with short 'a'.", "A modern blue and white oceanographic research ship vessel at sea"),
        ("island", "A piece of land surrounded entirely by water.", "Palm trees swayed gently along the shores of the tropical island.", "EYE-luhnd", "is-land", "Pronouncing the silent 's' as in 'is-land'.", "A lush green tropical island surrounded by turquoise coral lagoons"),
        ("coastal", "Of or near a coast; bordering the ocean.", "Scenic coastal cliffs offered breathtaking views of the ocean waves.", "KOH-stuhl", "coast-al", "Saying 'caw-stul' with short 'o'.", "A dramatic winding coastal road overlooking ocean cliffs and surf"),
        ("lagoon", "A stretch of salt water separated from the sea by a low sandbank or reef.", "Flamingos waded peacefully in the shallow turquoise water lagoon.", "luh-GOON", "la-goon", "Saying 'lay-goon' with long 'a'.", "A calm turquoise tropical saltwater lagoon enclosed by a coral atoll"),
        ("marina", "A specially designed harbor with moorings for pleasure yachts.", "Row upon row of sailboats docked neatly at the sunny marina.", "muh-REE-nuh", "ma-ri-na", "Saying 'mah-ry-nuh' with long 'i'.", "A modern recreational marina filled with gleaming white yachts"),
        ("rowboat", "A small boat propelled by oars.", "They rowed a wooden rowboat across the calm reflective bay.", "ROH-boht", "row-boat", "Saying 'raw-boat' with short 'o'.", "A classic wooden rowboat with oars resting on calm water at dawn"),
        ("kayaks", "Plural of kayak; small narrow watercraft propelled by a double-bladed paddle.", "Colorful kayaks glided smoothly through the mangrove channels.", "KY-aks", "kay-aks", "Saying 'kay-yaks' with long 'a'.", "Two bright red and yellow sea kayaks paddling near coastal rock arches"),
    ],
    # L6: 6-letter ocean depths & geology
    [
        ("abyss", "A deep or seemingly bottomless chasm in the ocean.", "Strange bioluminescent creatures thrived in the dark ocean abyss.", "uh-BIS", "a-byss", "Saying 'ay-biss' with long 'a'.", "An illustration of deep ocean abyss with glowing deep-sea creatures"),
        ("trench", "A long, narrow, deep depression in an ocean floor.", "The Mariana Trench is the deepest known geological canyon on Earth.", "TRENCH", "trench", "Saying 'trensh' with 'sh' sound.", "A 3D oceanographic diagram showing the steep walls of a deep ocean trench"),
        ("shoals", "Plural of shoal; shallow areas in a body of water.", "Sandbars created shallow shoals where boats navigated carefully.", "SHOHLZ", "shoals", "Saying 'shalls' with short 'o'.", "An aerial view of golden sandbar shoals in clear turquoise ocean water"),
        ("islets", "Plural of islet; very small islands.", "Tiny rocky islets dotted the entrance to the sheltered bay.", "EYE-lits", "is-lets", "Pronouncing the silent 's'.", "A cluster of tiny green rocky islets surrounded by white ocean waves"),
        ("current", "A body of water moving in a definite direction through surrounding water.", "The warm Gulf Stream current carried tropical fish northward.", "KUR-uhnt", "cur-rent", "Saying 'coo-rent' with long 'oo'.", "An oceanic current map showing warm red and cool blue swirling streams"),
        ("tides", "Plural of tide; rising and falling cycles of the sea.", "Tides are driven by the gravitational pull of the moon and sun.", "TYDZ", "tides", "Saying 'teedz' with long 'e'.", "Two side-by-side photos showing the same coastline at high tide and low tide"),
        ("pebbly", "Full of or covered with small rounded stones.", "The waves washed over the smooth, colorful pebbly shoreline.", "PEB-lee", "peb-bly", "Saying 'peeb-lee' with long 'e'.", "A shoreline of smooth colorful wet pebbles glistening in the surf"),
    ],
    # L7: 6-letter tide pool & coral creatures
    [
        ("limpet", "A marine mollusk with a shallow conical shell adhering tightly to rocks.", "The conical limpet clung firmly to the wave-swept granite rock.", "LIM-pit", "lim-pet", "Saying 'leem-pet' with long 'e'.", "A conical ribbed limpet shell attached tightly to a wet intertidal rock"),
        ("urchin", "A small sea creature with a spiny globular shell.", "A purple sea urchin tucked itself between two coral branches.", "UR-chin", "ur-chin", "Saying 'ur-kin' with hard 'c'.", "A vibrant purple sea urchin with sharp protective spines on a reef"),
        ("mussel", "A bivalve mollusk with a brown or purplish-black shell.", "Clusters of black mussels clung to the wooden pilings of the pier.", "MUHS-uhl", "mus-sel", "Saying 'moos-uhl' with long 'oo'.", "A dense cluster of blue-black marine mussels attached to wet rock"),
        ("oyster", "A bivalve mollusk with a rough irregular shell, producing pearls.", "The oyster filtered ocean water to nourish itself on the reef.", "OY-ster", "oys-ter", "Saying 'eye-ster' with long 'i'.", "A rough-shelled edible oyster lying on a bed of crushed shells"),
        ("anemone", "A sea creature with a tube body and stinging tentacles around the mouth.", "A clownfish nestled safely among the tentacles of the sea anemone.", "uh-NEM-uh-nee", "a-nem-o-ne", "Stumbling over the 'nem-o-ne' sequence.", "A bright pink and orange sea anemone with waving soft tentacles"),
        ("barnacle", "A marine crustacean that attaches itself permanently to hard surfaces.", "Hard white barnacles encrusted the hull of the wooden boat.", "BAHR-nuh-kuhl", "bar-na-cle", "Saying 'bar-nay-cle' with long 'a'.", "A cluster of white volcanic-shaped barnacles cemented onto a coastal rock"),
        ("kelp", "A large brown seaweed that grows into underwater forests.", "Towering giant kelp swayed rhythmically with the ocean swell.", "KELP", "kelp", "Saying 'kulp' with short 'u'.", "A majestic sunlit underwater giant green kelp forest with fish swimming"),
    ],
    # L8: 6-letter sea birds & predators
    [
        ("pelican", "A large waterbird with a long bill and expandable throat pouch.", "The brown pelican scooped up schooling fish in its large bill pouch.", "PEL-i-kuhn", "pel-i-can", "Saying 'pee-li-can' with long 'e'.", "A brown pelican perched on a wooden dock piling overlooking water"),
        ("albatross", "A very large oceanic bird with long narrow wings.", "The wandering albatross glided for hours over the southern ocean.", "AL-buh-traws", "al-ba-tross", "Saying 'al-bah-trahs' with wrong vowel.", "A magnificent wandering albatross with giant wings soaring over waves"),
        ("penguin", "A flightless seabird of southern waters with flipper-like wings.", "The emperor penguin slid on its belly across the smooth sea ice.", "PENG-gwin", "pen-guin", "Saying 'pen-gwin' and dropping 'g'.", "A sleek emperor penguin with yellow neck markings standing on ice"),
        ("seabird", "A bird that frequents the sea or inshore waters.", "Every seabird on the cliff took flight at the sound of the foghorn.", "SEE-burd", "sea-bird", "Saying 'say-bird' with long 'a'.", "A flock of white seabirds soaring gracefully over crashing ocean waves"),
        ("puffin", "A pelagic seabird with a brightly colored triangular bill.", "The Atlantic puffin carried several small sand eels in its beak.", "PUHF-in", "puf-fin", "Saying 'poof-in' with long 'oo'.", "An adorable Atlantic puffin with a colorful striped beak on a cliff"),
        ("tern", "A seabird related to the gulls, typically with a forked tail.", "The Arctic tern migrates from pole to pole across the globe every year.", "TURN", "tern", "Saying 'tarn' with wrong vowel.", "A sleek white Arctic tern with a black cap hovering over water to dive"),
        ("cormorant", "A dark aquatic bird with a long neck and hooked bill.", "The cormorant spread its wet wings wide in the sun to dry its feathers.", "KOR-muh-ruhnt", "cor-mo-rant", "Skipping the middle 'mo' syllable.", "A black cormorant bird perched on a rock with wings outstretched in sun"),
    ],
    # L9: 6-letter seafaring & nautical life
    [
        ("sailor", "A person who works as a member of the crew of a commercial or naval ship.", "The experienced sailor tied a secure bowline knot in the rope.", "SAY-ler", "sail-or", "Saying 'sigh-lor' with long 'i'.", "A smiling sailor in a striped shirt pulling a rigging line on a ship"),
        ("captain", "The person in command of a ship or aircraft.", "The captain steered the vessel safely through the narrow channel.", "KAP-tuhn", "cap-tain", "Saying 'cap-tayn' with long 'a'.", "A ship captain in uniform standing behind the wooden helm wheel"),
        ("mariner", "A sailor or seafarer who navigates across oceans.", "Ancient mariners used the North Star to navigate across the seas.", "MAIR-i-ner", "mar-i-ner", "Saying 'ma-ree-ner' with long 'e'.", "An antique illustration of a seafarer mariner looking through a spyglass"),
        ("voyage", "A long journey involving travel by sea or in space.", "The brave explorers embarked on a historic voyage across the ocean.", "VOY-ij", "voy-age", "Saying 'voy-ayj' with wrong ending.", "A majestic tall ship sailing across open blue ocean under white clouds"),
        ("drift", "To be carried along by currents of air or water.", "The message in a glass bottle was left to drift across the ocean.", "DRIFT", "drift", "Saying 'dreeft' with long 'e'.", "A sealed glass message bottle floating gently on sunlit ocean water"),
        ("anchor", "A heavy metal object lowered to sea bottom to hold a vessel.", "The crew hoisted the iron anchor as the ship prepared to depart.", "ANG-ker", "an-chor", "Saying 'an-chore' with 'ch' sound.", "A heavy iron ship anchor being raised out of foaming sea water"),
        ("helm", "A tiller or wheel for steering a ship or boat.", "The navigator held a steady course at the ship's wooden helm.", "HELM", "helm", "Saying 'hel-um' with two syllables.", "A polished brass and teak ship steering wheel helm on a bridge"),
    ],
    # L10: 6-letter tropical reef terms
    [
        ("atoll", "A ring-shaped reef, island, or chain of islands formed of coral.", "A tranquil turquoise lagoon sat in the center of the coral atoll.", "AT-awl", "at-oll", "Saying 'ay-toll' with long 'a'.", "An aerial view of a circular coral atoll island in deep blue ocean"),
        ("polyps", "Plural of polyp; tiny sea creatures that construct coral reefs.", "Millions of tiny coral polyps built the massive Great Barrier Reef.", "PAHL-ips", "pol-yps", "Saying 'poh-lips' with long 'o'.", "A microscopic close-up of colorful flowering coral polyps extending tentacles"),
        ("shallows", "Plural of shallow; areas of water of little depth.", "Schools of juvenile fish swam safely in the sun-warmed shallows.", "SHAL-ohz", "shal-lows", "Saying 'shel-lowz' with short 'e'.", "Crystal clear shallow turquoise water revealing white sand ripples beneath"),
        ("mangrove", "A tree or shrub that grows in coastal saline or brackish water.", "Interlocking roots of the mangrove forest protected the shoreline.", "MANG-grohv", "man-grove", "Saying 'men-grove' with short 'e'.", "Dense green mangrove trees with stilt roots growing in coastal water"),
        ("estuary", "The tidal mouth of a large river, where the tide meets the stream.", "The rich estuary provided a nursery for young fish and crabs.", "ES-choo-air-ee", "es-tu-ar-y", "Saying 'es-too-ree' with dropped syllable.", "An aerial view of a winding river estuary meeting the blue ocean"),
        ("seabreeze", "A cooling breeze blowing from the sea toward the land.", "A refreshing seabreeze kept the tropical beach cool at midday.", "SEE-breez", "sea-breeze", "Saying 'say-breeze' with long 'a'.", "Palm trees leaning gracefully as a cooling ocean seabreeze blows"),
        ("seawater", "Water in or taken from the sea; saltwater.", "A splash of cool seawater tasted salty on the diver's lips.", "SEE-wah-ter", "sea-wa-ter", "Saying 'sea-wader' with sloppy 'd'.", "A clear turquoise splash of ocean seawater sparkling in bright sunlight"),
    ],
    # L11: 7-letter marine invertebrates
    [
        ("starfish", "A marine echinoderm with five or more radiating arms.", "A bright orange starfish clung to the wet rock in the tide pool.", "STAHR-fish", "star-fish", "Saying 'store-fish' with wrong vowel.", "A vivid orange five-armed starfish resting on a wet coastal rock"),
        ("octopus", "A soft-bodied mollusk with eight tentacles bearing suckers.", "The clever octopus camouflaged itself to match the coral rock.", "AHK-tuh-puhs", "oc-to-pus", "Saying 'ahk-toh-poos' with wrong vowels.", "An octopus swimming gracefully with outstretched tentacles in blue water"),
        ("jellyfish", "A free-swimming marine coelenterate with a gelatinous bell.", "A translucent pink jellyfish pulsed gently through the clear water.", "JEL-ee-fish", "jel-ly-fish", "Saying 'yal-lee-fish' with 'y' sound.", "A glowing translucent pink jellyfish with trailing tentacles in blue sea"),
        ("lobster", "A large marine crustacean with a cylindrical body and large claws.", "A blue lobster peeked out from its rocky crevice on the seabed.", "LAHB-ster", "lob-ster", "Saying 'lobe-ster' with long 'o'.", "A dark blue marine lobster with large powerful claws on a sea floor"),
        ("scallop", "A bivalve mollusk with a fan-shaped fluted shell.", "The scallop clapped its shell valves together to swim through water.", "SKAH-luhp", "scal-lop", "Saying 'skay-lahp' with long 'a'.", "A beautiful ridged fan-shaped pink and white scallop seashell"),
        ("nautilus", "A cephalopod mollusk with a spiral chambered shell.", "The chambered nautilus used gas in its chambers to control buoyancy.", "NAW-tuhl-uhs", "nau-ti-lus", "Saying 'now-tee-lus' with wrong vowels.", "A striped brown and white chambered nautilus swimming in deep water"),
        ("barnacles", "Plural of barnacle; marine crustaceans that stick to ships.", "The whale's skin was dotted with harmless oceanic barnacles.", "BAHR-nuh-kuhlz", "bar-na-cles", "Saying 'bar-nay-kuhlz' with long 'a'.", "Clusters of white cone-shaped marine barnacles on a weathered wooden pier"),
    ],
    # L12: 7-letter coastal birds & amphibians
    [
        ("pelicans", "Plural of pelican; large waterbirds with throat pouches.", "A squadron of pelicans flew in formation over the ocean surf.", "PEL-i-kuhnz", "pel-i-cans", "Saying 'pee-li-canz' with long 'e'.", "Three brown pelicans flying in single file over breaking waves"),
        ("flamingos", "Plural of flamingo; tall pink wading birds with long legs.", "A flock of pink flamingos stood gracefully in the shallow lagoon.", "fluh-MING-gohz", "fla-min-gos", "Saying 'flay-ming-gohz' with long 'a'.", "A flock of vibrant pink flamingos standing on one leg in a lagoon"),
        ("seagulls", "Plural of seagull; web-footed seabirds with loud calls.", "Seagulls swooped down to catch fish tossed from the fishing boat.", "SEE-guhlZ", "sea-gulls", "Saying 'say-gullz' with long 'a'.", "A group of white seagulls flying around a fishing boat over water"),
        ("sandpiper", "A small wading bird that scurries along the surf line.", "The sandpiper probed the wet sand with its bill for tiny crabs.", "SAND-py-per", "sand-pi-per", "Saying 'send-pipe-er' with short 'e'.", "A small sandpiper bird running along the edge of incoming waves"),
        ("kingfisher", "A brightly colored bird that dives swiftly for fish.", "The pied kingfisher hovered motionlessly before diving into the sea.", "KING-fish-er", "king-fish-er", "Saying 'keen-fish-er' with long 'e'.", "A dazzling turquoise kingfisher emerging from water holding a small fish"),
        ("cormorant", "A dark aquatic diving bird with webbed feet and a hooked bill.", "The cormorant dove deep beneath the waves to chase a school of fish.", "KOR-muh-ruhnt", "cor-mo-rant", "Skipping the middle syllable 'mo'.", "A dark cormorant diving headfirst into clear blue ocean water"),
        ("albatross", "A very large seabird that can glide across oceans without flapping.", "The albatross traveled thousands of miles across the southern sea.", "AL-buh-traws", "al-ba-tross", "Saying 'al-bah-trahs' with wrong vowel.", "A giant white albatross soaring effortlessly over stormy ocean swells"),
    ],
    # L13: 7-letter sea vessels & navigation gear
    [
        ("sailboat", "A boat propelled largely or wholly by sails.", "The white sailboat leaned into the wind as it tacked across the bay.", "SAYL-boht", "sail-boat", "Saying 'sel-boat' with short 'e'.", "A sleek white sailboat with billowing white sails on blue water"),
        ("compass", "An instrument containing a magnetized pointer that shows the direction.", "The sailor checked the compass to steer a true course northward.", "KUHM-puhs", "com-pass", "Saying 'cahm-pass' with short 'o'.", "A brass navigational compass in a wooden box pointing north"),
        ("buoyancy", "The ability or tendency to float in water or air.", "The air-filled chambers provided positive buoyancy to the life jacket.", "BOY-uhn-see", "buoy-an-cy", "Saying 'boo-yan-cy' with 'oo' sound.", "A floating life jacket maintaining buoyancy on top of swimming pool water"),
        ("seafarer", "A person who travels regularly by sea; a sailor.", "The old seafarer shared thrilling tales of giant waves and whales.", "SEE-fair-er", "sea-far-er", "Saying 'say-fair-er' with long 'a'.", "An experienced seafarer in a raincoat looking through binoculars on a deck"),
        ("tidepool", "A pool of water left behind on a beach or reef after high tide.", "They discovered tiny crabs, snails, and sea stars in the rocky tide pool.", "TYD-pool", "tide-pool", "Saying 'teed-pool' with long 'e'.", "A colorful rocky tide pool filled with green sea anemones and red starfish"),
        ("seashore", "An area of sandy, stony, or rocky land bordering the sea.", "Children collected colorful sea glass along the breezy seashore.", "SEE-shor", "sea-shore", "Saying 'say-shore' with long 'a'.", "A picturesque sandy seashore with gentle rolling waves at golden hour"),
        ("currents", "Plural of current; flowing bodies of ocean water.", "Ocean currents circulate warm and cold water around the globe.", "KUR-uhnts", "cur-rents", "Saying 'coo-rents' with long 'oo'.", "An illustrated globe showing major swirling ocean currents in blue and red"),
    ],
    # L14: 7-letter marine biology & ecosystems
    [
        ("seaweed", "Large algae growing in the sea or on rocks below high water.", "Green and brown seaweed swayed gently with each passing swell.", "SEE-weed", "sea-weed", "Saying 'say-weed' with long 'a'.", "Green and golden kelp seaweed floating in clear turquoise ocean water"),
        ("plankton", "Microscopic organisms drifting in the sea, eaten by whales.", "Basking sharks feed by filtering millions of tiny plankton.", "PLANGK-tuhn", "plank-ton", "Saying 'plenk-ton' with short 'e'.", "A microscopic darkfield view of glowing geometric marine plankton organisms"),
        ("seagrass", "Grass-like plants that live completely submerged in shallow sea water.", "Manatees grazed peacefully in the lush underwater seagrass beds.", "SEE-gras", "sea-grass", "Saying 'say-grahs' with wrong vowels.", "A lush green underwater seagrass meadow with sunlight filtering down"),
        ("mollusks", "Plural of mollusk; soft-bodied invertebrates often with shells.", "Snails, clams, and octopuses belong to the diverse phylum of mollusks.", "MAHL-uhsks", "mol-lusks", "Saying 'moh-lusks' with long 'o'.", "A colorful collection of various seashells, squids, and snail mollusks"),
        ("creature", "A living animal, as distinct from a human being.", "The ocean depths contain many an extraordinary glowing creature.", "KREE-cher", "crea-ture", "Saying 'kree-toor' with unnatural ending.", "A fascinating deep-sea bioluminescent anglerfish creature glowing in dark"),
        ("organism", "An individual animal, plant, or single-celled life form.", "Every tiny organism in the coral reef contributes to its health.", "OR-guh-niz-uhm", "or-gan-ism", "Saying 'or-gan-eez-um' with long 'e'.", "A vibrant coral reef ecosystem showing diverse living organisms together"),
        ("tropical", "Characteristic of the warm region surrounding the equator.", "Schools of brightly colored tropical fish darted among the corals.", "TRAHP-i-kuhl", "trop-i-cal", "Saying 'troh-pi-cal' with long 'o'.", "A school of colorful yellow, blue, and striped tropical fish on a reef"),
    ],
    # L15: 7-letter coastal geography & landmarks
    [
        ("bayfront", "The land or road bordering a bay.", "Visitors walked along the scenic pedestrian promenade on the bayfront.", "BAY-fruhnt", "bay-front", "Saying 'bay-frant' with short 'a'.", "A scenic palm-lined paved pedestrian bayfront walk with benches overlooking boats"),
        ("headland", "A narrow piece of land that projects from a coastline into the sea.", "A historic white lighthouse stood tall upon the rocky headland.", "HED-luhnd", "head-land", "Saying 'heed-land' with long 'e'.", "A dramatic green grassy coastal headland cliff with a white lighthouse"),
        ("sandbars", "Plural of sandbar; ridges of sand formed by tides.", "The incoming tide gently covered the golden sandbars in the bay.", "SAND-bahrz", "sand-bars", "Saying 'send-barz' with short 'e'.", "Curving golden sandbars emerging from shallow clear turquoise ocean water"),
        ("channels", "Plural of channel; navigable routes between bodies of water.", "Deep water channels allowed large cargo ships to enter the bay.", "CHAN-uhlz", "chan-nels", "Saying 'shen-nels' with 'sh'.", "An aerial navigation chart showing blue marked shipping channels"),
        ("islander", "A native or inhabitant of an island.", "The friendly islander showed them how to harvest sweet coconut water.", "EYE-luhn-der", "is-land-er", "Pronouncing the silent 's'.", "A smiling islander wearing a flower lei standing beside palm trees"),
        ("tidegate", "A gate that opens and closes with the rise and fall of the tide.", "The wooden tidegate controlled water flow into the salt marsh.", "TYD-gayt", "tide-gate", "Saying 'teed-gate' with long 'e'.", "A wooden and metal water control tidegate in a coastal stone sea wall"),
        ("coastal", "Located on or near the coast of an ocean or sea.", "Cool sea breezes refreshed the picturesque coastal village.", "KOH-stuhl", "coast-al", "Saying 'caw-stul' with short 'o'.", "A scenic panoramic view of a coastal village with fishing docks and sea"),
    ],
    # L16: 8+ letter marine mammals & large fish
    [
        ("porpoise", "A small toothed whale with a rounded snout and triangular fin.", "The harbor porpoise surfaced quietly with a soft puff of breath.", "POR-puhs", "por-poise", "Saying 'por-poyz' with 'oy' sound.", "A sleek grey harbor porpoise swimming close to the water surface"),
        ("stingray", "A large flat ray with a stinging barbed spine on its whiplike tail.", "A spotted eagle stingray glided like a bird through the clear blue water.", "STING-ray", "sting-ray", "Saying 'steen-ray' with long 'e'.", "A magnificent spotted eagle stingray gliding gracefully over white sand"),
        ("swordfish", "A large marine fish with a long, swordlike upper jaw.", "The speedy swordfish can swim at speeds of over sixty miles per hour.", "SORD-fish", "sword-fish", "Pronouncing the silent 'w' as in 's-word'.", "A powerful blue swordfish leaping out of deep blue ocean water"),
        ("barracuda", "A large, predatory tropical marine fish with sharp teeth.", "The silver barracuda patrolled the outer edge of the coral drop-off.", "bair-uh-KOO-duh", "bar-ra-cu-da", "Saying 'bar-ra-coo-dah' with wrong stress.", "A long silver barracuda fish with sharp teeth hovering near a reef"),
        ("manta-ray", "A very large ray with triangular pectoral fins and horn-shaped head fins.", "A giant manta ray performed slow graceful barrel rolls while feeding.", "MAN-tuh-ray", "man-ta-ray", "Saying 'men-tuh-ray' with short 'e'.", "A colossal black and white manta ray gliding with open cephalic fins"),
        ("hammerhead", "A shark with a wide, flattened hammer-shaped head.", "The scalloped hammerhead shark swam along the underwater seamount.", "HAM-er-hed", "ham-mer-head", "Saying 'hem-er-head' with short 'e'.", "A distinctive hammerhead shark swimming in deep clear blue ocean"),
        ("angelfish", "A brightly colored tropical fish with a thin, deep body.", "A Queen angelfish with brilliant blue and yellow markings grazed on sponge.", "AYN-juhl-fish", "an-gel-fish", "Saying 'an-gell-fish' with hard 'g'.", "A stunning blue and yellow Queen angelfish swimming beside coral polyps"),
    ],
    # L17: 8+ letter ocean exploration & submersibles
    [
        ("submarine", "A watercraft capable of independent operation underwater.", "The yellow research submarine descended into the deep ocean canyon.", "suhb-muh-REEN", "sub-ma-rine", "Saying 'sub-ma-ryn' with long 'i'.", "A yellow manned research submarine exploring deep-sea coral formations"),
        ("periscope", "An apparatus for viewing objects that are above the water level.", "The submarine captain peered through the periscope to check the horizon.", "PAIR-i-skohp", "per-i-scope", "Saying 'per-ee-scope' with long 'e'.", "A periscope optical tube extending above ocean waves to view a ship"),
        ("submersible", "A small boat or craft designed to operate under water.", "The robotic submersible gathered mineral samples from the sea floor.", "suhb-MUR-suh-buhl", "sub-mers-i-ble", "Saying 'sub-mer-see-ble' with long 'e'.", "A robotic unmanned deep-sea submersible ROV with manipulator arms and lights"),
        ("bathyscaphe", "A free-diving self-propelled deep-sea submersible.", "The historic bathyscaphe Trieste reached the bottom of the Challenger Deep.", "BATH-i-skaf", "bath-y-scaphe", "Stumbling over the Greek origin consonants.", "The historic deep-sea submersible bathyscaphe with large float chamber"),
        ("sonarscope", "An instrument using sonar to detect underwater objects.", "The sonarscope showed schools of fish swimming around the sunken reef.", "SOH-nahr-skohp", "so-nar-scope", "Saying 'sah-nar-scope' with short 'o'.", "A glowing green circular sonar screen displaying submarine sound echoes"),
        ("scubadiver", "A diver who uses self-contained underwater breathing apparatus.", "The scubadiver swam alongside sea turtles in the coral lagoon.", "SKOO-buh-dy-ver", "scu-ba-div-er", "Saying 'skuh-bah-diver' with short 'u'.", "A scuba diver in full gear exploring an underwater coral wall"),
        ("hydroplane", "A light, fast motorboat designed to skim over the water.", "The hydroplane raced across the calm surface of the bay with speed.", "HY-druh-playn", "hy-dro-plane", "Saying 'hee-dro-plane' with long 'e'.", "A fast racing hydroplane boat skimming across water creating rooster tails"),
    ],
    # L18: 8+ letter coral reef ecology & conservation
    [
        ("biodiverse", "Showing a great variety of plant and animal species.", "The coral reef was the most biodiverse marine ecosystem on Earth.", "by-oh-dy-VURS", "bi-o-di-verse", "Saying 'bee-o-di-verse' with long 'e'.", "A bustling coral reef bursting with hundreds of colorful fish and corals"),
        ("regeneration", "The renewal or regrowth of living tissues or coral colonies.", "Coral fragments showed rapid regeneration on the restoration frames.", "ri-jen-er-AY-shuhn", "re-gen-er-a-tion", "Saying 're-gen-ra-tion' with dropped syllable.", "New bright coral polyps growing over an underwater nursery metal frame"),
        ("preservation", "The act of keeping natural ocean environments healthy.", "Marine protected areas ensured the long-term preservation of the reef.", "prez-er-VAY-shuhn", "pres-er-va-tion", "Saying 'press-er-va-tion' with hard 's'.", "A patrol boat marking boundaries of a protected marine nature reserve"),
        ("conservation", "The protection and management of marine biodiversity.", "School children joined coastal conservation projects to clean the beaches.", "kahn-ser-VAY-shuhn", "con-ser-va-tion", "Saying 'con-ser-va-shun' with hard 's'.", "Volunteers collecting marine debris from a sandy beach with bags"),
        ("sustainability", "Maintaining ocean ecological balance without depleting fish.", "Sustainable fishing practices protected tuna stocks for the future.", "suh-stay-nuh-BIL-i-tee", "sus-tain-a-bil-i-ty", "Stumbling over the seven-syllable sequence.", "A certified sustainable seafood emblem on a wooden fishing boat"),
        ("symbiosis", "A mutually beneficial relationship between two organisms.", "Clownfish and sea anemones live in an extraordinary marine symbiosis.", "sim-bee-OH-sis", "sym-bi-o-sis", "Saying 'sym-by-o-sis' with wrong stress.", "An orange clownfish resting safely among the tentacles of a sea anemone"),
        ("ecosystems", "Plural of ecosystem; biological communities in their environment.", "Mangrove swamps and coral reefs are vital coastal ecosystems.", "EE-koh-sis-tuhmz", "e-co-sys-tems", "Saying 'ek-oh-sys-tems' with short 'e'.", "A split-level photo showing mangroves above water and coral reefs below"),
    ],
    # L19: 8+ letter oceanographic equipment & tools
    [
        ("oceanography", "The branch of science that deals with the physical and biological properties of the sea.", "Her degree in oceanography led her to study deep-sea hydrothermal vents.", "oh-shuh-NAHG-ruh-fee", "o-cean-og-ra-phy", "Saying 'o-cean-oh-gra-phy' with wrong stress.", "An oceanographer analyzing satellite sea temperature maps on monitors"),
        ("thermocline", "A steep temperature gradient in a body of water.", "Divers felt a sudden chill as they swam through the ocean thermocline.", "THUR-muh-klyn", "ther-mo-cline", "Saying 'ther-moh-cleen' with long 'e'.", "A scientific chart showing rapid water temperature drop with ocean depth"),
        ("hydrophone", "A microphone designed to be used underwater for recording sound.", "The hydrophone recorded the complex songs of humpback whales miles away.", "HY-druh-fohn", "hy-dro-phone", "Saying 'hee-dro-phone' with long 'e'.", "An underwater hydrophone acoustic sensor listening to ocean sounds"),
        ("salinometer", "An instrument for measuring the salinity of water.", "The marine scientist used a digital salinometer to test the brine pool.", "sal-uh-NAHM-i-ter", "sal-i-nom-e-ter", "Stumbling over the multisyllabic flow.", "A handheld digital salinometer testing a water sample in a beaker"),
        ("anemometer", "An instrument used to measure the speed of sea wind.", "The ship's anemometer recorded gale force winds during the storm.", "an-uh-MAHM-i-ter", "an-e-mome-ter", "Saying 'AN-e-mo-mee-ter' with wrong stress.", "A marine mast anemometer spinning in high wind against storm clouds"),
        ("barometer", "An instrument measuring air pressure to forecast sea weather.", "A sharp drop in the ship's barometer warned the captain of a squall.", "buh-RAHM-i-ter", "ba-rom-e-ter", "Saying 'bair-oh-mee-ter' with wrong stress.", "A brass ship's barometer mounted on the teak wood wall of a wheelhouse"),
        ("sextant", "An instrument with an arc of 60° used for measuring angular distances in navigation.", "The navigator measured the angle of the sun using a polished brass sextant.", "SEKS-tuhnt", "sex-tant", "Saying 'sex-tunt' with overstressed ending.", "A vintage brass marine sextant aligned with the ocean horizon and sun"),
    ],
    # L20: 8+ letter bioluminescence & abyss
    [
        ("bioluminescent", "Emitting light produced by a chemical reaction in a living organism.", "The night surf glowed neon blue with bioluminescent algae.", "by-oh-loo-mi-NES-uhnt", "bi-o-lu-mi-nes-cent", "Stumbling over the six-syllable sequence.", "Neon blue bioluminescent waves crashing onto a dark beach at night"),
        ("luminescence", "The emission of light by a substance not resulting from heat.", "Deep sea jellyfish flashed with eerie green luminescence in the dark.", "loo-mi-NES-uhns", "lu-mi-nes-cence", "Saying 'lu-meen-es-cence' with long 'e'.", "A glowing deep sea jellyfish radiating pulsing turquoise light in dark"),
        ("phosphorescence", "Light emitted by a substance without combustion or perceptible heat.", "The ship left a glittering trail of green phosphorescence in its wake.", "fahs-fuh-RES-uhns", "phos-pho-res-cence", "Stumbling over the consonant transitions.", "A boat motor wake glowing brightly with green phosphorescent light at sea"),
        ("abyssal", "Inhabiting or relating to the ocean depths, especially below 2,000 meters.", "The abyssal plain stretched flat and dark for thousands of miles.", "uh-BIS-uhl", "a-bys-sal", "Saying 'ay-bee-sal' with long 'a'.", "A deep-sea camera view of strange pale creatures on the dark abyssal plain"),
        ("hydrothermal", "Relating to the action of heated water in the earth's crust.", "Giant tube worms clustered around the mineral-rich hydrothermal vent.", "hy-druh-THUR-muhl", "hy-dro-ther-mal", "Saying 'hee-dro-ther-mal' with long 'e'.", "A deep-sea black smoker hydrothermal vent billowing mineral-rich clouds"),
        ("fluorescence", "The emission of light by a substance that has absorbed light.", "Under ultraviolet light, the coral colonies displayed dazzling fluorescence.", "flaw-RES-uhns", "flu-o-res-cence", "Saying 'floo-or-es-cence' with wrong stress.", "Corals glowing vibrant neon green, red, and orange under UV dive lights"),
        ("anglerfish", "A predatory marine fish with an illuminated lure on its head.", "The female anglerfish dangled a glowing light organ to attract prey.", "ANG-gler-fish", "an-gler-fish", "Saying 'an-jler-fish' with soft 'g'.", "A deep-sea black anglerfish with sharp teeth and a glowing blue bioluminescent lure"),
    ],
    # L21: 8+ letter seafaring history & lore
    [
        ("lighthouse", "A tower containing a beacon light to warn or guide ships at sea.", "The historic stone lighthouse flashed its bright beam across the waves.", "LYT-howss", "light-house", "Saying 'light-howz' with voiced 'z'.", "A majestic red and white striped stone lighthouse on a cliff at dusk"),
        ("shipwreck", "The destruction of a ship at sea by sinking or breaking up.", "Divers explored the coral-encrusted hull of the ancient shipwreck.", "SHIP-rek", "ship-wreck", "Pronouncing the silent 'w'.", "An ancient wooden sailing shipwreck covered in sea fans and swimming fish"),
        ("figurehead", "A carved wooden figure on the prow of a sailing ship.", "A carved wooden mermaid served as the ship's majestic figurehead.", "FIG-yer-hed", "fig-ure-head", "Saying 'fig-ger-head' with dropped syllable.", "An ornate carved wooden mermaid figurehead on the bow of a wooden ship"),
        ("catamaran", "A yacht or other boat with twin parallel hulls in a frame.", "The twin-hulled catamaran sailed smoothly across the ocean waves.", "kat-uh-muh-RAN", "cat-a-ma-ran", "Saying 'cat-uh-muh-ron' with wrong vowel.", "A sleek modern sailing catamaran with twin hulls cruising on blue sea"),
        ("buccaneer", "A pirate or privateer who operated in the Caribbean.", "Tales of the legendary buccaneer inspired exciting adventure stories.", "buhk-uh-NEER", "buc-ca-neer", "Saying 'book-uh-neer' with long 'oo'.", "An antique illustration of a seafaring captain studying a treasure map"),
        ("treasure", "A quantity of precious metals, gems, or other valuable objects.", "They unlocked the iron-bound wooden chest to discover sparkling treasure.", "TREZH-er", "trea-sure", "Saying 'tray-zhure' with long 'a'.", "An open wooden chest overflowing with gold doubloons, pearls, and jewels"),
        ("navigator", "A person who directs the route or course of a ship or aircraft.", "The skilled navigator plotted a safe course around the dangerous reefs.", "NAV-i-gay-ter", "nav-i-ga-tor", "Saying 'nay-vi-ga-tor' with long 'a'.", "A ship navigator using parallel rulers and dividers on a nautical chart"),
    ],
    # L22: 8+ letter marine habitats & environments
    [
        ("archipelago", "A group or chain of islands scattered in a body of water.", "The Galápagos archipelago is famous for its unique wildlife species.", "ahr-kuh-PEL-uh-goh", "ar-chi-pel-a-go", "Saying 'ar-chee-pel-a-go' with 'ch' sound.", "An aerial satellite view of a beautiful chain of tropical green islands"),
        ("intertidal", "Of or relating to the area of a seashore between high and low water marks.", "The intertidal zone was packed with colorful sea stars, crabs, and snails.", "in-ter-TY-duhl", "in-ter-ti-dal", "Saying 'in-ter-tee-dal' with long 'e'.", "Rocky intertidal tide pools exposed at low tide under a sunny blue sky"),
        ("pelagic", "Relating to the open sea rather than coastal waters or the sea floor.", "Pelagic tuna and marlin roam thousands of miles across open oceans.", "puh-LAJ-ik", "pe-lag-ic", "Saying 'pel-uh-jik' with wrong stress.", "A school of fast-swimming pelagic tuna in open deep blue sunlit water"),
        ("estuarine", "Relating to or found in the tidal mouth of a large river.", "Estuarine waters support dense populations of oysters and blue crabs.", "ES-choo-uh-ryn", "es-tu-a-rine", "Saying 'es-too-reen' with wrong ending.", "A peaceful brackish water estuarine river mouth with reeds and wading herons"),
        ("saltmarsh", "An area of coastal grassland that is regularly flooded by seawater.", "Great blue herons stalked through the tall grasses of the salt marsh.", "SAWLT-mahrsh", "salt-marsh", "Saying 'salt-marsh' with dropped 'l'.", "A golden coastal salt marsh winding with tidal creeks under sunny skies"),
        ("breakwater", "A barrier built out into a body of water to protect a coast or harbor.", "Massive stone blocks of the breakwater calmed the raging ocean surf.", "BRAYK-wah-ter", "break-wa-ter", "Saying 'bree-wader' with long 'e'.", "A massive granite stone breakwater barrier protecting calm boats in harbor"),
        ("coastlines", "Plural of coastline; the outline of a coast, especially with shapes.", "Rugged rocky coastlines spanned for hundreds of miles along the sea.", "KOHST-lynz", "coast-lines", "Saying 'cawst-lines' with short 'o'.", "A panoramic aerial photo of dramatic rocky coastal headlands and beaches"),
    ],
    # L23: 8+ letter oceanographic phenomena & tides
    [
        ("whirlpool", "A rapidly rotating mass of water in a river or sea.", "Strong tidal currents created a swirling natural whirlpool in the strait.", "WURL-pool", "whirl-pool", "Saying 'wer-pool' with dropped 'l'.", "A dramatic swirling circular water vortex whirlpool in the ocean"),
        ("maelstrom", "A powerful whirlpool in the sea or a river.", "Legend spoke of a giant ocean maelstrom that swallowed ancient ships.", "MAYL-struhm", "mael-strom", "Saying 'mah-el-strom' with extra syllable.", "A dramatic historical painting of a giant swirling ocean maelstrom storm"),
        ("undertow", "A current of water below the surface and moving in a different direction.", "Swimmers were careful to avoid the strong outward ocean undertow.", "UHN-der-toh", "un-der-tow", "Saying 'un-der-too' with long 'oo'.", "An illustrated diagram showing incoming surface waves and outgoing undertow"),
        ("springtide", "A tide just after a new or full moon, when there is the greatest difference.", "The moon's alignment created a high spring tide that flooded the flats.", "SPRING-tyd", "spring-tide", "Saying 'shpring-tide' with 'sh'.", "An illustrated chart of the earth, moon, and sun alignment during spring tide"),
        ("neaptide", "A tide just after the first or third quarters of the moon, with least difference.", "During the neap tide, the difference between high and low water was small.", "NEEP-tyd", "neap-tide", "Saying 'nep-tide' with short 'e'.", "An illustrated diagram showing the moon at right angles during neap tide"),
        ("tsunami", "A long high sea wave caused by an earthquake or submarine landslide.", "The deep ocean tsunami warning buoy detected pressure changes instantly.", "soo-NAH-mee", "tsu-na-mi", "Pronouncing hard initial 't'.", "A deep-sea oceanographic yellow sensor buoy measuring tsunami waves"),
        ("bathymetry", "The measurement of depth of water in oceans, seas, or lakes.", "Sonar bathymetry revealed underwater mountains higher than the Alps.", "buh-THIM-i-tree", "ba-thym-e-try", "Saying 'bath-ee-mee-try' with wrong stress.", "A high-resolution colorful 3D bathymetry elevation map of the ocean floor"),
    ],
    # L24: 8+ letter sea creature specializations
    [
        ("camouflage", "Coloration or patterns that help an animal blend with surroundings.", "The cuttlefish used dynamic skin camouflage to vanish on the sand.", "KAM-uh-flahzh", "cam-ou-flage", "Saying 'cam-oo-flayj' with wrong ending.", "A cuttlefish changing color and texture to match a speckled pebble seabed"),
        ("tentacles", "Plural of tentacle; slender flexible appendages used for grasping.", "The giant squid reached out with two long feeding tentacles.", "TEN-tuh-kuhlz", "ten-ta-cles", "Saying 'ten-tay-kuhlz' with long 'a'.", "Close-up of flexible octopus tentacles with circular suction cups"),
        ("exoskeleton", "A rigid external covering for the body in invertebrate animals.", "A crab sheds its hard chitinous exoskeleton as it grows larger.", "ek-soh-SKEL-i-tuhn", "ex-o-skel-e-ton", "Skipping the 'e' in skeleton.", "A discarded empty crab shell molt exoskeleton resting on beach sand"),
        ("crustaceans", "Plural of crustacean; arthropods including crabs, lobsters, and shrimp.", "Crustaceans have jointed legs and tough calcified exoskeletons.", "kruh-STAY-shuhnz", "crus-ta-ceans", "Saying 'crus-tah-ke-anz' with hard 'c'.", "An educational chart showing diverse marine crustaceans on display"),
        ("cephalopod", "An active predatory mollusk such as an octopus or squid.", "The intelligent cephalopod solved a maze to retrieve a tasty crab.", "SEF-uh-luh-pahd", "ceph-a-lo-pod", "Saying 'keph-a-lo-pod' with hard 'c'.", "A blue-ringed octopus cephalopod displaying iridescent glowing blue rings"),
        ("echinoderm", "A marine invertebrate of a group that includes starfish and sea urchins.", "Echinoderms have radial symmetry and a water vascular system.", "i-KY-nuh-durm", "e-chi-no-derm", "Saying 'ee-chee-no-derm' with 'ch' sound.", "A colorful display of sand dollars, brittle stars, and sea urchin echinoderms"),
        ("ichthyology", "The branch of zoology that deals with fishes.", "His passion for ichthyology led him to study coral reef fish diets.", "ik-thee-AHL-uh-jee", "ich-thy-ol-o-gy", "Stumbling over the Greek root syllables.", "An ichthyologist examining preserved fish specimens in a museum lab"),
    ],
    # L25: 8+ letter coastal plant & reef botany
    [
        ("photosynthesize", "To synthesize foods from carbon dioxide and water using sunlight.", "Zooxanthellae algae photosynthesize inside coral tissues to provide energy.", "foh-toh-SIN-thuh-syz", "pho-to-syn-the-size", "Stumbling over the multisyllabic rhythm.", "Microscopic view of golden algae cells inside translucent coral polyps"),
        ("zooxanthellae", "Single-celled golden-brown algae living inside coral polyps.", "Healthy zooxanthellae give coral reefs their magnificent vibrant colors.", "zoh-uh-zan-THEL-ee", "zo-o-xan-thel-lae", "Stumbling over the scientific pronunciation.", "Magnified view of vibrant symbiotic algae living inside coral tissues"),
        ("calcification", "The process of depositing calcium salts to build coral skeleton.", "Warm ocean water facilitates the rapid calcification of stony corals.", "kal-suh-fi-KAY-shuhn", "cal-ci-fi-ca-tion", "Skipping the 'fi' syllable.", "A cross-section of a white limestone skeleton of a brain coral"),
        ("biodiversity", "The variety of marine plant and animal life in a habitat.", "The Great Barrier Reef boasts the highest marine biodiversity on Earth.", "by-oh-dy-VUR-si-tee", "bi-o-di-ver-si-ty", "Saying 'bee-o-di-ver-si-ty' with long 'e'.", "A vibrant panorama of corals, sea turtles, sharks, and colorful fish"),
        ("microscopic", "So small as to be visible only with a microscope.", "Whales filter tons of microscopic krill and plankton from the sea.", "my-kruh-SKAHP-ik", "mi-cro-scop-ic", "Saying 'my-cro-scope-ik' with long 'o'.", "A glowing microscopic image of intricate geometric diatom shell organisms"),
        ("fluorescence", "The emission of vivid light by coral under ultraviolet dive lights.", "Night divers marveled at the psychedelic fluorescence of the coral polyps.", "flaw-RES-uhns", "flu-o-res-cence", "Saying 'floo-or-es-cence' with wrong stress.", "Corals glowing in vibrant electric green, pink, and orange under UV light"),
        ("invertebrate", "An animal lacking a backbone, such as an octopus or crab.", "Over ninety percent of all marine animals are classified as invertebrates.", "in-VUR-tuh-brayt", "in-ver-te-brate", "Saying 'in-ver-te-brayt' with wrong stress.", "A collage of colorful marine invertebrates including jellyfish and sea stars"),
    ],
    # L26: 8+ letter seafaring traditions & nautical arts
    [
        ("shipwright", "A carpenter skilled in building and repairing wooden ships.", "The master shipwright shaped curved oak ribs for the wooden schooner.", "SHIP-ryt", "ship-wright", "Pronouncing the silent 'gh' as hard 'g'.", "A skilled shipwright bending a steamed oak plank onto a wooden ship frame"),
        ("scrimshaw", "Scrollwork, engravings, and carvings done in bone or ivory.", "Sailors carved intricate whaling scenes into scrimshaw whale teeth.", "SKRIM-shaw", "scrim-shaw", "Saying 'scrim-sho' with long 'o'.", "An antique polished whale tooth engraved with a detailed scrimshaw sailing ship"),
        ("figureheads", "Plural of figurehead; carved wooden ornamental figures on ships.", "Historic maritime museums preserved gilded figureheads from wooden frigates.", "FIG-yer-hedz", "fig-ure-heads", "Saying 'fig-ger-headz' with dropped syllable.", "A row of colorful carved wooden maritime figureheads on museum display"),
        ("cartography", "The science or practice of drawing nautical navigational charts.", "Accurate cartography was essential for ships crossing uncharted oceans.", "kahr-TAHG-ruh-fee", "car-tog-ra-phy", "Saying 'car-to-gra-phy' with wrong stress.", "An antique hand-drawn navigational ocean chart with sea monster drawings"),
        ("astronomy", "The branch of science that deals with celestial objects and space.", "Ancient navigators studied astronomy to sail by the positions of stars.", "uh-STRAHN-uh-mee", "as-tron-o-my", "Saying 'as-tro-no-my' with wrong stress.", "A navigator observing stars through a telescope on a ship deck at night"),
        ("triangulation", "The tracing and measurement of a series of triangles in mapping.", "Coastal surveyors used triangulation to pinpoint navigation hazard rocks.", "try-ang-gyuh-LAY-shuhn", "tri-an-gu-la-tion", "Stumbling over the five-syllable sequence.", "A map diagram showing triangular lines connecting three coastal lighthouses"),
        ("horology", "The study and measurement of time, critical for marine longitude.", "Marine horology revolutionized ocean travel with precision chronometers.", "haw-RAHL-uh-jee", "ho-rol-o-gy", "Saying 'hor-oh-lo-gy' with wrong stress.", "A brass antique marine chronometer clock in a velvet-lined mahogany box"),
    ],
    # L27: 8+ letter ocean exploration milestones
    [
        ("submersibles", "Plural of submersible; underwater research exploratory craft.", "Deep-diving submersibles explored volcanic ridges miles below the surface.", "suhb-MUR-suh-buhlz", "sub-mers-i-bles", "Saying 'sub-mer-see-bulz' with long 'e'.", "Two yellow research submersibles with robotic arms working on the sea floor"),
        ("expeditionary", "Belonging to an expedition, especially for oceanic discovery.", "The expeditionary crew discovered twenty new species of deep-sea corals.", "ek-spuh-DISH-uh-nair-ee", "ex-pe-di-tion-ar-y", "Skipping the 'ar' syllable.", "A large ocean research expedition team gathered on the deck of a ship"),
        ("circumnavigate", "To sail or travel all the way around something, especially the world.", "Ferdinand Magellan's expedition was the first to circumnavigate the globe.", "sur-kuhm-NAV-i-gayt", "cir-cum-nav-i-gate", "Skipping the 'cum' syllable.", "A globe showing a red dotted navigation route circumnavigating the Earth"),
        ("oceanographer", "A scientist who studies the physical and biological aspects of the seas.", "The oceanographer tagged sea turtles to track their migratory routes.", "oh-shuh-NAHG-ruh-fer", "o-cean-og-ra-pher", "Saying 'o-cean-oh-gra-pher' with wrong stress.", "A marine oceanographer in a lab coat examining seawater core samples"),
        ("bathyspheres", "Plural of bathysphere; spherical deep-diving chambers.", "Pioneering scientists lowered steel bathyspheres into the dark abyss.", "BATH-i-sfeerz", "bath-y-spheres", "Saying 'bath-ee-sfeerz' with wrong vowel.", "The historic spherical steel diving bathysphere with thick round quartz windows"),
        ("hydrophones", "Plural of hydrophone; underwater acoustic recording devices.", "Underwater hydrophones detected the haunting echolocation clicks of whales.", "HY-druh-fohnz", "hy-dro-phones", "Saying 'hee-dro-phones' with long 'e'.", "An array of underwater hydrophone listening sensors submerged in blue sea"),
        ("salinometers", "Plural of salinometer; instruments measuring water salinity.", "Digital salinometers verified the high salt concentration in the tidal flats.", "sal-uh-NAHM-i-terz", "sal-i-nom-e-ters", "Stumbling over the multisyllabic flow.", "A marine scientist calibrating precision salinometers in a ship laboratory"),
    ],
    # L28: 8+ letter marine conservation & sanctuaries
    [
        ("sustainability", "Maintaining ocean ecological balance without depleting marine life.", "Marine sustainability requires protecting coral reefs and preventing overfishing.", "suh-stay-nuh-BIL-i-tee", "sus-tain-a-bil-i-ty", "Stumbling over the seven-syllable sequence.", "A symbolic illustration of clean blue ocean waves cradled by caring hands"),
        ("rehabilitation", "The restoration of injured wildlife to a condition of good health.", "The sea turtle rescue center celebrated the successful rehabilitation of a loggerhead.", "ree-huh-bil-i-TAY-shuhn", "re-ha-bil-i-ta-tion", "Skipping the 'bil' syllable.", "Marine biologists releasing a healthy rehabilitated sea turtle into ocean waves"),
        ("sanctuaries", "Plural of sanctuary; places where marine wildlife is protected.", "National marine sanctuaries provide safe breeding grounds for humpback whales.", "SANGK-choo-air-eez", "sanc-tu-ar-ies", "Saying 'sank-too-air-eez' with hard 't'.", "A marine sanctuary boundary marker buoy floating in turquoise coral water"),
        ("restoration", "The action of returning a degraded reef or ecosystem to a former condition.", "Coral restoration teams planted thousands of healthy fragments on degraded reefs.", "res-tuh-RAY-shuhn", "res-to-ra-tion", "Saying 'res-tore-ay-shun' with wrong vowel.", "Scuba divers attaching coral fragments to an underwater reef restoration frame"),
        ("biodiversity", "The rich variety of marine species in an oceanic ecosystem.", "The vibrant coral lagoon exhibited an astonishing level of biodiversity.", "by-oh-dy-VUR-si-tee", "bi-o-di-ver-si-ty", "Saying 'bee-o-di-ver-si-ty' with wrong vowels.", "A vibrant collage of sea turtles, dolphins, clownfish, and colorful corals"),
        ("environmental", "Relating to the natural marine world and human impact upon it.", "Environmental scientists monitored water clarity and temperature daily.", "en-vy-ruhn-MEN-tuhl", "en-vi-ron-men-tal", "Saying 'en-vi-ro-men-tal' and dropping 'n'.", "Scientists taking water samples in bottles from the side of a research boat"),
        ("preservation", "The maintenance of marine habitats in their pristine natural state.", "Global treaties supported the preservation of fragile deep-sea coral reefs.", "prez-er-VAY-shuhn", "pres-er-va-tion", "Saying 'press-er-va-tion' with hard 's'.", "A pristine untouched coral atoll with crystal water symbolizing preservation"),
    ],
    # L29: 8+ letter oceanic acoustic resonance
    [
        ("echolocation", "The location of objects by reflected sound, used by dolphins and whales.", "Dolphins use echolocation to navigate and hunt fish in murky water.", "ek-oh-loh-KAY-shuhn", "ech-o-lo-ca-tion", "Saying 'ee-choh-lo-ca-tion' with 'ch' sound.", "An illustration showing soundwaves emitting from a dolphin and bouncing off a fish"),
        ("reverberation", "Prolongation of sound; resonance created by reflection in water.", "Underwater reverberation carried whale calls across hundreds of miles.", "ri-vur-buh-RAY-shuhn", "re-ver-ber-a-tion", "Skipping the 'ber' syllable.", "An underwater acoustic graphic showing soundwaves rippling through sea layers"),
        ("bioluminescence", "Light emitted by living organisms in the deep ocean depths.", "The deep-sea comb jelly flashed with pulsing rainbow bioluminescence.", "by-oh-loo-mi-NES-uhns", "bi-o-lu-mi-nes-cence", "Stumbling over the six-syllable sequence.", "A comb jelly radiating iridescent neon rainbow light in pitch black ocean"),
        ("phosphorescence", "Luminescence that occurs without heat, seen in glowing sea water.", "Night kayakers marveled at the sparkling green phosphorescence in their wake.", "fahs-fuh-RES-uhns", "phos-pho-res-cence", "Stumbling over the consonant transitions.", "A kayak paddle stirring up glowing neon green phosphorescent sea water at night"),
        ("vibrations", "Plural of vibration; periodic acoustic waves traveling in seawater.", "Low-frequency sound vibrations from fin whales travel through ocean basins.", "vy-BRAY-shuhnz", "vi-bra-tions", "Saying 'vee-bra-tions' with long 'e'.", "An illustrated waveform showing acoustic soundwaves traveling in deep water"),
        ("harmonics", "A series of musical overtones produced in whale songs.", "Humpback whale songs contained rich haunting harmonics that changed each year.", "hahr-MAHN-iks", "har-mon-ics", "Saying 'har-mone-iks' with long 'o'.", "A visual spectrogram chart showing the harmonic frequency layers of a whale song"),
        ("resonance", "The quality of sound being deep, full, and reverberating.", "The deep resonance of the foghorn pierced through the thick coastal mist.", "REZ-uh-nuhns", "res-o-nance", "Saying 'ree-zo-nance' with long 'e'.", "A coastal lighthouse foghorn sounding with visible soundwaves in heavy fog"),
    ],
    # L30: 8+ letter ocean triumph & maritime mastery
    [
        ("magnificent", "Impressively beautiful, elaborate, or grand in scale.", "A magnificent pod of killer whales surfaced together in the golden sunset.", "mag-NIF-i-suhnt", "mag-nif-i-cent", "Saying 'mag-neef-i-cent' with wrong vowel.", "A magnificent killer whale orca leaping completely out of blue ocean water"),
        ("extraordinary", "Very unusual or remarkable; beyond what is ordinary.", "The beauty of the untouched underwater coral garden was extraordinary.", "ik-STROR-di-nair-ee", "ex-traor-di-nar-y", "Saying 'extra-ordinary' in six distinct syllables.", "A breathtaking underwater coral cathedral with sunbeams streaming down"),
        ("unshakeable", "Unable to be disputed or weakened; firm and resolute.", "Her unshakeable courage guided the sailboat safely through the stormy seas.", "uhn-SHAY-kuh-buhl", "un-shake-a-ble", "Saying 'un-shak-a-ble' with short 'a'.", "A steadfast sailor holding the helm wheel firmly in rolling blue ocean waves"),
        ("triumphant", "Having won a battle or contest; victorious and celebratory.", "The triumphant sailing team crossed the finish line to cheers from the shore.", "try-UHM-fuhnt", "tri-um-phant", "Saying 'tree-um-phant' with long 'e'.", "A cheering sailboat crew waving triumphantly as they cross the finish line"),
        ("invincible", "Too powerful to be defeated or overcome; resilient.", "Working together with trust, the diving expedition felt brave and invincible.", "in-VIN-suh-buhl", "in-vin-ci-ble", "Saying 'in-veen-ci-ble' with long 'e'.", "Scuba divers giving thumbs up triumphantly underwater near a coral wall"),
        ("accomplishment", "Something that has been achieved successfully through effort.", "Mapping the entire deep-sea coral canyon was a historic accomplishment.", "uh-KAHM-plish-muhnt", "ac-com-plish-ment", "Saying 'ac-cum-plish-ment' with short 'u'.", "A marine research team holding a finished high-resolution ocean floor map"),
        ("masterpiece", "A work of outstanding artistry, skill, or natural beauty.", "The vibrant Coral Cove was nature's breathtaking underwater masterpiece.", "MAS-ter-pees", "mas-ter-piece", "Saying 'mes-ter-piece' with short 'e'.", "A stunning panoramic underwater photo of a healthy thriving coral reef garden"),
    ],
]
