"""World 6: Cloud Kingdom (Levels 1 to 30, 210 unique words)."""
from __future__ import annotations

# Format: (text, meaning, sentence, hint, syllables, mistake, alt)
WORLD_6_LEVELS = [
    # L1: 4-5 letter sky foundation
    [
        ("sky", "The region of the atmosphere and outer space seen from the earth.", "A flock of white doves soared across the clear blue morning sky.", "SKY", "sky", "Saying 'skee' with long 'e'.", "A vast crystal clear azure blue sky with a few wispy white clouds"),
        ("air", "The invisible gaseous substance surrounding the earth.", "Cool fresh mountain air filled her lungs as she stood on the overlook.", "AIR", "air", "Saying 'ar' with flat short 'a'.", "Gentle wind ripples moving through high green mountain grass"),
        ("fly", "To move through the air using wings or aerodynamic forces.", "Eagles fly effortlessly by catching warm rising thermal air currents.", "FLY", "fly", "Saying 'flee' with long 'e'.", "A majestic white bird with outstretched wings flying gracefully in sky"),
        ("soar", "To fly or rise high in the air without flapping wings.", "Kites soar high above the grassy hilltop on windy spring afternoons.", "SOR", "soar", "Saying 'sore' with dropped vowel.", "A colorful diamond kite soaring high against a background of puffy clouds"),
        ("wing", "A modified forelimb for flying in birds and bats, or aerofoil in planes.", "The falcon tucked its left wing to dive sharply through the air.", "WING", "wing", "Saying 'ween' with long 'e'.", "The feathered wing of an eagle spread wide against the blue sky"),
        ("haze", "A slight obscuration of the lower atmosphere, typically caused by fine dust or heat.", "Morning haze lifted as the bright sun warmed the mountain valley.", "HAYZ", "haze", "Saying 'hez' with short 'e'.", "A soft golden atmospheric haze drifting over distant mountain peaks"),
        ("glow", "To give out steady light without a flame.", "Clouds at sunset began to glow with radiant shades of peach and violet.", "GLOH", "glow", "Saying 'glaw' with short 'o'.", "Puffy cumulus clouds glowing with warm orange and pink sunset light"),
    ],
    # L2: 5-letter atmospheric phenomena & flight
    [
        ("cloud", "A visible mass of condensed water vapor floating in the atmosphere.", "A fluffy white cloud drifted slowly across the bright blue sky.", "KLOWD", "cloud", "Saying 'clod' with short 'o'.", "A pure white fluffy cotton-like cumulus cloud in a bright blue sky"),
        ("glide", "To move with a smooth, continuous, and effortless motion through air.", "The hang glider was able to glide gracefully along the cliff ridge.", "GLYD", "glide", "Saying 'gleed' with long 'e'.", "A colorful triangular hang glider gliding smoothly through sunlit sky"),
        ("vapor", "A substance diffused or suspended in the air, especially water mist.", "Water vapor condensed into tiny sparkling droplets on the cold window.", "VAY-per", "va-por", "Saying 'vah-por' with short 'a'.", "White steam water vapor rising gently into cool mountain air"),
        ("storm", "A violent disturbance of the atmosphere with strong winds, rain, or thunder.", "Dark grey clouds gathered on the horizon before the afternoon storm.", "STORM", "storm", "Saying 'stahm' with wrong vowel.", "A dramatic dark storm cloud front with distant rain curtains falling"),
        ("frost", "Small white ice crystals formed on the ground or other surfaces when cold.", "Delicate frost patterns formed like lace on the cold glass pane.", "FRAWST", "frost", "Saying 'fruh-st' with short 'u'.", "Intricate crystalline ice frost patterns spreading across cold glass"),
        ("draft", "A current of cool or warm air in a room or in the atmosphere.", "An updraft of warm air lifted the hot air balloon higher into the sky.", "DRAFT", "draft", "Saying 'dreft' with short 'e'.", "An illustrated diagram showing rising warm thermal drafts lifting a glider"),
        ("flock", "A group of birds of one kind feeding, resting, or flying together.", "A V-shaped flock of migrating geese honked high in the autumn sky.", "FLAHK", "flock", "Saying 'flook' with long 'oo'.", "A flock of birds flying in a perfect V-formation across a sunset sky"),
    ],
    # L3: 5-letter optical sky phenomena
    [
        ("beams", "Plural of beam; distinct lines of light shining from a source.", "Sunbeams broke through the clouds, illuminating the green valley below.", "BEEMZ", "beams", "Saying 'bims' with short 'i'.", "Dramatic crepuscular sunbeams streaming through gaps in clouds onto a valley"),
        ("flair", "A sudden burst of bright light or a special natural talent.", "A solar flare burst from the surface of the sun into space.", "FLAIR", "flair", "Saying 'flee-er' with two syllables.", "A dramatic ultraviolet photo of a bright solar flare erupting from the sun"),
        ("shine", "To give out or reflect a bright light; be bright.", "Stars shine with steady crystal brilliance through the high thin air.", "SHYN", "shine", "Saying 'sheen' with long 'e'.", "A single radiant star shining brightly in a deep twilight sky"),
        ("spark", "A small fiery particle thrown off from a fire, or a trace of light.", "A tiny electrical spark leaped between the two metal contact spheres.", "SPAHRK", "spark", "Saying 'spork' with wrong vowel.", "A bright glowing blue electric spark jumping between two metal terminals"),
        ("halo", "A circle of white or colored light around the sun or moon.", "Ice crystals in cirrus clouds created a magnificent luminous halo around the sun.", "HAY-loh", "ha-lo", "Saying 'hah-loh' with short 'a'.", "A rare, perfect circular 22-degree rainbow ice halo around the sun"),
        ("prism", "A transparent glass body with triangular ends that separates white light.", "The glass prism refracted white sunlight into a spectrum of rainbow colors.", "PRIZ-uhm", "prism", "Saying 'pree-zuhm' with long 'e'.", "A triangular glass prism splitting a beam of white light into a rainbow"),
        ("comet", "A celestial object consisting of a nucleus of ice and a long luminous tail.", "Comet Halley sweeps through our solar system with a glowing dust tail.", "KAH-mit", "com-et", "Saying 'koh-mit' with long 'o'.", "A brilliant comet with a glowing blue ion tail streaking across starry space"),
    ],
    # L4: 6-letter cloud types & weather
    [
        ("cirrus", "High-altitude clouds characterized by thin, wispy feathery strands.", "Wispy white cirrus clouds signaled that fair weather would continue.", "SEER-uhs", "cir-rus", "Saying 'kee-rus' with hard 'c'.", "Delicate wispy white cirrus clouds stretching across a deep blue sky"),
        ("stratus", "Low-level clouds forming a continuous horizontal grey sheet.", "A low grey blanket of stratus clouds covered the valley in light mist.", "STRAY-tuhs", "stra-tus", "Saying 'strah-tus' with short 'a'.", "A smooth, uniform grey stratus cloud deck covering a mountain valley"),
        ("cumulus", "Puffy cotton-like clouds with flat bases and rounded outlines.", "Bright white cumulus clouds looked like giant heaps of fluffy cotton.", "KYOOM-yuh-luhs", "cu-mu-lus", "Skipping the 'yuh' syllable.", "Massive bright white puffy cumulus clouds building in a sunny summer sky"),
        ("nimbi", "Plural of nimbus; rain-bearing storm clouds.", "Dark grey nimbi gathered overhead as the rumble of thunder began.", "NIM-by", "nim-bi", "Saying 'neem-bee' with long 'e'.", "Heavy dark grey rain-bearing storm clouds hanging low over landscape"),
        ("aurora", "A natural electrical phenomenon characterized by streamers of reddish or greenish light.", "The emerald green aurora borealis danced across the arctic night sky.", "aw-ROR-uh", "au-ro-ra", "Saying 'ow-roh-rah' with wrong vowels.", "Vibrant curtains of glowing green and purple aurora borealis in night sky"),
        ("vapors", "Plural of vapor; diffused gaseous mists.", "Atmospheric water vapors condensed into puffy white cumulus clouds.", "VAY-perz", "va-pors", "Saying 'vah-perz' with short 'a'.", "Swirling white water vapors billowing into cool mountain air"),
        ("breeze", "A gentle, refreshing and light wind blowing high in the sky.", "A steady upper-level breeze propelled the colorful hot air balloon.", "BREEZ", "breeze", "Saying 'brees' with unvoiced 's'.", "A colorful hot air balloon drifting gently in a calm morning breeze"),
    ],
    # L5: 6-letter aviation & aeronautics
    [
        ("glider", "A light aircraft that is designed to fly without using an engine.", "The sleek white sailplane glider soared silently on mountain updrafts.", "GLY-der", "gli-der", "Saying 'glee-der' with long 'e'.", "A sleek white motorless sailplane glider soaring silently over peaks"),
        ("pilot", "A person who operates the flying controls of an aircraft.", "The skilled pilot performed a smooth, gentle landing on the runway.", "PY-luht", "pi-lot", "Saying 'pee-lot' with long 'e'.", "A focused airplane pilot in uniform sitting in the cockpit with headsets"),
        ("flier", "A person or thing that flies in the air.", "The peregrine falcon is the fastest natural flier in the animal kingdom.", "FLY-er", "fli-er", "Saying 'flee-er' with long 'e'.", "A bird with wings tucked diving at high speed through the sky"),
        ("hangar", "A large building with extensive floor area, for housing aircraft.", "The vintage biplane was parked safely inside the airport hangar.", "HANG-er", "hang-ar", "Saying 'han-gar' with hard 'g'.", "A spacious airport airplane hangar with arched steel beams housing planes"),
        ("rudder", "A flat vertical aerofoil pivoted at the tail of an airplane for steering.", "The pilot pressed the foot pedal to deflect the rudder to the left.", "RUHD-er", "rud-der", "Saying 'roo-der' with long 'oo'.", "The vertical tail stabilizer and movable rudder of a modern airplane"),
        ("engine", "A machine with moving parts that converts power into motion.", "The powerful jet engine propelled the passenger airplane into the clouds.", "EN-jin", "en-gine", "Saying 'en-gyn' with hard 'g'.", "A large modern turbofan jet engine mounted under the wing of an airliner"),
        ("runway", "A leveled strip of smooth ground on which aircraft take off and land.", "Runway lights illuminated the long asphalt strip in the evening twilight.", "RUHN-way", "run-way", "Saying 'roon-way' with long 'oo'.", "A long airport runway with glowing green and white center line lights"),
    ],
    # L6: 6-letter wind currents & weather instruments
    [
        ("airway", "A recognized regular route for airplanes in the sky.", "Air traffic controllers guided the passenger jet along its designated airway.", "AIR-way", "air-way", "Saying 'ahr-way' with wrong vowel.", "A map graphic showing invisible designated aerial flight path airways"),
        ("upwind", "Into or in the direction that the wind is blowing from.", "The sailing yacht tacked upwind into the refreshing coastal breeze.", "UHP-wind", "up-wind", "Saying 'up-wynd' with long 'i'.", "A sailboat leaning into the wind while tacking upwind across waves"),
        ("tailor", "Here referring to tailoring flight trims, or adjusting aerodynamic flaps.", "The aerodynamicist tailored the winglet curves to minimize fuel drag.", "TAY-ler", "tai-lor", "Saying 'tie-lor' with long 'i'.", "An engineer inspecting the curved winglet tip of an airliner wing"),
        ("updraft", "An upward current of gas, air, or other fluid.", "A powerful thermal updraft lifted the soaring hawk thousands of feet.", "UHP-draft", "up-draft", "Saying 'up-dreft' with short 'e'.", "An illustrated thermal column of warm air rising beneath a soaring hawk"),
        ("downdraft", "A downward current of gas or air, as in a thunderstorm.", "Pilots are trained to detect and avoid severe localized downdrafts.", "DOWN-draft", "down-draft", "Saying 'down-dreft' with short 'e'.", "An illustrated diagram of a cold air downdraft descending from a storm"),
        ("airship", "A power-driven aircraft that is kept buoyant by a gas lighter than air.", "The majestic silver airship floated silently through the morning clouds.", "AIR-ship", "air-ship", "Saying 'air-sheep' with long 'e'.", "A giant silver dirigible airship floating serenely above cloud banks"),
        ("clouds", "Plural of cloud; visible masses of condensed water vapor.", "Golden evening clouds reflected the setting sun across the horizon.", "KLOWDZ", "clouds", "Saying 'clodz' with short 'o'.", "A breathtaking view looking down across an endless sea of white clouds"),
    ],
    # L7: 6-letter storms & celestial optics
    [
        ("squall", "A sudden violent gust of wind or a localized storm.", "A sudden rain squall swept across the bay, whipping up whitecap waves.", "SKWAWL", "squall", "Saying 'skwal' with flat 'a'.", "A dark localized rain squall falling over the ocean under dark clouds"),
        ("corona", "The rarefied gaseous envelope of the sun and other stars.", "During a total solar eclipse, the glowing pearly white corona is visible.", "kuh-ROH-nuh", "co-ro-na", "Saying 'caw-ro-na' with wrong stress.", "A total solar eclipse showing the glowing white plasma corona ring"),
        ("zenith", "The time at which something is most powerful; the point directly overhead.", "The midday sun reached its highest point at the celestial zenith.", "ZEE-nith", "ze-nith", "Saying 'zen-eeth' with wrong vowels.", "A starry night sky chart showing the point directly overhead as zenith"),
        ("skyline", "An outline of land and buildings defined against the sky.", "The illuminated city skyline glowed brilliantly in the evening twilight.", "SKY-lyn", "sky-line", "Saying 'skee-line' with long 'e'.", "A modern city skyscraper skyline silhouetted against a golden sunset"),
        ("rainbow", "An arch of colors formed in the sky by refraction of light in water.", "A vivid double rainbow arched across the entire mountain valley.", "RAYN-boh", "rain-bow", "Saying 'ren-boh' with short 'e'.", "A brilliant complete semicircular rainbow spanning across green hills"),
        ("vapors", "Plural of vapor; moisture suspended in atmosphere.", "Morning vapors curled upward like white smoke from the forest floor.", "VAY-perz", "va-pors", "Saying 'vah-perz' with short 'a'.", "Misty white water vapors rising through morning sunbeams in a forest"),
        ("silver", "A shiny pale grey metallic color like cloud linings.", "Every dark cloud is said to have a bright and hopeful silver lining.", "SIL-ver", "sil-ver", "Saying 'seel-ver' with long 'e'.", "A dark storm cloud with a brilliant silver edge lit by the sun behind it"),
    ],
    # L8: 7-letter atmospheric layers & structures
    [
        ("airliner", "A large passenger aircraft operated by a commercial airline.", "The modern wide-body airliner cruised smoothly at thirty-five thousand feet.", "AIR-ly-ner", "air-lin-er", "Saying 'air-lee-ner' with long 'e'.", "A large commercial passenger airliner flying above white clouds in sun"),
        ("airplane", "A powered flying vehicle with fixed wings and propelled by engines.", "The twin-engine propeller airplane touched down gently on the airstrip.", "AIR-playn", "air-plane", "Saying 'air-plen' with short 'e'.", "A private twin-propeller airplane cruising over green patchwork fields"),
        ("aircraft", "An airplane, helicopter, or other machine capable of flight.", "Modern aircraft use lightweight carbon composite materials for efficiency.", "AIR-kraft", "air-craft", "Saying 'air-kreft' with short 'e'.", "A sleek composite aircraft soaring with wings reflecting sunlight"),
        ("aviation", "The flying or operating of aircraft, or aircraft manufacturing.", "The museum celebrated a century of progress in global commercial aviation.", "ay-vee-AY-shuhn", "a-vi-a-tion", "Saying 'av-ee-ay-shun' with short 'a'.", "A historical timeline display of early biplanes to modern jet aircraft"),
        ("floating", "Resting or moving on the surface of a liquid or buoyant in air.", "A cluster of colorful helium balloons was floating high in the sky.", "FLOH-ting", "float-ing", "Saying 'flaw-ting' with short 'o'.", "A bunch of colorful bright balloons floating upward into an azure sky"),
        ("soaring", "Flying or rising high in the air with outspread wings.", "A pair of red-tailed hawks were soaring gracefully in the thermal breeze.", "SOR-ing", "soar-ing", "Saying 'saw-ring' with short 'o'.", "A hawk soaring with spread wings high above a green mountain valley"),
        ("drifting", "Being carried along by a current of air or water.", "White cumulus clouds were drifting lazily across the summer sky.", "DRIF-ting", "drift-ing", "Saying 'dreef-ting' with long 'e'.", "Soft wispy white clouds drifting across the face of a crescent moon"),
    ],
    # L9: 7-letter optical atmospheric effects
    [
        ("rainbows", "Plural of rainbow; multicolored arches formed by water droplets.", "Waterfalls created shimmering miniature rainbows in the rising mist.", "RAYN-bohz", "rain-bows", "Saying 'ren-bohz' with short 'e'.", "Multiple vibrant rainbows forming in the mist of a majestic waterfall"),
        ("twilight", "The soft glowing light from the sky when the sun is below the horizon.", "Planets Venus and Jupiter shone like diamonds in the evening twilight.", "TWY-lyt", "twi-light", "Saying 'twee-light' with long 'e'.", "A purple and indigo gradient twilight sky with glowing evening planets"),
        ("sunbeams", "Plural of sunbeam; rays of sunlight shining through clouds.", "Golden sunbeams illuminated the misty forest floor like theater lights.", "SUHN-beemz", "sun-beams", "Saying 'soon-beams' with long 'oo'.", "Radiant sunbeams streaming down through gaps in a dark cloud deck"),
        ("sunburst", "A sudden burst of bright sunlight through breaking clouds.", "A dramatic sunburst painted the distant ocean waves in shimmering silver.", "SUHN-burst", "sun-burst", "Saying 'soon-burst' with long 'oo'.", "A dramatic sunburst exploding with light through breaking storm clouds"),
        ("daylight", "The natural light of the day when the sun is above the horizon.", "Long hours of summer daylight allowed them to hike late into the evening.", "DAY-lyt", "day-light", "Saying 'dey-light' with short 'e'.", "A bright sunlit landscape bathed in clear full daytime natural sunlight"),
        ("starlight", "The light that comes from the stars in the night sky.", "They navigated along the open trail illuminated solely by bright starlight.", "STAHR-lyt", "star-light", "Saying 'store-light' with wrong vowel.", "A crystal clear starry night with snow peaks illuminated by starlight"),
        ("moonbeam", "A ray of moonlight shining through the darkness of night.", "A silvery moonbeam illuminated the sleeping puppy on the rug.", "MOON-beem", "moon-beam", "Saying 'mun-beam' with short 'u'.", "A single silvery beam of moonlight shining through an open cottage window"),
    ],
    # L10: 7-letter storm dynamics & precipitation
    [
        ("cyclone", "A system of winds rotating inward to an area of low atmospheric pressure.", "Meteorologists tracked the rotating eye of the powerful ocean cyclone.", "SY-klohn", "cy-clone", "Saying 'see-clone' with long 'e'.", "A satellite hurricane spiral image of a massive cyclone over the ocean"),
        ("typhoon", "A tropical storm in the region of the Indian or western Pacific oceans.", "Coastal defenses braced for high tides as the typhoon approached land.", "ty-FOON", "ty-phoon", "Saying 'tee-foon' with long 'e'.", "Massive ocean waves crashing against sea walls during a tropical typhoon"),
        ("monsoon", "A seasonal prevailing wind in the region of South and Southeast Asia.", "Summer monsoon rains brought life-giving moisture to parched farm fields.", "mahn-SOON", "mon-soon", "Saying 'mun-soon' with short 'u'.", "Lush green rice paddy fields drinking in heavy tropical monsoon rains"),
        ("blizzard", "A severe snowstorm with high winds and blinding low visibility.", "The mountain rescue team waited out the zero-visibility winter blizzard.", "BLIZ-erd", "bliz-zard", "Saying 'bleez-zard' with long 'e'.", "Swirling white snow drifts and howling winds in a mountain blizzard"),
        ("tempest", "A violent windy storm accompanied by rain, hail, or snow.", "The ancient sailing vessel survived the fury of the northern tempest.", "TEM-pist", "tem-pest", "Saying 'tem-past' with overstressed ending.", "A dramatic painting of a wooden ship battling huge waves in a tempest"),
        ("downpour", "A heavy fall of rain occurring in a short period of time.", "A sudden tropical downpour filled the dry garden rain barrels in minutes.", "DOWN-por", "down-pour", "Saying 'down-pour' as 'down-par'.", "Heavy sheets of rain cascading down on a lush tropical garden terrace"),
        ("cloudlet", "A small, delicate, or wispy cloud in the sky.", "A single pink cloudlet hovered near the setting sun at twilight.", "KLOWD-lit", "cloud-let", "Saying 'clod-let' with short 'o'.", "A tiny pink and gold wispy cloudlet floating alone in a sunset sky"),
    ],
    # L11: 8+ letter ballooning & lighter-than-air flight
    [
        ("aerostat", "An aircraft that derives its lift from buoyancy, such as a balloon or blimp.", "The tethered helium aerostat provided high-altitude atmospheric monitoring.", "AIR-uh-stat", "aer-o-stat", "Saying 'ay-ro-stat' with wrong vowels.", "A large white tethered helium aerostat balloon floating above an airfield"),
        ("balloonist", "A person who flies in or navigates a hot air balloon.", "The skilled balloonist fired the propane burner to gain altitude gently.", "buh-LOO-nist", "bal-loon-ist", "Saying 'bal-lon-ist' with short 'o'.", "A smiling balloonist in a wicker basket firing the bright orange burner flame"),
        ("dirigible", "A steerable airship; an aircraft kept buoyant by gas lighter than air.", "The historic dirigible cruised smoothly above the clouds on its voyage.", "DIR-i-juh-buhl", "dir-i-gi-ble", "Saying 'di-rij-i-ble' with wrong stress.", "A giant silver dirigible airship with twin propellers cruising in sun"),
        ("altimeter", "An instrument used to measure the altitude of an object above a fixed level.", "The pilot glanced at the altimeter to verify their cruising altitude.", "al-TIM-i-ter", "al-tim-e-ter", "Saying 'AL-ti-mee-ter' with wrong stress.", "A precision aircraft altimeter instrument gauge showing feet of elevation"),
        ("barograph", "A barometer that automatically records variations in atmospheric pressure.", "The weather station's barograph drew a steady ink line on the drum.", "BAIR-uh-graf", "bar-o-graph", "Saying 'buh-rah-graf' with wrong vowels.", "An antique brass recording drum barograph drawing ink pressure lines"),
        ("anemograph", "An instrument for measuring and continuously recording wind velocity.", "The wind turbine park monitored gusts using a computerized anemograph.", "an-uh-MAHM-uh-graf", "an-e-mo-graph", "Stumbling over the multisyllabic rhythm.", "A digital scientific station recording live continuous wind gust data charts"),
        ("parachutes", "Plural of parachute; cloth canopies used for slowing descents.", "Colorful round parachutes opened gracefully, slowing the payload safely.", "PAIR-uh-shoots", "par-a-chutes", "Saying 'par-a-chutes' with 'ch' sound.", "Three colorful round cargo parachutes drifting down gently over a meadow"),
    ],
    # L12: 8+ letter atmospheric layers & science
    [
        ("troposphere", "The lowest region of the atmosphere extending from the earth's surface.", "Nearly all weather clouds and storms occur within the active troposphere.", "TROH-puh-sfeer", "tro-po-sphere", "Saying 'trah-po-sphere' with short 'o'.", "An educational diagram showing atmospheric layers from ground to space"),
        ("stratosphere", "The layer of the earth's atmosphere above the troposphere.", "Commercial airliners cruise in the calm lower layer of the stratosphere.", "STRAT-uh-sfeer", "strat-o-sphere", "Saying 'stray-to-sphere' with long 'a'.", "Looking out an airplane window at the smooth curvature of the stratosphere"),
        ("mesosphere", "The region of the earth's atmosphere above the stratosphere.", "Meteors burn up as bright shooting stars within the cold mesosphere.", "MEZ-uh-sfeer", "mes-o-sphere", "Saying 'mee-zo-sphere' with long 'e'.", "A scientific graphic showing shooting star meteors disintegrating in mesosphere"),
        ("thermosphere", "The region of the atmosphere above the mesosphere characterized by high temperature.", "The International Space Station orbits Earth within the high thermosphere.", "THUR-muh-sfeer", "ther-mo-sphere", "Saying 'ther-moh-sfeer' with wrong vowel.", "The International Space Station orbiting Earth against a glowing thin blue rim"),
        ("exosphere", "The outermost region of a planet's atmosphere.", "In the ultra-thin exosphere, atmospheric gases gradually fade into deep space.", "EK-soh-sfeer", "ex-o-sphere", "Saying 'ex-uh-sfeer' with dropped vowel.", "An artistic space view showing Earth's outermost blue atmospheric exosphere ring"),
        ("ionosphere", "The layer of the atmosphere containing a high concentration of ions.", "Radio signals bounce off the reflective ionosphere to travel around the globe.", "eye-AHN-uh-sfeer", "i-on-o-sphere", "Saying 'ee-on-o-sphere' with long 'e'.", "A diagram showing high-frequency radio waves bouncing between Earth and ionosphere"),
        ("ozonosphere", "Another term for the ozone layer, which absorbs harmful ultraviolet light.", "The protective ozonosphere shields life on Earth from harmful radiation.", "oh-ZOH-nuh-sfeer", "o-zon-o-sphere", "Saying 'oz-on-o-sphere' with short 'o'.", "An illustrated graphic showing the ozone layer shielding Earth from sun rays"),
    ],
    # L13: 8+ letter lightning & electrical phenomena
    [
        ("lightning", "The occurrence of a natural electrical discharge of very short duration.", "A jagged bolt of blue lightning illuminated the dramatic thundercloud.", "LYT-ning", "light-ning", "Saying 'light-en-ing' with extra syllable.", "A brilliant branched fork of blue lightning striking across dark storm clouds"),
        ("thunderbolt", "A flash of lightning with a simultaneous crash of thunder.", "A powerful thunderbolt struck the high metal lightning rod safely.", "THUHN-der-bohlt", "thun-der-bolt", "Dropping the 'th' sound.", "A dramatic single thunderbolt lightning strike illuminating a rocky hilltop"),
        ("thundercloud", "A cumulus cloud producing thunder, lightning, and rain.", "The anvil-shaped thundercloud towered forty thousand feet into the sky.", "THUHN-der-klowd", "thun-der-cloud", "Saying 'tun-der-cloud' and dropping 'th'.", "A massive towering anvil-topped cumulonimbus thundercloud at golden hour"),
        ("cumulonimbus", "A cloud forming a towering mass with a flat anvil top, bringing thunderstorms.", "The cumulonimbus produced torrential rain, hail, and dazzling lightning.", "kyoo-myuh-loh-NIM-buhs", "cu-mu-lo-nim-bus", "Stumbling over the five-syllable sequence.", "A majestic isolated supercell cumulonimbus cloud rotating over open plains"),
        ("electrification", "The process of charging something with electricity.", "Friction between ice particles causes rapid electrification within storm clouds.", "i-lek-truh-fi-KAY-shuhn", "e-lec-tri-fi-ca-tion", "Skipping the 'tri' syllable.", "An educational animation diagram showing positive and negative charge buildup in a cloud"),
        ("bioelectricity", "Electric phenomena in living organisms, studied in sensory biology.", "Some marine and nocturnal organisms utilize subtle bioelectricity to navigate.", "by-oh-i-lek-TRIS-i-tee", "bi-o-e-lec-tric-i-ty", "Stumbling over the seven-syllable sequence.", "A glowing scientific rendering of electrical impulses traveling through neurons"),
        ("luminescent", "Emitting light not caused by heat; glowing with soft light.", "The edges of the high cirrus clouds glowed with bright luminescent color.", "loo-mi-NES-uhnt", "lu-mi-nes-cent", "Saying 'lu-meen-es-cent' with long 'e'.", "Luminescent iridescent pastel rainbow clouds glowing near the sun in blue sky"),
    ],
    # L14: 8+ letter aeronautical engineering & flight
    [
        ("aerodynamics", "The study of the properties of moving air and the forces on bodies in air.", "Engineers designed the aircraft with sleek aerodynamics to reduce drag.", "air-oh-dy-NAM-iks", "aer-o-dy-nam-ics", "Saying 'ay-ro-dy-nam-iks' with wrong vowels.", "A model airplane inside a wind tunnel showing colored smoke streamlines flowing"),
        ("aeronautics", "The science or practice of travel through the air.", "Her passion for aeronautics inspired her to build remote-controlled gliders.", "air-uh-NAW-tiks", "aer-o-nau-tics", "Saying 'ay-ro-naw-tiks' with wrong vowels.", "An engineer using computer-aided design software to model airplane wings"),
        ("turbofan", "A jet engine in which a fan assists the flow of air.", "The modern turbofan engine delivered immense thrust with quiet efficiency.", "TUR-boh-fan", "tur-bo-fan", "Saying 'toor-boh-fan' with long 'oo'.", "A high-bypass turbofan jet engine with shiny curved titanium fan blades"),
        ("turboprop", "A jet engine designed to drive a propeller.", "The regional commuter airplane was powered by two reliable turboprop engines.", "TUR-boh-prahp", "tur-bo-prop", "Saying 'toor-boh-prop' with long 'oo'.", "A four-bladed composite propeller spinning on a sleek turboprop engine cowl"),
        ("fuselage", "The main body of an aircraft that holds crew, passengers, or cargo.", "The lightweight aluminum fuselage was engineered to withstand high cabin pressure.", "FYOO-zuh-lahzh", "fu-se-lage", "Saying 'fyoo-suh-layj' with hard 'j'.", "The streamlined polished white fuselage body of an airliner on the tarmac"),
        ("empennage", "The tail assembly of an aircraft, providing stability during flight.", "The empennage consists of the vertical fin, rudder, stabilizer, and elevators.", "ahm-puh-NAHZH", "em-pen-nage", "Stumbling over the French origin word.", "A diagram highlighting the horizontal and vertical tail empennage of an aircraft"),
        ("stabilizer", "A horizontal aerofoil at the tail of an aircraft for pitch stability.", "The pilot trimmed the horizontal stabilizer to maintain level cruising flight.", "STAY-buh-ly-zer", "sta-bi-liz-er", "Saying 'stah-bi-li-zer' with short 'a'.", "The horizontal tail stabilizer wing of an airplane viewed against blue sky"),
    ],
    # L15: 8+ letter celestial bodies & astronomy
    [
        ("constellations", "Plural of constellation; patterns of stars in the night sky.", "Stargazers identified the ancient constellations of Pegasus and Cygnus.", "kahn-stuh-LAY-shuhnz", "con-stel-la-tions", "Skipping the 'la' syllable.", "A star chart showing illustrated mythical figures drawn over constellations"),
        ("observatories", "Plural of observatory; facilities equipped with telescopes.", "High-altitude mountaintop observatories enjoy cloud-free stargazing nights.", "uhb-ZUR-vuh-tor-eez", "ob-ser-va-to-ries", "Saying 'ob-zer-va-treez' with dropped syllable.", "A cluster of white astronomical observatory domes under a starry galaxy sky"),
        ("astrophotography", "The photography of astronomical objects and celestial events.", "Her deep-sky astrophotography captured the swirling arms of the Andromeda galaxy.", "as-troh-fuh-TAHG-ruh-fee", "as-tro-pho-tog-ra-phy", "Stumbling over the six-syllable sequence.", "A stunning high-resolution colorful photo of the spiral Andromeda galaxy"),
        ("astronomer", "An expert in the study of stars, planets, and outer space.", "The astronomer discovered a new periodic comet orbiting the solar system.", "uh-STRAHN-uh-mer", "as-tron-o-mer", "Saying 'as-tro-no-mer' with wrong stress.", "An astronomer adjusting the digital camera on a large observatory telescope"),
        ("planetarium", "A domed theater in which representations of celestial objects are shown.", "School students marveled at the digital planetarium show about the solar system.", "plan-i-TAIR-ee-uhm", "plan-e-tar-i-um", "Saying 'plan-ee-tahr-ee-um' with wrong vowels.", "Students looking upward in a planetarium at a giant projected Milky Way galaxy"),
        ("spectrometer", "An instrument used to measure properties of light over a spectrum.", "The telescope's spectrometer determined the chemical makeup of distant stars.", "spek-TRAHM-i-ter", "spec-trom-e-ter", "Saying 'SPEC-tro-mee-ter' with wrong stress.", "A laboratory spectrometer displaying a rainbow light spectrum analysis graph"),
        ("heliosphere", "The vast bubble of space dominated by the sun's magnetic field and solar wind.", "Voyager 1 crossed the boundary of the heliosphere into interstellar space.", "HEE-lee-uh-sfeer", "he-li-o-sphere", "Saying 'hel-ee-o-sphere' with short 'e'.", "An astronomical illustration showing the sun's bubble heliosphere in the galaxy"),
    ],
    # L16: 8+ letter meteorological sciences
    [
        ("meteorology", "The branch of science concerned with the processes of the atmosphere.", "Modern meteorology utilizes satellite imagery and radar to forecast weather.", "mee-tee-uh-RAHL-uh-jee", "me-te-o-rol-o-gy", "Saying 'mee-tor-ol-o-gy' with dropped syllables.", "A meteorologist presenting a dynamic weather radar map on a news studio screen"),
        ("anemometer", "An instrument for measuring the speed and pressure of the wind.", "The digital anemometer recorded peak wind gusts of seventy miles per hour.", "an-uh-MAHM-i-ter", "an-e-mome-ter", "Saying 'AN-e-mo-mee-ter' with wrong stress.", "A spinning metal three-cup anemometer mounted atop a weather station tower"),
        ("radiosonde", "An instrument carried by a balloon into the atmosphere to transmit data.", "Meteorologists released a helium weather balloon carrying a radiosonde package.", "RAY-dee-oh-sahnd", "ra-di-o-sonde", "Saying 'ray-dee-oh-sond-ee' with extra vowel.", "A large white weather balloon being released carrying a small radiosonde box"),
        ("barometers", "Plural of barometer; instruments measuring atmospheric pressure.", "Digital barometers on weather buoys detected changes in ocean air pressure.", "buh-RAHM-i-terz", "ba-rom-e-ters", "Saying 'bair-oh-mee-terz' with wrong stress.", "A display of antique and modern digital barometers on a laboratory desk"),
        ("hygrometer", "An instrument for measuring the humidity of the air or a gas.", "The digital hygrometer registered sixty percent relative humidity in the room.", "hy-GRAHM-i-ter", "hy-grom-e-ter", "Saying 'HY-gro-mee-ter' with wrong stress.", "A digital electronic hygrometer showing temperature and relative humidity numbers"),
        ("stratification", "The formation of water or air into separate distinct temperature layers.", "Thermal stratification in the atmosphere can trap fog in mountain valleys.", "strat-uh-fi-KAY-shuhn", "strat-i-fi-ca-tion", "Stumbling over the multisyllabic flow.", "An illustrated atmosphere cross-section showing warm air trapping cool air below"),
        ("precipitation", "Rain, snow, sleet, or hail that falls to the ground.", "The weather forecast called for scattered afternoon precipitation in the valley.", "pri-sip-i-TAY-shuhn", "pre-cip-i-ta-tion", "Saying 'pre-sip-tay-shun' with dropped syllable.", "An illustrated chart showing rain, snow, hail, and sleet precipitation types"),
    ],
    # L17: 8+ letter solar optics & rainbows
    [
        ("iridescent", "Showing luminous colors that seem to change when seen from different angles.", "The cloud showed breathtaking iridescent rainbow colors near the sun.", "eer-i-DES-uhnt", "ir-i-des-cent", "Saying 'eye-ri-des-cent' with long 'i'.", "An iridescent pastel mother-of-pearl cloud glowing with rainbow colors"),
        ("diffraction", "The process by which a beam of light is spread out as a result of passing an edge.", "Diffraction of sunlight through cloud water droplets created a glowing corona.", "di-FRAK-shuhn", "dif-frac-tion", "Saying 'dee-frak-shun' with long 'e'.", "A laser beam passing through a narrow slit creating a diffraction light pattern"),
        ("refraction", "The fact or phenomenon of light being deflected in passing through a medium.", "Refraction of light through raindrops creates the colorful arch of a rainbow.", "ri-FRAK-shuhn", "re-frac-tion", "Saying 'ree-frak-shun' with hard 's'.", "A glass prism bending and refracting a white beam of light into pure colors"),
        ("polarization", "The action of restricting the vibrations of a transverse wave.", "Polarized sunglasses reduce glare by blocking horizontal light polarization.", "poh-luh-ri-ZAY-shuhn", "po-lar-i-za-tion", "Skipping the 'ri' syllable.", "Looking through a polarized filter showing crystal clear blue water without glare"),
        ("bioluminescence", "Light emitted by living organisms in the atmosphere or ocean.", "Glowworms in the high cave ceiling resembled a ceiling of glowing stars.", "by-oh-loo-mi-NES-uhns", "bi-o-lu-mi-nes-cence", "Stumbling over the six-syllable sequence.", "Thousands of tiny blue glowing bioluminescent glowworms on a cave ceiling"),
        ("phosphorescence", "Light emitted by a substance without combustion or perceptible heat.", "The cloud ionization experiment left a soft green phosphorescence in the tube.", "fahs-fuh-RES-uhns", "phos-pho-res-cence", "Stumbling over the consonant transitions.", "A glass laboratory tube glowing with soft green phosphorescent gas plasma"),
        ("fluorescence", "The emission of light by a substance that has absorbed light or radiation.", "Minerals in the high mountain rocks exhibited brilliant fluorescence under UV.", "flaw-RES-uhns", "flu-o-res-cence", "Saying 'floo-or-es-cence' with wrong stress.", "Minerals glowing neon green and red under an ultraviolet blacklight in a dark room"),
    ],
    # L18: 8+ letter aerospace & flight navigation
    [
        ("stratospheric", "Relating to the stratosphere, the atmospheric layer above the troposphere.", "High-altitude scientific balloons conducted stratospheric ozone measurements.", "strat-uh-SFEER-ik", "strat-o-spher-ic", "Saying 'stray-to-sfeer-ik' with long 'a'.", "A large scientific balloon floating in the dark blue stratospheric sky"),
        ("interstellar", "Occurring or situated between the stars in space.", "Deep space robotic probes are traveling outward into interstellar space.", "in-ter-STEL-er", "in-ter-stel-lar", "Saying 'in-ter-steh-lar' with wrong stress.", "An artist rendering of a robotic space probe cruising among distant stars"),
        ("navigation", "The process or activity of accurately ascertaining one's position and route.", "Modern satellite GPS navigation allows precision automated airplane landings.", "nav-i-GAY-shuhn", "nav-i-ga-tion", "Saying 'nay-vi-ga-tion' with long 'a'.", "An electronic glass cockpit flight display screen showing a 3D navigation map"),
        ("aeronavigation", "The art or science of conducting aircraft from place to place.", "Pilots master aeronavigation principles including dead reckoning and VOR.", "air-oh-nav-i-GAY-shuhn", "aer-o-nav-i-ga-tion", "Stumbling over the seven-syllable sequence.", "A flight instructor teaching a student pilot with navigational plotters on a chart"),
        ("flightdeck", "The cockpit of a large aircraft containing controls and instruments.", "The pilots monitored digital flight computers from the modern glass flightdeck.", "FLYT-dek", "flight-deck", "Saying 'flayt-deck' with wrong vowel.", "The illuminated multi-screen computerized glass flightdeck cockpit of an airliner"),
        ("autopilot", "An electronic device for keeping an aircraft on a set course automatically.", "The flight crew engaged the digital autopilot for the long ocean crossing.", "AW-toh-py-luht", "au-to-pi-lot", "Saying 'ow-toh-pee-lot' with wrong vowels.", "An illuminated modern autopilot control panel on the dashboard of an aircraft"),
        ("turbofan", "A jet engine in which a fan assists the flow of air.", "Ultra-quiet turbofan engines reduced airplane noise for airport communities.", "TUR-boh-fan", "tur-bo-fan", "Saying 'toor-boh-fan' with long 'oo'.", "Engineers assembling the huge composite fan blades of a modern turbofan engine"),
    ],
    # L19: 8+ letter celestial phenomena & northern lights
    [
        ("auroraborealis", "The northern lights; glowing streamers in the arctic night sky.", "The dazzling green aurora borealis danced in shimmering curtains above the pines.", "aw-ROR-uh-bor-ee-AL-is", "au-ro-ra-bo-re-al-is", "Stumbling over the eight-syllable Latin phrase.", "A breathtaking panoramic photo of green and magenta aurora borealis over snow"),
        ("auroraaustralis", "The southern lights; glowing streamers in the antarctic night sky.", "Scientists at the South Pole observed brilliant ribbons of aurora australis.", "aw-ROR-uh-aw-STRAY-lis", "au-ro-ra-aus-tra-lis", "Stumbling over the eight-syllable Latin phrase.", "Vibrant violet and green aurora australis dancing over Antarctic ice domes"),
        ("magnetosphere", "The region surrounding the earth in which its magnetic field is predominant.", "Earth's protective magnetosphere deflects high-energy solar particle radiation.", "mag-NEE-tuh-sfeer", "mag-ne-to-sphere", "Saying 'mag-net-o-sphere' with short 'e'.", "An illustrated diagram showing Earth's blue magnetic field lines in space"),
        ("solarwind", "The continuous flow of charged particles from the sun into space.", "Electrons in the solar wind collide with oxygen atoms to create glowing auroras.", "SOH-ler-wind", "so-lar-wind", "Saying 'sah-lar-wind' with short 'o'.", "A space graphic showing solar wind streams flowing from the sun toward Earth"),
        ("geomagnetic", "Relating to the magnetic field of the earth.", "A strong geomagnetic storm caused auroras to be visible far south of the poles.", "jee-oh-mag-NET-ik", "ge-o-mag-net-ic", "Saying 'jee-oh-mag-nee-tik' with long 'e'.", "A scientific compass needle responding to geomagnetic flux lines on a monitor"),
        ("astronomy", "The scientific study of celestial bodies, space, and the universe.", "Studying astronomy broadens our perspective of our place in the cosmos.", "uh-STRAHN-uh-mee", "as-tron-o-my", "Saying 'as-tro-no-my' with wrong stress.", "An astronomer pointing a laser pointer at celestial constellations in night sky"),
        ("astrophysicist", "An expert in the physics of celestial bodies and space.", "The astrophysicist analyzed data from the space telescope to model black holes.", "as-troh-FIZ-i-sist", "as-tro-phys-i-cist", "Stumbling over the six-syllable sequence.", "A scientist in an observatory reviewing deep-space data on computer screens"),
    ],
    # L20: 8+ letter cloud kingdom architecture & fantasy
    [
        ("cloudcastle", "A fantasy castle constructed high among fluffy white clouds.", "Golden spires of the cloud castle rose majestically above the cumulus banks.", "KLOWD-kas-uhl", "cloud-cas-tle", "Pronouncing the silent 't' in castle.", "A magical fairytale white marble castle resting atop billowing golden clouds"),
        ("palaces", "Plural of palace; large and impressive official residences.", "Gleaming crystal palaces glittered in the upper atmosphere of the kingdom.", "PAL-i-siz", "pal-ac-es", "Saying 'pay-lah-sez' with long 'a'.", "Majestic gleaming palaces with towers and domes resting in glowing sunset clouds"),
        ("aerostatics", "The branch of statics that deals with equilibrium of gaseous bodies.", "Principles of aerostatics govern how lighter-than-air airships achieve lift.", "air-oh-STAT-iks", "aer-o-stat-ics", "Saying 'ay-ro-stah-tiks' with wrong vowels.", "An illustrated diagram showing buoyant gas displacement balancing gravitational weight"),
        ("equilibrium", "A state in which opposing forces or influences are balanced.", "The hot air balloon hovered in perfect equilibrium at five thousand feet.", "ee-kwuh-LIB-ree-uhm", "e-qui-lib-ri-um", "Saying 'ek-wuh-lib-ree-um' with short 'e'.", "A hot air balloon floating completely motionless in calm sunlit morning air"),
        ("architecture", "The art or practice of designing majestic buildings.", "Soaring cloud architecture featured delicate bridges made of solidified rainbow light.", "AHR-ki-tek-cher", "ar-chi-tec-ture", "Saying 'ar-chee-tek-toor' with 'ch' sound.", "A futuristic floating city with soaring graceful towers connected by arches"),
        ("breathtaking", "Astonishing or awe-inspiring in appearance or scale.", "The view looking down at a sea of endless clouds at sunrise was breathtaking.", "BRETH-tay-king", "breath-tak-ing", "Saying 'breeth-tay-king' with long 'ee'.", "A breathtaking aerial view of endless golden cloud waves under a sunrise sky"),
        ("monumental", "Great in importance, extent, or size; imposing.", "The monumental storm cloud towered higher than Mount Everest into the sky.", "mahn-yuh-MEN-tuhl", "mon-u-men-tal", "Skipping the 'u' syllable.", "A colossal cumulonimbus storm cloud rising like a monumental white pillar"),
    ],
    # L21: 8+ letter atmospheric optics & light
    [
        ("crepuscular", "Relating to twilight; rays of sunlight streaming through clouds.", "Stunning crepuscular rays radiated downward like spokes of a golden wheel.", "kri-PUHS-kyuh-ler", "cre-pus-cu-lar", "Stumbling over the four-syllable sequence.", "Dramatic crepuscular sunbeams bursting through dark clouds over hills"),
        ("anticrepuscular", "Rays of sunlight that converge on the point opposite the sun at sunset.", "Anticrepuscular rays formed a dramatic fan of pink light across the eastern sky.", "an-tee-kri-PUHS-kyuh-ler", "an-ti-cre-pus-cu-lar", "Stumbling over the seven-syllable sequence.", "Pink and blue anticrepuscular light rays converging in the eastern sunset sky"),
        ("circumzenithal", "An arc of rainbow colors resembling an upside-down rainbow near zenith.", "A dazzling circumzenithal arc smiled brightly in the high icy cirrus clouds.", "sur-kuhm-ZEN-i-thuhl", "cir-cum-zen-i-thal", "Stumbling over the six-syllable sequence.", "A brilliant upside-down rainbow circumzenithal arc glowing high above sun"),
        ("parhelion", "A bright spot in the sky on either side of the sun; a sundog.", "A brilliant parhelion sundog glittered with rainbow colors beside the sun.", "pahr-HEE-lee-uhn", "par-he-li-on", "Saying 'par-hel-ee-on' with short 'e'.", "Two bright rainbow sundogs flanking the sun through a thin veil of ice clouds"),
        ("parhelia", "Plural of parhelion; bright luminous spots on either side of the sun.", "Twin parhelia flanked the morning sun like glowing rainbow sentinels.", "pahr-HEE-lee-uh", "par-he-li-a", "Saying 'par-hel-ee-ah' with short 'e'.", "A full winter ice halo display showing sun dogs parhelia on both sides of sun"),
        ("infrasound", "Sound waves with a frequency below the lower limit of human audibility.", "Volcanic eruptions and aurora borealis generate low-frequency infrasound waves.", "IN-fruh-sownd", "in-fra-sound", "Saying 'in-frah-sownd' with wrong vowel.", "A scientific waveform display measuring ultra-low-frequency atmospheric waves"),
        ("spectroscopy", "The branch of science concerned with the investigation of spectra.", "Atmospheric spectroscopy verified the presence of water vapor and ozone.", "spek-TRAHS-kuh-pee", "spec-tros-co-py", "Saying 'SPEC-tro-sco-py' with wrong stress.", "A laboratory spectral analysis monitor displaying colored emission lines"),
    ],
    # L22: 8+ letter high-altitude flight & balloons
    [
        ("stratostat", "A balloon designed for high-altitude stratospheric exploration.", "Pioneering balloonists sealed themselves in a spherical gondola beneath the stratostat.", "STRAT-uh-stat", "strat-o-stat", "Saying 'stray-to-stat' with long 'a'.", "A massive plastic stratospheric research balloon ascending into thin air"),
        ("superpressure", "A balloon whose internal gas pressure remains higher than ambient air.", "Ultra-long-duration superpressure balloons can float around the globe for months.", "SOO-per-PRESH-er", "su-per-pres-sure", "Skipping the 'per' syllable.", "A giant pumpkin-shaped transparent scientific superpressure balloon aloft"),
        ("transosonde", "A meteorological balloon that floats at constant pressure across oceans.", "The transosonde collected wind and temperature data across the Pacific Ocean.", "TRANZ-uh-sahnd", "trans-o-sonde", "Saying 'trans-oh-sond-ee' with extra vowel.", "A high-tech transosonde instrument package transmitting satellite telemetry"),
        ("heliosphere", "The vast bubble of space dominated by the sun's solar wind.", "Cosmic rays from deep space are deflected by the magnetic heliosphere.", "HEE-lee-uh-sfeer", "he-li-o-sphere", "Saying 'hel-ee-o-sphere' with short 'e'.", "An artistic graphic of our solar system shielded inside the golden heliosphere"),
        ("photovoltaics", "The conversion of light into electricity using semiconductor cells.", "High-altitude solar airplanes rely on lightweight, flexible photovoltaics.", "foh-toh-vahl-TAY-iks", "pho-to-vol-ta-ics", "Stumbling over the vowel transitions.", "A futuristic solar-powered long-wing drone airplane covered in solar cells"),
        ("aerodynamically", "In a way that relates to the forces of air on moving bodies.", "The aircraft's fuselage was aerodynamically contoured for minimum drag.", "air-oh-dy-NAM-ik-lee", "aer-o-dy-nam-i-cal-ly", "Stumbling over the seven-syllable sequence.", "A computer simulation showing smooth airflow lines moving around a plane body"),
        ("telecommunications", "Communication over a distance by cable, telegraph, telephone, or radio.", "High-altitude atmospheric drones provide regional telecommunications coverage.", "tel-i-kuh-myoo-ni-KAY-shuhnz", "tel-e-com-mu-ni-ca-tions", "Stumbling over the eight-syllable sequence.", "A high-altitude solar aircraft relaying wireless communications to a town below"),
    ],
    # L23: 8+ letter meteorology & atmospheric forecasting
    [
        ("radiosondes", "Plural of radiosonde; sensor packages carried aloft by weather balloons.", "Twice daily, global weather services release hundreds of radiosondes.", "RAY-dee-oh-sahndz", "ra-di-o-sondes", "Saying 'ray-dee-oh-sond-eez' with extra vowel.", "A meteorological technician launching a large weather balloon with radiosonde"),
        ("barometers", "Plural of barometer; instruments measuring atmospheric pressure.", "Digital barometers on mountaintops detected the incoming cold front.", "buh-RAHM-i-terz", "ba-rom-e-ters", "Saying 'bair-oh-mee-terz' with wrong stress.", "A bank of high-precision digital barometer readouts in a weather station"),
        ("anemometers", "Plural of anemometer; wind speed measuring instruments.", "Ultrasonic anemometers have no moving parts and measure wind in three axes.", "an-uh-MAHM-i-terz", "an-e-mome-ters", "Saying 'AN-e-mo-mee-terz' with wrong stress.", "A high-tech sonic anemometer instrument measuring 3D wind velocity on a tower"),
        ("hygrometers", "Plural of hygrometer; devices measuring atmospheric humidity.", "Precision hygrometers monitored the moisture level inside the air museum.", "hy-GRAHM-i-terz", "hy-grom-e-ters", "Saying 'HY-gro-mee-terz' with wrong stress.", "A set of electronic hygrometer sensors displaying relative humidity graphs"),
        ("microclimate", "The climate of a very small or restricted local area.", "The sun-warmed south face of the cloud canyon had its own microclimate.", "MY-kroh-kly-mit", "mi-cro-cli-mate", "Saying 'my-cro-cly-mayt' with wrong ending.", "An illustrated diagram showing localized wind and moisture in a microclimate"),
        ("stratospheric", "Relating to the stratosphere layer of the atmosphere.", "Stratospheric winds blow in steady high-speed jet streams across continents.", "strat-uh-SFEER-ik", "strat-o-spher-ic", "Saying 'stray-to-sfeer-ik' with long 'a'.", "A global weather map showing high-speed meandering jet stream wind rivers"),
        ("precipitation", "Any form of water that falls from clouds and reaches the ground.", "Snow, sleet, hail, and rain are the four primary forms of precipitation.", "pri-sip-i-TAY-shuhn", "pre-cip-i-ta-tion", "Skipping the 'i' syllable.", "An infographic showing rain, snow crystals, and hail stones precipitation"),
    ],
    # L24: 8+ letter celestial navigation & astronomy
    [
        ("constellation", "A recognized pattern of stars forming an imaginary picture.", "The constellation Ursa Major contains the famous asterism of the Big Dipper.", "kahn-stuh-LAY-shuhn", "con-stel-la-tion", "Skipping the 'la' syllable.", "A starry night sky showing the connected lines of constellation Ursa Major"),
        ("planetarium", "A building where realistic images of stars and planets are projected.", "The planetarium projector displayed the night sky as seen from Mars.", "plan-i-TAIR-ee-uhm", "plan-e-tar-i-um", "Saying 'plan-ee-tahr-ee-um' with wrong vowels.", "A circular planetarium theater dome showing high-resolution star projections"),
        ("observatories", "Plural of observatory; facilities equipped with giant telescopes.", "Astronomical observatories high in the mountains peer deep into the cosmos.", "uhb-ZUR-vuh-tor-eez", "ob-ser-va-to-ries", "Saying 'ob-zer-va-treez' with dropped syllable.", "Telescope domes with open shutters pointing toward the Milky Way galaxy"),
        ("telescopes", "Plural of telescope; optical instruments for viewing distant space.", "Space telescopes orbit high above Earth's atmosphere for crystal-clear images.", "TEL-uh-skohps", "tel-e-scopes", "Saying 'tee-lee-scopes' with long 'e'.", "The James Webb and Hubble space telescopes orbiting in deep star-filled space"),
        ("astronomers", "Plural of astronomer; scientists who study celestial bodies.", "Astronomers collaborated globally to capture the first image of a black hole.", "uh-STRAHN-uh-merz", "as-tron-o-mers", "Saying 'as-tro-no-merz' with wrong stress.", "A team of astronomers celebrating at computer monitors in an observatory control room"),
        ("spectrometers", "Plural of spectrometer; instruments analyzing light spectra.", "Infrared spectrometers detected methane and oxygen in an exoplanet atmosphere.", "spek-TRAHM-i-terz", "spec-trom-e-ters", "Saying 'SPEC-tro-mee-terz' with wrong stress.", "A laboratory display showing rainbow spectral line readouts on screens"),
        ("celestial", "Relating to the sky or outer space as observed in astronomy.", "Celestial navigation relies on measuring the altitude of sun and stars.", "suh-LES-chuhl", "ce-les-tial", "Saying 'see-les-tee-al' with four syllables.", "A vintage celestial star globe map with brass gimbal rings on an oak table"),
    ],
    # L25: 8+ letter environmental protection & clean air
    [
        ("sustainability", "The avoidance of the depletion of natural resources to maintain balance.", "Renewable wind energy is vital for global atmospheric sustainability.", "suh-stay-nuh-BIL-i-tee", "sus-tain-a-bil-i-ty", "Stumbling over the seven-syllable sequence.", "A field of modern white wind turbines turning gracefully on a green hill"),
        ("environmental", "Relating to the natural world and the impact of human activity upon it.", "Clean air environmental policies significantly reduced city smog.", "en-vy-ruhn-MEN-tuhl", "en-vi-ron-men-tal", "Saying 'en-vi-ro-men-tal' and dropping 'n'.", "A pristine panoramic vista of clear blue skies over mountains and clean rivers"),
        ("preservation", "The maintenance of pristine atmospheric and ecological quality.", "Global treaties supported the preservation of Earth's protective ozone layer.", "prez-er-VAY-shuhn", "pres-er-va-tion", "Saying 'press-er-va-tion' with hard 's'.", "A symbolic graphic of Earth surrounded by a glowing protective ozone shield"),
        ("biodiversity", "The variety of living organisms in an ecosystem or world.", "Conserving clean air protects the rich biodiversity of bird and insect species.", "by-oh-dy-VUR-si-tee", "bi-o-di-ver-si-ty", "Saying 'bee-o-di-ver-si-ty' with long 'e'.", "A colorful montage showing diverse migratory birds, butterflies, and eagles"),
        ("rehabilitation", "The action of restoring something to its former health or condition.", "Urban reforestation helped with the rehabilitation of local air quality.", "ree-huh-bil-i-TAY-shuhn", "re-ha-bil-i-ta-tion", "Skipping the 'bil' syllable.", "City volunteers planting green trees in a park under bright sunny skies"),
        ("photosynthesis", "The process by which plants use sunlight to synthesize nutrients.", "Forests perform photosynthesis to absorb carbon dioxide and release oxygen.", "foh-toh-SIN-thuh-sis", "pho-to-syn-the-sis", "Stumbling over the multisyllabic rhythm.", "An educational graphic showing sunlight and water turning into oxygen in leaves"),
        ("atmosphere", "The envelope of gases surrounding the earth or another planet.", "Earth's atmosphere creates the blue sky, clouds, and conditions for life.", "AT-muhs-feer", "at-mo-sphere", "Saying 'at-moce-feer' with wrong vowel.", "A breathtaking view of the glowing thin blue ribbon of Earth's atmosphere in space"),
    ],
    # L26: 8+ letter celestial exploration & spaceflights
    [
        ("interplanetary", "Situated or traveling between planets of the solar system.", "Interplanetary space probes beamed back high-resolution photos of Jupiter.", "in-ter-PLAN-i-tair-ee", "in-ter-plan-e-tar-y", "Skipping the 'e' syllable.", "A robotic spacecraft cruising past the swirling Great Red Spot of Jupiter"),
        ("stratosphere", "The atmospheric layer extending from roughly six to thirty miles up.", "Weather balloons expand to the size of a house in the thin stratosphere.", "STRAT-uh-sfeer", "strat-o-sphere", "Saying 'stray-to-sphere' with long 'a'.", "A glowing high-altitude balloon floating in the dark blue stratosphere"),
        ("astrophysics", "The branch of astronomy dealing with the physics of stars and cosmos.", "Theoretical astrophysics models the formation of stars, nebulae, and galaxies.", "as-troh-FIZ-iks", "as-tro-phys-ics", "Saying 'as-tro-fee-ziks' with long 'e'.", "A 3D simulation of a binary star system swirling and merging in deep space"),
        ("observatories", "Plural of observatory; research stations equipped with telescopes.", "Desert observatories documented the transit of Venus across the sun.", "uhb-ZUR-vuh-tor-eez", "ob-ser-va-to-ries", "Saying 'ob-zer-va-treez' with dropped syllable.", "Modern white astronomical telescope domes glowing under a starry night sky"),
        ("constellations", "Plural of constellation; recognized groupings of stars.", "Sailors identified celestial constellations like the Southern Cross to steer.", "kahn-stuh-LAY-shuhnz", "con-stel-la-tions", "Skipping the 'la' syllable.", "A star map showing the glowing Southern Cross constellation guiding a ship"),
        ("heliosphere", "The vast bubble of space dominated by the sun's solar wind.", "The sun's heliosphere protects all eight planets from interstellar cosmic rays.", "HEE-lee-uh-sfeer", "he-li-o-sphere", "Saying 'hel-ee-o-sphere' with short 'e'.", "An astronomical illustration showing the sun's bubble in interstellar space"),
        ("spectrometer", "An instrument used to analyze the wavelengths of light spectra.", "The orbiter's spectrometer analyzed the atmospheric composition of Venus.", "spek-TRAHM-i-ter", "spec-trom-e-ter", "Saying 'SPEC-tro-mee-ter' with wrong stress.", "A laboratory spectral analysis monitor displaying colored emission lines"),
    ],
    # L27: 8+ letter aerial harmony & sound
    [
        ("reverberation", "Prolongation of sound in high open mountain and cloud canyons.", "The clear trumpet tone produced a long, haunting reverberation in the clouds.", "ri-vur-buh-RAY-shuhn", "re-ver-ber-a-tion", "Skipping the 'ber' syllable.", "Soundwaves rippling through misty cloud canyons and reflecting back"),
        ("resonance", "The reinforcement or prolongation of sound by reflection.", "The deep resonance of the cloud chime bell echoed across the kingdom.", "REZ-uh-nuhns", "res-o-nance", "Saying 'ree-zo-nance' with long 'e'.", "A large brass bell hanging in a cloud tower vibrating with soundwaves"),
        ("harmonics", "Musical tones produced as components of an acoustic wave.", "Wind whistling through the wire rigging created pleasant musical harmonics.", "hahr-MAHN-iks", "har-mon-ics", "Saying 'har-mone-iks' with long 'o'.", "A musical staff showing harmonic overtones above a sky landscape"),
        ("sonorous", "Capable of producing a deep, resonant, or rich musical sound.", "The pipe organ in the cloud cathedral produced a sonorous, noble melody.", "SAHN-er-uhs", "son-o-rous", "Saying 'suh-nor-us' with wrong stress.", "A magnificent pipe organ with gleaming silver pipes rising toward arches"),
        ("vibrations", "Plural of vibration; rapid periodic motions producing sound.", "Gentle acoustic vibrations rippled across the calm surface of the cloud pool.", "vy-BRAY-shuhnz", "vi-bra-tions", "Saying 'vee-bra-tions' with long 'e'.", "An illustrated waveform showing acoustic sound vibrations in air"),
        ("serenity", "The state of being calm, peaceful, and untroubled.", "Drifting high above the world in a hot air balloon brings a deep serenity.", "suh-REN-i-tee", "se-ren-i-ty", "Saying 'see-ren-i-ty' with long 'e'.", "A peaceful hot air balloon floating above a sea of calm golden morning clouds"),
        ("tranquility", "The quality or state of being tranquil, calm, and peaceful.", "The Cloud Kingdom rested in an atmosphere of magical tranquility at dusk.", "trang-KWIL-i-tee", "tran-quil-i-ty", "Saying 'tran-kwil-ty' with dropped syllable.", "A serene floating palace reflected in a glassy cloud pool at sunset"),
    ],
    # L28: 8+ letter atmospheric wonders & triumphs
    [
        ("extraordinary", "Very unusual or remarkable; beyond what is ordinary.", "The view of the sun setting over a sea of clouds was extraordinary.", "ik-STROR-di-nair-ee", "ex-traor-di-nar-y", "Saying 'extra-ordinary' in six distinct syllables.", "A breathtaking vibrant sunset casting golden light across cloud mountain peaks"),
        ("magnificent", "Impressively beautiful, elaborate, or grand in scale.", "The magnificent Cloud Kingdom hovered like a crown above the world.", "mag-NIF-i-suhnt", "mag-nif-i-cent", "Saying 'mag-neef-i-cent' with wrong vowel.", "A magnificent palace of marble and crystal resting on glowing sunset clouds"),
        ("monumental", "Great in importance, extent, or size; majestic in scale.", "Building the high-altitude cloud research platform was a monumental feat.", "mahn-yuh-MEN-tuhl", "mon-u-men-tal", "Skipping the 'u' syllable.", "A futuristic floating research city station anchored high in the clouds"),
        ("spectacular", "Beautiful in a dramatic and eye-catching way.", "The emerald green aurora dancing above the clouds was a spectacular sight.", "spek-TAK-yuh-ler", "spec-tac-u-lar", "Saying 'spec-tak-lar' with dropped syllable.", "A dramatic view of glowing green aurora curtains reflecting on cloud tops"),
        ("masterpieces", "Plural of masterpiece; works of outstanding artistry and natural beauty.", "The cloud formations at golden hour are nature's ever-changing masterpieces.", "MAS-ter-pee-siz", "mas-ter-piec-es", "Saying 'mes-ter-piec-es' with short 'e'.", "A series of three photos showing dramatic sculptural sunset cloud formations"),
        ("resplendent", "Attractive and impressive through being richly colorful and bright.", "The evening sky was resplendent in shades of amber, violet, and gold.", "ri-SPLEN-duhnt", "re-splen-dent", "Saying 're-splan-dent' with short 'a'.", "A sky glowing resplendently with vibrant sunset colors across cloud layers"),
        ("flourishing", "Developing rapidly and successfully; thriving in beauty.", "A flourishing garden of alpine orchids bloomed in the cloud greenhouse.", "FLUR-ish-ing", "flour-ish-ing", "Saying 'floor-ish-ing' with wrong vowel.", "A lush glass greenhouse conservatory floating among clouds with blooming flowers"),
    ],
    # L29: 8+ letter aeronautical mastery & navigation
    [
        ("trailblazers", "Plural of trailblazer; pioneers who lead the way in aviation.", "The Wright brothers and early aviators were true trailblazers of the skies.", "TRAYL-blay-zerz", "trail-blaz-ers", "Saying 'trel-blazerz' with short 'e'.", "Pioneering early aviators standing proudly beside a vintage biplane"),
        ("circumnavigate", "To fly or sail all the way around the world.", "Pioneering pilots were the first to circumnavigate the globe in a single flight.", "sur-kuhm-NAV-i-gayt", "cir-cum-nav-i-gate", "Skipping the 'cum' syllable.", "A globe showing a red dotted flight route circumnavigating the planet"),
        ("mountaineers", "Plural of mountaineer; people who climb high peaks into the clouds.", "The mountaineers emerged above the cloud layer into brilliant sunshine.", "mown-tuh-NEERZ", "moun-tain-eers", "Saying 'mown-teh-neerz' with dropped syllable.", "Climbers standing atop a summit island looking down at a sea of clouds"),
        ("cartographers", "Plural of cartographer; scientists who draw maps and aeronautical charts.", "Aeronautical cartographers charted flight routes, jet streams, and air corridors.", "kahr-TAHG-ruh-ferz", "car-tog-ra-phers", "Saying 'car-to-gra-pherz' with wrong stress.", "Cartographers at drafting tables designing modern high-altitude airway charts"),
        ("expeditionary", "Belonging to an expedition, especially for atmospheric discovery.", "The expeditionary airship gathered weather data across the Arctic Circle.", "ek-spuh-DISH-uh-nair-ee", "ex-pe-di-tion-ar-y", "Skipping the 'ar' syllable.", "A scientific exploration airship moored at a snow-covered research base"),
        ("triangulation", "The measurement of a network of triangles for geographic survey.", "Airborne laser mapping used triangulation to model the topography below.", "try-ang-gyuh-LAY-shuhn", "tri-an-gu-la-tion", "Stumbling over the five-syllable sequence.", "An aerial survey aircraft scanning the ground below with triangular laser beams"),
        ("stratosphere", "The layer of the earth's atmosphere above the troposphere.", "The spy plane cruised safely above the weather in the quiet stratosphere.", "STRAT-uh-sfeer", "strat-o-sphere", "Saying 'stray-to-sphere' with long 'a'.", "A high-altitude aircraft cruising in the dark navy blue stratosphere"),
    ],
    # L30: 8+ letter Cloud Kingdom triumph & mastery
    [
        ("triumphant", "Having won a victory; joyful, proud, and celebratory.", "The triumphant pilots celebrated a flawless round-the-world flight.", "try-UHM-fuhnt", "tri-um-phant", "Saying 'tree-um-phant' with long 'e'.", "Cheering pilots and engineers celebrating beside a futuristic airplane"),
        ("accomplishment", "Something achieved successfully through dedication and skill.", "Conquering the Cloud Kingdom was an extraordinary accomplishment.", "uh-KAHM-plish-muhnt", "ac-com-plish-ment", "Saying 'ac-cum-plish-ment' with short 'u'.", "A smiling student holding up a golden aeronautical wings achievement medal"),
        ("unshakeable", "Unable to be weakened or swayed; resolute and steadfast.", "Her unshakeable focus guided the airplane safely through the storm clouds.", "uhn-SHAY-kuh-buhl", "un-shake-a-ble", "Saying 'un-shak-a-ble' with short 'a'.", "A confident pilot with steady hands on the control yoke flying into sunshine"),
        ("invincible", "Too powerful to be defeated or overcome; resilient and strong.", "Soaring high above the clouds, the adventurers felt brave and invincible.", "in-VIN-suh-buhl", "in-vin-ci-ble", "Saying 'in-veen-ci-ble' with long 'e'.", "Two young adventurers with flying goggles looking out over golden cloud banks"),
        ("championship", "The status or title of a champion; supreme victory.", "They won the golden trophy in the international air racing championship.", "CHAM-pee-uhn-ship", "cham-pi-on-ship", "Saying 'chem-py-on-ship' with short 'e'.", "A gleaming golden trophy cup with wings standing tall in front of airplanes"),
        ("pronunciation", "The correct way in which words and phonemes are spoken clearly.", "Clear pronunciation allowed the flight crew to communicate perfectly.", "pruh-nuhn-see-AY-shuhn", "pro-nun-ci-a-tion", "Saying 'pro-nown-ci-a-tion' with 'noun'.", "A glowing soundwave symbol radiating crystal-clear sound energy in the sky"),
        ("masterpiece", "An outstanding work of artistry, skill, or natural perfection.", "The sunlit Cloud Kingdom shone as a breathtaking atmospheric masterpiece.", "MAS-ter-pees", "mas-ter-piece", "Saying 'mes-ter-piece' with short 'e'.", "A stunning panoramic aerial photo of glowing golden clouds and floating castles"),
    ],
]
