"""World 3: Echo Mountain (Levels 1 to 30, 210 unique words)."""
from __future__ import annotations

# Format: (text, meaning, sentence, hint, syllables, mistake, alt)
WORLD_3_LEVELS = [
    # L1: 4-5 letter mountain foundation
    [
        ("peak", "The pointed top of a mountain or ridge.", "Snow crowned the highest rocky peak of the mountain range.", "PEEK", "peak", "Saying 'pick' with short 'i'.", "A snow-covered sharp mountain peak piercing white clouds"),
        ("cliff", "A steep, high rock face or precipice beside a drop.", "Eagles nested on the high ledge of the granite cliff.", "KLIF", "cliff", "Saying 'cleef' with long 'e'.", "A sheer vertical grey granite cliff face overlooking a valley"),
        ("ridge", "A long, narrow hilltop, mountain range, or watershed.", "Hikers walked single file along the scenic mountain ridge.", "RIJ", "ridge", "Saying 'reedj' with long 'e'.", "A narrow rocky mountain ridge trail with panoramic drop-offs on both sides"),
        ("slope", "A surface of which one end or side is higher than the other.", "Skiiers glided down the gentle snowy mountain slope.", "SLOHP", "slope", "Saying 'slap' with short 'a'.", "A wide snow-covered mountain slope curving down to pine trees"),
        ("crag", "A steep or rugged cliff or rock face in mountains.", "Mountain goats bounded effortlessly across the rocky crag.", "KRAG", "crag", "Saying 'kreg' with short 'e'.", "Rugged sharp jagged rock crags jutting out from a mountainside"),
        ("echo", "A sound caused by the reflection of sound waves from a surface.", "His joyful shout produced a crystal clear echo across the canyon.", "EK-oh", "ech-o", "Saying 'ee-choh' with 'ch' sound.", "Soundwaves rippling and reflecting between two steep canyon walls"),
        ("cave", "A natural underground chamber in a hillside or cliff.", "Hikers sought shelter from the storm inside the dry mountain cave.", "KAYV", "cave", "Saying 'kav' with short 'a'.", "A dark arched entrance of a stone mountain cave framed by rocks"),
    ],
    # L2: 5-letter mountain minerals & terrain
    [
        ("flint", "A hard grey rock that produces a spark when struck with steel.", "Early explorers used a piece of flint to light their campfire.", "FLINT", "flint", "Saying 'fleent' with long 'e'.", "A sharp piece of grey flint stone sparking near tinder"),
        ("slate", "A fine-grained grey or greenish rock that splits into thin plates.", "The cottage roof was tiled with durable dark grey slate.", "SLAYT", "slate", "Saying 'slet' with short 'e'.", "Smooth flat tiles of dark grey slate stone stacked neatly"),
        ("ledge", "A narrow horizontal surface projecting from a mountain wall.", "A family of mountain bighorn sheep rested on the rocky ledge.", "LEJ", "ledge", "Saying 'ledj-ee' with extra vowel.", "A narrow flat stone ledge on the side of a tall mountain cliff"),
        ("gorge", "A narrow valley between hills or mountains, typically with a stream.", "A suspension footbridge spanned high across the deep river gorge.", "GORJ", "gorge", "Saying 'gor-jee' or 'garg'.", "A deep rocky canyon gorge with a rushing turquoise river below"),
        ("bluff", "A steep cliff, bank, or headland with a broad face.", "The scenic wooden lookout perched on top of the limestone bluff.", "BLUHF", "bluff", "Saying 'bloof' with long 'oo'.", "A high rounded limestone bluff overlooking a vast winding river"),
        ("chasm", "A deep fissure in the earth, rock, or other surface.", "A fallen cedar trunk bridged the narrow gap across the dark chasm.", "KAZ-uhm", "chasm", "Saying 'chaz-um' with 'ch' sound.", "A deep dark crack chasm splitting a massive granite rock face"),
        ("crest", "The top of a mountain, hill, or wave.", "Hikers cheered triumphantly as they reached the mountain crest.", "KREST", "crest", "Saying 'krist' with short 'i'.", "The highest curved summit crest of a green alpine mountain"),
    ],
    # L3: 5-letter alpine wildlife & weather
    [
        ("eagle", "A large bird of prey with a massive hooked bill and broad wings.", "The golden eagle circled effortlessly in the high thermal winds.", "EE-guhl", "ea-gle", "Saying 'egg-uhl' with short 'e'.", "A majestic golden eagle soaring with outstretched wings over peaks"),
        ("llama", "A domesticated South American camelid used as a pack animal.", "The friendly llama carried camping gear along the Andean mountain trail.", "LAH-muh", "lla-ma", "Saying 'lay-ma' with long 'a'.", "A woolly white and brown llama standing against a backdrop of snowy peaks"),
        ("cougar", "A large wild cat with a plain tawny coat found in mountains.", "The agile cougar leaped gracefully between the rocky boulders.", "KOO-ger", "cou-gar", "Saying 'cow-gar' with 'ow' sound.", "A sleek tawny cougar wildcat walking along a mountain ridge"),
        ("condor", "A very large South American or Californian vulture.", "The Andean condor has one of the largest wingspans of any bird.", "KAHN-dor", "con-dor", "Saying 'con-dour' with wrong stress.", "A giant black Andean condor soaring high above rocky mountain peaks"),
        ("alpine", "Relating to high mountains, especially above the tree line.", "Delicate purple alpine wildflowers grew among the rocky gravel.", "AL-pyn", "al-pine", "Saying 'al-peen' with long 'e'.", "A meadow of colorful blooming alpine flowers beneath a jagged peak"),
        ("chilly", "Unpleasantly cold; marked by cold air in high elevations.", "The chilly mountain air made everyone zip up their fleece jackets.", "CHIL-ee", "chil-ly", "Saying 'shil-ee' with 'sh'.", "A hiker in a warm knitted cap breathing visible mist in chilly air"),
        ("frost", "A deposit of small white ice crystals formed on ground.", "Sparkling morning frost coated the needles of the dwarf pines.", "FRAWST", "frost", "Saying 'fruhst' with short 'u'.", "White crystalline ice frost coating the surface of mountain rocks"),
    ],
    # L4: 6-letter mountain landforms & geology
    [
        ("summit", "The highest point of a mountain or hill.", "After hours of climbing, they proudly stood on the summit.", "SUHM-it", "sum-mit", "Saying 'soo-mit' with long 'oo'.", "Two hikers standing victoriously on a snowy mountain summit holding flags"),
        ("valley", "A low area of land between hills or mountains, often with a river.", "A peaceful green valley spread out beneath the towering cliffs.", "VAL-ee", "val-ley", "Saying 'vahl-lay' with wrong ending.", "A lush green mountain valley with a winding silver river running through"),
        ("canyon", "A deep gorge, typically one with a river flowing through it.", "Red sandstone walls rose steeply on both sides of the canyon.", "KAN-yuhn", "can-yon", "Saying 'can-on' and dropping 'y'.", "A dramatic red rock canyon carved deep into the earth by a river"),
        ("ravine", "A deep, narrow gorge with steep sides.", "Water rushed noisily along the bottom of the rocky mountain ravine.", "ruh-VEEN", "ra-vine", "Saying 'ray-veen' with long 'a'.", "A narrow rocky mountain ravine with pine trees clinging to the slopes"),
        ("scree", "A mass of small loose stones that covers a mountain slope.", "Careful footsteps were needed when crossing the loose gravel scree.", "SKREE", "scree", "Saying 'skree-ee' with two syllables.", "A steep mountainside covered in loose grey slate and gravel scree"),
        ("plateau", "An area of relatively level high ground.", "Vast grasslands stretched across the high mountain plateau.", "pla-TOH", "pla-teau", "Saying 'play-too' with long 'oo'.", "A flat-topped high elevation mountain plateau under a blue sky"),
        ("boulder", "A large rock, typically one that has been worn smooth by erosion.", "A massive granite boulder rested beside the winding trail.", "BOHL-der", "boul-der", "Saying 'bow-el-der' with extra syllable.", "A huge rounded grey granite boulder resting in a mountain meadow"),
    ],
    # L5: 6-letter mountain rocks & minerals
    [
        ("granite", "A very hard, granular, crystalline igneous rock.", "The sheer mountain face was composed of solid grey granite.", "GRAN-it", "gran-ite", "Saying 'gran-yt' with long 'i'.", "A polished slab of speckled grey and white natural granite stone"),
        ("basalt", "A dark, fine-grained volcanic rock forming columns.", "Hexagonal basalt columns formed a natural staircase up the cliff.", "buh-SAWLT", "ba-salt", "Saying 'bay-salt' with long 'a'.", "Geometric vertical hexagonal black volcanic basalt rock columns"),
        ("quartz", "A hard mineral consisting of silica, found in colorless crystals.", "Veins of white and rose quartz sparkled inside the cave wall.", "KWORTS", "quartz", "Saying 'kwarz' with 'z' sound.", "A cluster of translucent hexagonal quartz crystals glowing in light"),
        ("marble", "A hard crystalline metamorphic form of limestone.", "The monument was carved from smooth white Italian marble.", "MAHR-buhl", "mar-ble", "Saying 'mar-buhl' with dropped 'r'.", "A polished white marble slab with elegant natural grey veining"),
        ("gravel", "A loose aggregation of small water-worn or pounded stones.", "Their boots crunched steadily along the dry gravel pathway.", "GRAV-uhl", "grav-el", "Saying 'gray-vuhl' with long 'a'.", "A path of clean rounded small grey and tan river gravel stones"),
        ("pebble", "A small stone made smooth and round by the action of water.", "She skipped a flat round pebble across the calm alpine lake.", "PEB-uhl", "peb-ble", "Saying 'peeb-uhl' with long 'e'.", "Smooth colorful flat river pebbles resting in crystal clear water"),
        ("fossil", "The remains or impression of a prehistoric organism preserved in petrified form.", "He discovered a fossilized seashell embedded in the limestone rock.", "FAHS-uhl", "fos-sil", "Saying 'foh-sil' with long 'o'.", "A spiral ammonite shell fossil clearly preserved in a tan stone matrix"),
    ],
    # L6: 6-letter climbing & hiking equipment
    [
        ("harness", "A set of straps by which a person is safely fastened to a rope.", "The rock climber double-checked the buckles on her climbing harness.", "HAHR-nis", "har-ness", "Saying 'har-nass' with short 'a'.", "A safety climbing harness with carabiners and loops on a table"),
        ("helmet", "A hard or padded protective hat worn to protect the head.", "He strapped on his safety climbing helmet before scaling the wall.", "HEL-mit", "hel-met", "Saying 'hel-mat' with overstressed ending.", "A lightweight white mountaineering helmet with a headlamp mount"),
        ("cables", "Plural of cable; thick strong ropes of wire used for safety lines.", "Steel cables secured the via ferrata route along the cliff edge.", "KAY-buhlz", "ca-bles", "Saying 'cab-uhlz' with short 'a'.", "Braided steel climbing cables anchored into a solid granite rock wall"),
        ("pulley", "A wheel with a grooved rim around which a cord passes.", "The rescue team used a mechanical pulley system to hoist the pack.", "PUL-ee", "pul-ley", "Saying 'pool-ee' with long 'oo'.", "A metal climbing pulley with a brightly colored rope running through"),
        ("anchor", "A device used to connect a climbing rope securely to a rock face.", "The lead climber set a solid titanium anchor into the crack.", "ANG-ker", "an-chor", "Saying 'an-chore' with 'ch' sound.", "A heavy-duty climbing bolt and anchor hanger fixed into rock"),
        ("boots", "Sturdy footwear extending above the ankle for mountain hiking.", "Waterproof leather boots protected his feet across the rocky scree.", "BOOTS", "boots", "Saying 'buts' with short 'u'.", "A pair of sturdy waterproof leather mountain hiking boots on rocks"),
        ("jacket", "An outer garment extending either to the waist or hips.", "Her bright orange down jacket kept her warm in freezing winds.", "JAK-it", "jack-et", "Saying 'jack-at' with overstressed ending.", "A bright orange insulated mountaineering down jacket with a hood"),
    ],
    # L7: 6-letter mountain weather & water
    [
        ("glacier", "A slowly moving mass or river of ice formed by the accumulation of snow.", "The massive blue glacier carved a deep U-shaped valley over centuries.", "GLAY-sher", "gla-cier", "Saying 'gla-see-er' with three syllables.", "A massive glowing blue ice glacier flowing between two jagged peaks"),
        ("crevasse", "A deep open crack, especially in a glacier.", "Climbers carefully crossed the deep icy crevasse using a ladder.", "kri-VAS", "cre-vasse", "Saying 'cree-vass' with wrong stress.", "A deep turquoise blue ice crevasse in the surface of a glacier"),
        ("frozen", "Turned into or covered with ice as a result of extreme cold.", "The high mountain lake remained frozen solid throughout the spring.", "FROH-zuhn", "fro-zen", "Saying 'fraw-zen' with short 'o'.", "A pristine mountain lake with a smooth sheet of crystal clear ice"),
        ("icicle", "A hanging, tapering piece of ice formed by the freezing of dripping water.", "Glittering icicles hung from the rocky roof of the mountain cave.", "EYE-si-kuhl", "i-ci-cle", "Saying 'eye-sick-uhl' with wrong middle vowel.", "Crystal clear pointed icicles hanging from a rocky cliff overhang"),
        ("blizzard", "A severe snowstorm with high winds and low visibility.", "The expedition waited inside their sturdy tent during the raging blizzard.", "BLIZ-erd", "bliz-zard", "Saying 'bleez-zard' with long 'e'.", "Swirling white snow and fierce howling winds in a mountain blizzard"),
        ("thunder", "A loud rumbling noise heard after a lightning flash.", "Deep mountain thunder rumbled dramatically across the rocky peaks.", "THUHN-der", "thun-der", "Saying 'ton-der' and dropping 'th'.", "Dark dramatic storm clouds over mountain peaks with lightning flashes"),
        ("gusts", "Sudden strong rushes of wind.", "Powerful mountain wind gusts whipped across the exposed ridge.", "GUHSTS", "gusts", "Saying 'gosts' with long 'o'.", "High mountain ridge grass and shrubs bending sharply in fierce wind gusts"),
    ],
    # L8: 6-letter high-altitude wildlife
    [
        ("ibex", "A wild mountain goat with long, thick ridged curved horns.", "The nimble Alpine ibex balanced on a steep, almost vertical dam wall.", "EYE-beks", "i-bex", "Saying 'ee-bex' with long 'e'.", "An Alpine ibex with magnificent long curved horns standing on a rock"),
        ("chamois", "A goat-antelope with short hooked horns inhabiting high mountains.", "A graceful chamois bounded across the snowy mountain crags.", "SHAM-wah", "cham-ois", "Saying 'chay-moys' with 'ch' sound.", "A nimble brown chamois goat-antelope leaping across rocky terrain"),
        ("marmot", "A heavily built, gregarious, burrowing rodent of the squirrel family.", "An alpine marmot whistled a loud warning from atop its boulder.", "MAHR-muht", "mar-mot", "Saying 'mar-mote' with long 'o'.", "A chubby brown alpine marmot sitting upright on a sunny granite rock"),
        ("vulture", "A large bird of prey that feeds predominantly on carrion.", "A bearded vulture with a nine-foot wingspan glided above the gorge.", "VUL-cher", "vul-ture", "Saying 'vul-toor' with unnatural ending.", "A majestic bearded vulture bird soaring close to a mountain cliff face"),
        ("ermine", "A short-tailed weasel whose coat turns completely white in winter.", "The quick ermine blended perfectly against the deep mountain snow.", "UR-min", "er-mine", "Saying 'er-myn' with long 'i'.", "A cute pure white winter ermine with black tail tip peeking from snow"),
        ("pika", "A small mammal related to rabbits that lives on rocky scree.", "The tiny alpine pika carried dried grasses to its winter rock cache.", "PY-kuh", "pi-ka", "Saying 'peek-uh' with long 'e'.", "A small round furry mountain pika holding a flower stem in its mouth"),
        ("falcon", "A bird of prey with long pointed wings and swift flight.", "The falcon soared high above the jagged mountain spires.", "FAL-kuhn", "fal-con", "Pronouncing the silent 'l'.", "A peregrine falcon perched high on a rocky crag overlooking a valley"),
    ],
    # L9: 6-letter mountain travel & shelter
    [
        ("trails", "Plural of trail; marked paths through rough country.", "Scenic hiking trails wound through the evergreen alpine slopes.", "TRAYLZ", "trails", "Saying 'chrails' with 'ch' sound.", "A well-marked dirt hiking trail winding up toward snowy peaks"),
        ("cairn", "A mound of rough stones built as a memorial or landmark on a hilltop.", "A stone cairn marked the safe route through the dense fog.", "KAIRN", "cairn", "Saying 'karn' with flat 'a'.", "A pyramid stack of stones cairn marking a hiking path on a ridge"),
        ("chalet", "A wooden house with a sloping roof and overhangs, common in the Alps.", "Smoke drifted cozily from the chimney of the Swiss mountain chalet.", "sha-LAY", "cha-let", "Saying 'chay-let' with hard 'ch' and 't'.", "A picturesque wooden Swiss alpine chalet surrounded by wildflowers"),
        ("refuge", "A place providing shelter or protection from danger or weather.", "The stone mountain refuge provided warm soup for tired climbers.", "REF-yooj", "ref-uge", "Saying 'reh-fyoodj' with wrong stress.", "A cozy stone mountain mountain refuge hut nestled beneath a peak"),
        ("passes", "Plural of pass; navigable routes through mountain ranges.", "Ancient trade caravans traveled through the high rocky mountain passes.", "PAS-iz", "pass-es", "Saying 'pahs-iz' with wrong vowel.", "A high elevation mountain road pass curving between two towering peaks"),
        ("tunnels", "Plural of tunnel; underground passages dug through hills.", "The railway train traveled through illuminated mountain tunnels.", "TUHN-uhlz", "tun-nels", "Saying 'toon-nels' with long 'oo'.", "An arched stone railway tunnel opening in the side of a mountain"),
        ("timber", "Wood prepared for use in building mountain lodges.", "Heavy beams of spruce timber framed the ceiling of the lodge.", "TIM-ber", "tim-ber", "Saying 'teem-ber' with long 'e'.", "Massive peeled log timbers supporting the roof of a mountain lodge"),
    ],
    # L10: 6-letter mountain actions & descriptors
    [
        ("ascent", "A climb or walk to the summit of a mountain or hill.", "They began their steep ascent before the first rays of dawn.", "uh-SENT", "as-cent", "Saying 'ay-scent' with long 'a'.", "A line of climbers roped together ascending a steep snowy ridge"),
        ("rugged", "Having a broken, rocky, and uneven surface.", "The rugged terrain challenged even the most experienced mountaineers.", "RUHG-id", "rug-ged", "Saying 'ruugd' in one syllable.", "A rugged landscape of jagged granite spires and steep canyons"),
        ("steep", "Rising or falling sharply; nearly perpendicular.", "The steep incline required climbers to use their hands for balance.", "STEEP", "steep", "Saying 'step' with short 'e'.", "A steep mountain slope rising dramatically toward a blue sky"),
        ("echoes", "Plural of echo; sounds repeated by reflection.", "Joyful shouts created long-lasting echoes across the deep canyon.", "EK-ohz", "ech-oes", "Saying 'ee-chohz' with 'ch' sound.", "Concentric rings depicting sound echoes bouncing between mountain walls"),
        ("frozen", "Hardened or turned into ice by cold temperatures.", "A frozen waterfall formed giant crystalline pillars against the cliff.", "FROH-zuhn", "fro-zen", "Saying 'fraw-zen' with short 'o'.", "A massive frozen blue ice waterfall clinging to a vertical cliff face"),
        ("alpine", "Characteristic of high mountain pastures and peaks.", "An alpine meadow bloomed with vibrant yellow arnica flowers.", "AL-pyn", "al-pine", "Saying 'al-peen' with long 'e'.", "A high alpine valley with crystal streams and blooming wildflowers"),
        ("summit", "The highest point attainable on a mountain peak.", "A metal compass rose marker stood atop the rocky summit.", "SUHM-it", "sum-mit", "Saying 'soo-mit' with long 'oo'.", "A panoramic 360-degree view of mountain ranges from a rocky summit"),
    ],
    # L11: 7-letter alpine geology & rock structures
    [
        ("granite", "A hard igneous rock consisting of quartz, mica, and feldspar.", "Climbers loved the excellent friction of the solid granite rock face.", "GRAN-it", "gran-ite", "Saying 'gran-yt' with long 'i'.", "A close-up of textured grey, black, and white speckled granite rock"),
        ("mineral", "A solid inorganic substance of natural occurrence.", "The rocky cave contained specimens of gold, quartz, and copper mineral.", "MIN-er-uhl", "min-er-al", "Saying 'mee-ner-al' with long 'e'.", "A colorful collection of raw mineral crystals in display boxes"),
        ("boulder", "A massive rock rounded by the action of water or weather.", "A giant boulder balanced precariously on the edge of the precipice.", "BOHL-der", "boul-der", "Saying 'bow-el-der' with extra syllable.", "A colossal round moss-covered boulder resting in a mountain stream"),
        ("bedrock", "Solid rock underlying loose deposits such as soil or gravel.", "The foundation of the mountain lodge was anchored directly into bedrock.", "BED-rahk", "bed-rock", "Saying 'bad-rock' with short 'a'.", "Solid exposed grey bedrock layers beneath thin alpine soil"),
        ("geology", "The science that deals with the earth's physical structure.", "She studied the geology of volcanic rock formations in the park.", "jee-AHL-uh-jee", "ge-ol-o-gy", "Saying 'jee-oh-lo-gy' with wrong stress.", "A geologist with a rock hammer examining layered rock strata on a cliff"),
        ("outcrop", "A rock formation that is visible on the surface of the ground.", "A jagged limestone outcrop jutted dramatically above the pine trees.", "OWT-krahp", "out-crop", "Saying 'out-crap' with wrong vowel.", "A dramatic rocky limestone outcrop rising high above a forest hillside"),
        ("terrace", "A level paved or grassy area next to a building or hillside.", "Farmers cultivated barley on ancient stepped mountain terraces.", "TAIR-is", "ter-race", "Saying 'ter-rays' with long 'a'.", "Stepped green agricultural terraces carved into a steep mountainside"),
    ],
    # L12: 7-letter high-altitude weather & atmosphere
    [
        ("altitude", "The height of an object or point in relation to sea level.", "At high altitude, the air is crisp, cool, and thin.", "AL-ti-tood", "al-ti-tude", "Saying 'al-tee-tood' with wrong vowels.", "An altimeter watch showing high elevation in front of snowy peaks"),
        ("climates", "Plural of climate; prevailing weather conditions of areas.", "Mountain climates change rapidly as you ascend through elevation zones.", "KLY-mits", "cli-mates", "Saying 'kly-mayts' with long 'a'.", "An illustrated chart showing elevation climate zones from forest to snow"),
        ("tempest", "A violent windy storm accompanied by rain or snow.", "The mountain tempest howled fiercely against the cabin shutters.", "TEM-pist", "tem-pest", "Saying 'tem-past' with overstressed ending.", "A dark and dramatic swirling storm tempest over jagged mountain peaks"),
        ("thunder", "A loud rumbling or crashing noise heard after lightning.", "Loud thunder echoed across the mountain peaks during the storm.", "THUHN-der", "thun-der", "Dropping the 'th' sound.", "A streak of bright blue lightning illuminating a stormy mountain ridge"),
        ("horizon", "The line at which the earth's surface and the sky appear to meet.", "The setting sun painted the distant mountain horizon with purple light.", "huh-RY-zuhn", "ho-ri-zon", "Saying 'HOR-i-zon' with wrong stress.", "A wide panoramic horizon showing layers of mountain silhouettes at sunset"),
        ("overlook", "A commanding view from an elevated position.", "We paused at the scenic overlook to photograph the sprawling valley.", "OH-ver-luk", "o-ver-look", "Saying 'oh-ver-luke' with long 'oo'.", "A wooden observation deck overlook offering views of mountain ranges"),
        ("peaktop", "The topmost point or crest of a mountain peak.", "A flock of alpine choughs circled above the rocky peaktop.", "PEEK-tahp", "peak-top", "Saying 'pick-tap' with short 'i'.", "The highest rocky tip peaktop of a mountain under a crystal blue sky"),
    ],
    # L13: 7-letter mountaineering & climbing terms
    [
        ("climbing", "The sport or activity of scaling rock faces or mountains.", "Rock climbing requires strength, balance, concentration, and courage.", "KLY-ming", "climb-ing", "Pronouncing the silent 'b'.", "A climber in gear scaling a vertical granite rock wall using handholds"),
        ("trekking", "The activity of going on long arduous journeys on foot.", "They spent two weeks trekking through the breathtaking Himalayas.", "TREK-ing", "trek-king", "Saying 'chrek-ing' with 'ch' sound.", "A group of backpackers with trekking poles hiking on a mountain trail"),
        ("traverse", "To travel across or pass over a slope or ridge.", "Climbers had to traverse a narrow ice ledge to reach the col.", "truh-VURS", "tra-verse", "Saying 'TRA-verse' with wrong stress.", "A climber carefully traversing horizontally across a sheer rock face"),
        ("foothold", "A secure place where one can place one's foot safely.", "She found a small, sturdy foothold in the crack of the granite wall.", "FUT-hohld", "foot-hold", "Saying 'fut-hold' as 'food-hold'.", "A climbing shoe balanced securely on a small rocky granite foothold"),
        ("handhold", "A place to hold on with the hands in climbing.", "The climber gripped a deep handhold in the rock to pull herself up.", "HAND-hohld", "hand-hold", "Dropping the 'nd' in hand.", "Chalked hands firmly gripping a secure rock handhold on a climbing wall"),
        ("descent", "An action of moving downwards, especially down a mountain.", "The careful descent took three hours of navigating rocky switchbacks.", "di-SENT", "de-scent", "Saying 'DEE-scent' with wrong stress.", "Hikers carefully descending a zigzagging switchback trail down a slope"),
        ("belayer", "A person who controls the safety rope for a climber.", "The attentive belayer kept the rope taut as the climber ascended.", "bi-LAY-er", "be-lay-er", "Saying 'bee-ly-er' with long 'i'.", "A climbing partner on the ground belaying a rope through a safety device"),
    ],
    # L14: 7-letter mountain ecology & wildlife
    [
        ("wildness", "The quality or state of being wild, untamed, and natural.", "The raw wildness of the jagged peaks filled them with wonder.", "WYLD-nis", "wild-ness", "Saying 'willd-ness' with short 'i'.", "A dramatic untamed alpine landscape of glaciers, rocks, and peaks"),
        ("highland", "An area of high or mountainous land.", "Heather bloomed purple across the rolling Scottish highland slopes.", "HY-luhnd", "high-land", "Saying 'high-land' with overstressed ending.", "Rolling green highland hills with misty glens and grazing sheep"),
        ("steepness", "The quality of rising or falling sharply with a high gradient.", "The extreme steepness of the cliff required specialized climbing ropes.", "STEEP-nis", "steep-ness", "Saying 'step-ness' with short 'e'.", "Looking down the sheer vertical steepness of a mountain precipice"),
        ("footpath", "A path for people to walk along, especially in the countryside.", "A peaceful footpath bordered by alpine meadows led up to the pass.", "FUT-path", "foot-path", "Saying 'food-path' or dropping 'th'.", "A stone footpath winding through alpine wildflower meadows"),
        ("explorer", "A person who explores an unfamiliar area for discovery.", "The brave explorer mapped uncharted mountain passes and rivers.", "ik-SPLOR-er", "ex-plor-er", "Saying 'ex-plur-er' with wrong vowel.", "An explorer with a backpack and map looking out over a mountain valley"),
        ("passages", "Plural of passage; narrow ways allowing access between places.", "Underground passages wound deep through the limestone cavern system.", "PAS-i-jiz", "pas-sag-es", "Saying 'pass-ay-jez' with wrong ending.", "Illuminated underground stone cave passages winding through rock"),
        ("cascades", "Plural of cascade; small waterfalls, typically in a series.", "Melting snow fed crystal cascades tumbling over granite terraces.", "kas-KAYDZ", "cas-cades", "Saying 'cas-cah-dez' with wrong vowels.", "A series of cascading clear water waterfalls tumbling over stone steps"),
    ],
    # L15: 7-letter cave & subterranean features
    [
        ("caverns", "Plural of cavern; large underground caves or chambers.", "Ancient mineral crystals glowed in the depths of the underground caverns.", "KAV-ernz", "cav-erns", "Saying 'kay-verns' with long 'a'.", "A vast subterranean limestone cavern with stalactites and still water"),
        ("crystals", "Plural of crystal; clear, transparent mineral formations.", "Giant gypsum crystals grew inside the magnificent mountain cavern.", "KRIS-tuhlz", "crys-tals", "Saying 'kris-tayls' with wrong ending.", "A cluster of translucent purple amethyst and clear quartz crystals"),
        ("stalagm", "A short term for stalagmite; a rising cave mineral formation.", "A stone stalagmite rose steadily from the floor of the damp cave.", "STAL-uhg-myt", "sta-lag-mite", "Saying 'stay-lag-mite' with long 'a'.", "A mineral stalagmite pillar rising upward from the stone floor of a cave"),
        ("stalact", "A short term for stalactite; a hanging cave mineral icicle.", "Water dripped from a pointed stalactite hanging from the cave ceiling.", "stuh-LAK-tyt", "sta-lac-tite", "Saying 'stay-lack-tite' with long 'a'.", "A sharp mineral stalactite hanging downward from the ceiling of a cave"),
        ("echoing", "Resounding or repeating with sound waves reflecting from walls.", "Their footsteps created echoing sounds in the vast cavern chamber.", "EK-oh-ing", "ech-o-ing", "Saying 'ee-cho-ing' with 'ch' sound.", "Concentric sound waves echoing inside a majestic stone cavern"),
        ("fissure", "A long, narrow opening or line of breakage made by cracking rock.", "Steam rose from a deep geothermal fissure in the volcanic rock.", "FISH-er", "fis-sure", "Saying 'fiss-yure' with hard 's'.", "A deep narrow crack fissure in volcanic rock with light shining through"),
        ("grotto", "A small picturesque cave, especially an artificial one in a garden.", "A hidden grotto behind the waterfall contained glowing blue water.", "GRAHT-oh", "grot-to", "Saying 'groh-toh' with long 'o'.", "A magical blue water grotto cave illuminated by sunlight through water"),
    ],
    # L16: 8+ letter mountain geography & terminology
    [
        ("mountain", "A large natural elevation of the earth's surface rising abruptly.", "The snow-capped mountain rose majestic and tall above the green valley.", "MOWN-tuhn", "moun-tain", "Saying 'mown-tayn' with long 'a'.", "A breathtaking snow-capped mountain peak rising above a pine forest"),
        ("elevation", "Height above a given level, especially sea level.", "At an elevation of ten thousand feet, the alpine air felt delightfully crisp.", "el-uh-VAY-shuhn", "el-e-va-tion", "Skipping the middle 'e' syllable.", "A mountain peak sign showing high elevation above sea level in meters"),
        ("topography", "The arrangement of the natural and artificial physical features of an area.", "The rugged topography of the region made road construction difficult.", "tuh-PAHG-ruh-fee", "to-pog-ra-phy", "Saying 'to-poh-gra-phy' with wrong stress.", "A 3D topographical contour map showing mountains, valleys, and rivers"),
        ("promontory", "A point of high land that juts out into a large body of water or valley.", "A medieval watchtower stood atop the rocky promontory.", "PRAHM-uhn-tor-ee", "prom-on-to-ry", "Saying 'pro-mon-try' with dropped syllable.", "A high rocky promontory headland extending out over a vast misty valley"),
        ("precipice", "A very steep rock face or cliff, typically a tall one.", "They peered cautiously over the edge of the towering stone precipice.", "PRES-uh-pis", "prec-i-pice", "Saying 'pree-ci-pice' with long 'e'.", "A dramatic vertical stone precipice dropping sheer into a misty gorge"),
        ("continental", "Forming or belonging to a continent or large landmass.", "The Continental Divide separates river systems flowing to different oceans.", "kahn-tuh-NEN-tuhl", "con-ti-nen-tal", "Skipping the 'ti' syllable.", "A wooden sign marking the high mountain Continental Divide pass"),
        ("escarpment", "A long, steep slope, especially one at the edge of a plateau.", "The limestone escarpment ran for fifty miles across the northern ridge.", "i-SKAHRP-muhnt", "es-carp-ment", "Saying 'es-karp-e-ment' with extra syllable.", "A towering continuous wall-like cliff escarpment spanning across a horizon"),
    ],
    # L17: 8+ letter alpine weather & glacial terms
    [
        ("avalanche", "A mass of snow, ice, and rocks falling rapidly down a mountainside.", "Safety patrols used controlled charges to prevent a winter avalanche.", "AV-uh-lanch", "av-a-lanche", "Saying 'av-uh-lansh' with 'sh' vs 'ch'.", "A dramatic plume of powdery white snow cascading down a mountain face"),
        ("moraine", "A mass of rocks and sediment carried down and deposited by a glacier.", "The terminal moraine formed a natural dam holding back the glacial lake.", "muh-RAYN", "mo-raine", "Saying 'mor-ayn' with wrong stress.", "A ridge of rocky debris and boulders moraine at the edge of a glacier"),
        ("icefield", "A wide flat expanse of floating or terrestrial ice.", "The expansive Columbia icefield stretched across the high mountain plateau.", "EYS-feeld", "ice-field", "Saying 'ice-feld' with short 'e'.", "A vast pristine expanse of blue-white icefield under a sunny blue sky"),
        ("snowstorm", "A heavy fall of snow, especially with a high wind.", "A sudden mountain snowstorm covered the trail in fresh powder.", "SNOH-storm", "snow-storm", "Saying 'snout-storm' with wrong vowel.", "Snowflakes swirling through evergreen pine trees in a mountain storm"),
        ("snowcapped", "Having snow on top; covered at the summit with snow.", "The snowcapped peaks glowed pink and gold in the morning sunrise.", "SNOH-kapt", "snow-capped", "Saying 'snow-cap-ed' in three syllables.", "A row of jagged mountain peaks with brilliant white snow-capped summits"),
        ("permafrost", "A thick subsurface layer of soil that remains frozen year-round.", "In the high Arctic mountains, roots cannot penetrate the deep permafrost.", "PUR-muh-frawst", "per-ma-frost", "Saying 'per-mah-frost' with wrong vowel.", "An illustrated soil cross-section showing active soil above permafrost"),
        ("whiteout", "A weather condition in which snow and clouds produce uniform white.", "During the whiteout, the climbers navigated strictly by compass.", "WYT-owt", "white-out", "Saying 'weet-owt' with long 'e'.", "A complete whiteout where ground and sky blend into uniform white mist"),
    ],
    # L18: 8+ letter mountaineering techniques & gear
    [
        ("carabiner", "A metal loop with a spring-loaded gate used in climbing ropes.", "He clipped his safety rope into the locking steel carabiner.", "kair-uh-BEE-ner", "car-a-bi-ner", "Saying 'cara-by-ner' with long 'i'.", "An anodized blue locking aluminum climbing carabiner with screw gate"),
        ("crampons", "Plural of crampon; spiked metal plates attached to boots for ice.", "Sharp steel crampons provided solid traction on the steep blue glacier.", "KRAM-pahnz", "cram-pons", "Saying 'cram-pawns' with wrong stress.", "Spiked steel mountaineering crampons strapped to heavy hiking boots on ice"),
        ("icepicker", "A specialized pick used by mountaineers for chipping steps in ice.", "The climber swung the icepicker firmly into the vertical frozen wall.", "EYS-pik-er", "ice-pick-er", "Dropping the 'k' in pick.", "A technical mountaineering ice axe pick planted securely into blue ice"),
        ("abseiling", "The act of descending a rock face using a doubled rope.", "She enjoyed the thrilling experience of abseiling down the granite cliff.", "AHB-say-ling", "ab-seil-ing", "Saying 'ab-sy-ling' with long 'i'.", "A climber rappelling abseiling backward down a vertical stone cliff"),
        ("rappelling", "The controlled descent of a vertical drop using a climbing rope.", "Rappelling down the waterfall gorge required steady footwork and focus.", "ruh-PEL-ing", "rap-pel-ling", "Saying 'rap-uh-ling' with dropped syllable.", "A climber using a rope and harness rappelling down beside a waterfall"),
        ("switchback", "A sharp zigzag path or road up a steep mountain slope.", "The trail climbed the mountain face in a series of gentle switchbacks.", "SWICH-bak", "switch-back", "Saying 'swish-back' with 'sh'.", "A zigzagging dirt trail switchback carving back and forth up a green slope"),
        ("bivouac", "A temporary camp without tents or cover, used by mountaineers.", "They set up a safe emergency bivouac on a wide stone ledge.", "BIV-oo-ak", "biv-ou-ac", "Saying 'bee-voo-ack' with long 'e'.", "A mountaineer in a sleeping bag under a starry sky on a high ledge"),
    ],
    # L19: 8+ letter mountain ecology & biodiversity
    [
        ("timberline", "The elevation limit above which trees cannot grow on mountains.", "Stunted dwarf pines marked the transition at the rocky timberline.", "TIM-ber-lyn", "tim-ber-line", "Saying 'teem-ber-line' with long 'e'.", "The distinct boundary where green forest ends and rocky alpine peaks begin"),
        ("ptarmigan", "A northern grouse bird whose feathers turn white in winter.", "The rock ptarmigan blended invisibly against the snow-covered boulders.", "TAHR-mi-guhn", "ptar-mi-gan", "Pronouncing the silent initial 'p'.", "A white feathered winter ptarmigan bird perched on a snowy rock"),
        ("snowleopard", "A large rare cat with smoky grey fur that lives in Central Asian peaks.", "The elusive snow leopard padded silently across the high Himalayan crags.", "SNOH-lep-erd", "snow-leop-ard", "Saying 'snow-lee-o-pard' with extra syllables.", "A magnificent snow leopard with thick spotted fur perched on a cliff"),
        ("bighorn", "A wild mountain sheep with large curved horns.", "A majestic bighorn ram stood proudly atop the red sandstone ridge.", "BIG-horn", "big-horn", "Saying 'beek-horn' with long 'e'.", "A male bighorn sheep with huge spiral horns standing on a rock ledge"),
        ("chough", "A black crow-like bird with a red or yellow bill found on mountains.", "Alpine choughs performed acrobatics in the updrafts along the ridge.", "CHUHf", "chough", "Saying 'choh' or 'chow'.", "A glossy black alpine chough bird with a bright red beak and red legs"),
        ("marmots", "Plural of marmot; burrowing alpine rodents.", "Two playful marmots wrestled happily in the sunny summer meadow.", "MAHR-muhts", "mar-mots", "Saying 'mar-motes' with long 'o'.", "Two furry alpine marmots playing on a grassy slope near their burrow"),
        ("grizzly", "A large brown bear of North America with a hump on its shoulders.", "A mighty grizzly bear grazed on sweet alpine huckleberries.", "GRIZ-lee", "griz-zly", "Saying 'grees-lee' with long 'e'.", "A massive grizzly bear with a silver-tipped fur coat walking in a meadow"),
    ],
    # L20: 8+ letter cave formations & speleology
    [
        ("speleology", "The scientific study of caves and other subterranean features.", "Her passion for speleology led her to explore vast underground caverns.", "spee-lee-AHL-uh-jee", "spe-le-ol-o-gy", "Stumbling over the vowel transitions.", "A speleologist in a helmet with a light exploring a limestone cave"),
        ("subterranean", "Existing, occurring, or done under the earth's surface.", "A clear subterranean river flowed through the ancient limestone caverns.", "suhb-tuh-RAY-nee-uhn", "sub-ter-ra-ne-an", "Skipping the 'ra' syllable.", "An underground subterranean river flowing through a cavern lit with lamps"),
        ("limestone", "A hard sedimentary rock composed mainly of calcium carbonate.", "Rainwater carved spectacular caves through layers of soft limestone.", "LYM-stohn", "lime-stone", "Saying 'leem-stone' with long 'e'.", "A dramatic white and grey limestone cliff formation with natural arches"),
        ("stalagmite", "A mound or tapering column rising from the floor of a cave.", "Centuries of dripping mineral water built a giant calcite stalagmite.", "stuh-LAG-myt", "sta-lag-mite", "Saying 'stay-lag-mite' with long 'a'.", "A tall golden calcite stalagmite rising upward from a wet cave floor"),
        ("stalactite", "A tapering structure hanging like an icicle from a cave roof.", "Delicate soda-straw stalactites hung from the vaulted cave ceiling.", "stuh-LAK-tyt", "sta-lac-tite", "Saying 'stay-lack-tite' with long 'a'.", "Delicate mineral stalactites hanging like stone icicles from a ceiling"),
        ("flowstone", "Rock deposited by precipitation from mineral-rich water in caves.", "Smooth sheets of glittering flowstone resembled frozen stone waterfalls.", "FLOH-stohn", "flow-stone", "Saying 'flaw-stone' with short 'o'.", "Sheets of wavy golden-brown calcite flowstone cascading down a cave wall"),
        ("calcite", "A white or clear mineral consisting of calcium carbonate.", "Pure crystalline calcite sparkled under the beam of the explorer's light.", "KAL-syt", "cal-cite", "Saying 'kal-seet' with long 'e'.", "A sparkling cluster of geometric white and clear calcite mineral crystals"),
    ],
    # L21: 8+ letter alpine landscape & vistas
    [
        ("panoramic", "With a wide view of an extensive area in all directions.", "The summit provided a breathtaking panoramic view of twelve peaks.", "pan-uh-RAM-ik", "pan-o-ram-ic", "Saying 'pan-uh-ray-mik' with long 'a'.", "A sweeping panoramic 360-degree photo of snow-capped mountain ranges"),
        ("breathtaking", "Astonishing or awe-inspiring in quality or appearance.", "The sunrise over the snow-covered alpine range was truly breathtaking.", "BRETH-tay-king", "breath-tak-ing", "Saying 'breeth-tay-king' with long 'ee'.", "A stunning sunrise with golden rays lighting up snowy mountain summits"),
        ("wilderness", "An uncultivated and wild uninhabited region.", "They preserved thousands of acres of pristine mountain wilderness.", "WIL-der-nis", "wil-der-ness", "Saying 'wyld-er-ness' with long 'i'.", "An untouched mountain valley with blue lakes and pine forests under clouds"),
        ("spectacular", "Beautiful in a dramatic and eye-catching way.", "The sheer vertical granite face was a spectacular sight to behold.", "spek-TAK-yuh-ler", "spec-tac-u-lar", "Saying 'spec-tak-lar' with dropped syllable.", "A dramatic view of soaring granite rock needles against a golden sunset"),
        ("monumental", "Great in importance, extent, or size; majestic.", "The colossal mountain range stood as a monumental testament to nature.", "mahn-yuh-MEN-tuhl", "mon-u-men-tal", "Skipping the 'u' syllable.", "A massive monumental wall of towering stone mountains rising into sky"),
        ("magnificence", "The quality of being magnificent; splendid beauty.", "Visitors stood in awe at the sheer magnificence of the alpine peaks.", "mag-NIF-i-suhns", "mag-nif-i-cence", "Saying 'mag-neef-i-cence' with wrong vowel.", "Sunlight streaming through towering mountain peaks onto a pristine lake"),
        ("picturesque", "Visually attractive, especially in a quaint or charming way.", "The wooden chalet sat in a picturesque alpine valley of wildflowers.", "pik-chuh-RESK", "pic-tur-esque", "Saying 'pic-tur-esk-yoo' with wrong ending.", "A picturesque scene of a wooden cabin in an alpine meadow surrounded by peaks"),
    ],
    # L22: 8+ letter mountain hydrology & glaciers
    [
        ("watershed", "An area of land that drains all streams to a common outlet.", "The high mountain watershed supplied freshwater to millions of homes.", "WAH-ter-shed", "wa-ter-shed", "Saying 'wader-shed' with sloppy 'd'.", "An aerial map diagram showing mountain streams converging into a river"),
        ("headwaters", "The streams at the source of a river.", "The clean headwaters of the mighty river began in alpine snowfields.", "HED-wah-terz", "head-wa-ters", "Saying 'heed-wa-ters' with long 'e'.", "A crystal-clear bubbling spring headwater in a high mountain meadow"),
        ("meltwater", "Water formed by the melting of snow and ice.", "Cold turquoise meltwater rushed down the river gorge in early summer.", "MELT-wah-ter", "melt-wa-ter", "Saying 'mel-wader' with dropped 't'.", "Turbulent turquoise blue meltwater surging through a rocky mountain river"),
        ("periglacial", "Relating to areas adjacent to glaciers or subject to freeze-thaw.", "Periglacial landscapes featured patterned stone rings and frost cracks.", "pair-i-GLAY-shuhl", "per-i-gla-cial", "Saying 'per-ee-gla-ceel' with wrong ending.", "A tundra landscape with patterned ground circles near a retreating glacier"),
        ("serac", "A pinnacle or block of ice among the crevasses of a glacier.", "A towering blue serac leaned precariously over the icefall route.", "suh-RAK", "se-rac", "Saying 'see-rack' with long 'e'.", "A massive sculpted pillar of glowing blue glacier ice standing tall"),
        ("bergschrund", "A deep crevasse formed where moving glacier ice separates from stagnant ice.", "The climbers bridged the deep bergschrund using an aluminum ladder.", "BURK-shroond", "berg-schrund", "Stumbling over the German origin consonants.", "A massive gaping bergschrund crevasse separating mountain rock from ice"),
        ("icefall", "A frozen waterfall or chaotic jumble of ice in a glacier.", "Navigating the Khumbu Icefall required careful route-finding among seracs.", "EYS-fawl", "ice-fall", "Saying 'eese-fall' with long 'e'.", "A chaotic maze of towering blue ice blocks and crevasses in an icefall"),
    ],
    # L23: 8+ letter mountaineering challenges & safety
    [
        ("acclimatize", "To become accustomed to a new climate or altitude.", "Climbers spent three days at base camp to acclimatize to thin air.", "uh-KLY-muh-tyz", "ac-cli-ma-tize", "Saying 'ac-clee-ma-tize' with long 'e'.", "Climbers resting at high base camp drinking warm tea in the sun"),
        ("expeditions", "Plural of expedition; organized journeys for exploration.", "High-altitude mountain expeditions required months of careful preparation.", "ek-spuh-DISH-uhnz", "ex-pe-di-tions", "Saying 'ex-pree-di-shuns' with wrong vowels.", "A mountain base camp of yellow expedition dome tents pitched on snow"),
        ("mountaineering", "The sport or activity of climbing mountains.", "Mountaineering teaches endurance, teamwork, judgment, and perseverance.", "mown-tuh-NEER-ing", "moun-tain-eer-ing", "Saying 'mown-teh-neer-ing' with dropped syllable.", "A line of mountaineers roped together ascending a snowy ridge at sunrise"),
        ("orienteering", "The sport of navigating through country with map and compass.", "The scouts mastered wilderness orienteering across the rugged hills.", "or-ee-en-TEER-ing", "o-ri-en-teer-ing", "Stumbling over the initial vowel sequence.", "A hiker using a baseplate compass aligned with contour lines on a map"),
        ("alpinist", "A person who climbs mountains, especially in the Alps.", "The skilled alpinist completed a solo ascent of the North Face.", "AL-pin-ist", "al-pin-ist", "Saying 'al-peen-ist' with long 'e'.", "A focused alpinist with ice axes climbing a steep snow and ice face"),
        ("pathfinder", "A person who goes ahead to discover or show a way through unknown country.", "The trusted pathfinder guided the team safely through the rocky maze.", "PATH-fyn-der", "path-find-er", "Mispronouncing unvoiced 'th' sound.", "A guide pointing toward a safe mountain pass with a hiking group"),
        ("wayfarer", "A person who travels on foot, especially on long journeys.", "The weary wayfarer rested beside the mountain spring before continuing.", "WAY-fair-er", "way-far-er", "Saying 'way-fah-rer' with flat 'a'.", "A hiker with a walking stick walking along a scenic mountain trail"),
    ],
    # L24: 8+ letter high-altitude physiology & equipment
    [
        ("altimeter", "An instrument for determining altitude attained.", "The digital altimeter showed they had climbed over eight thousand feet.", "al-TIM-i-ter", "al-tim-e-ter", "Saying 'AL-ti-mee-ter' with wrong stress.", "A wrist altimeter displaying current elevation and barometric pressure"),
        ("barometer", "An instrument measuring atmospheric pressure, used in forecasting.", "A falling barometer indicated an approaching mountain snowstorm.", "buh-RAHM-i-ter", "ba-rom-e-ter", "Saying 'BAIR-oh-mee-ter' with wrong stress.", "An antique brass circular wall barometer with a needle dial"),
        ("anemometer", "An instrument for measuring the speed of the wind.", "The mountain weather station recorded wind gusts with a spinning anemometer.", "an-uh-MAHM-i-ter", "an-e-mome-ter", "Stumbling over the multisyllabic flow.", "A three-cup spinning anemometer on a metal pole against a cloudy sky"),
        ("hydrometer", "An instrument for measuring the density of liquids.", "Geologists used a hydrometer to test the mineral content of the spring.", "hy-DRAHM-i-ter", "hy-drom-e-ter", "Saying 'HY-dro-mee-ter' with wrong stress.", "A glass hydrometer floating in a cylinder of mineral water"),
        ("thermometer", "An instrument for measuring and indicating temperature.", "The digital thermometer showed the temperature had dropped below freezing.", "ther-MAHM-i-ter", "ther-mom-e-ter", "Saying 'THER-moh-mee-ter' with wrong stress.", "An outdoor thermometer showing degrees Celsius and Fahrenheit"),
        ("insulation", "Material used to prevent loss of heat or intrusion of sound.", "Thick thermal insulation kept the mountaineering sleeping bag toasty.", "in-suh-LAY-shuhn", "in-su-la-tion", "Saying 'in-soo-lay-shun' with long 'oo'.", "A cross-section of layered goose down insulation in a winter jacket"),
        ("carabiners", "Plural of carabiner; metal loops with spring gates for ropes.", "A row of colorful carabiners hung neatly from her climbing gear harness.", "kair-uh-BEE-nerz", "car-a-bi-ners", "Saying 'cara-by-nerz' with long 'i'.", "An assortment of colorful aluminum locking carabiners arranged in a row"),
    ],
    # L25: 8+ letter mountain minerals & crystals
    [
        ("gemstone", "A precious or semiprecious stone, especially one cut and polished.", "A raw sapphire gemstone glittered within the dark granite rock.", "JEM-stohn", "gem-stone", "Saying 'gem-stohn' with hard 'g'.", "A sparkling cut blue sapphire gemstone resting on raw granite stone"),
        ("amethyst", "A precious purple variety of quartz.", "Geodes cracked open to reveal dazzling clusters of violet amethyst.", "AM-uh-thist", "am-e-thyst", "Saying 'am-uh-teest' and dropping 'th'.", "A cracked-open natural geode filled with sparkling deep violet amethyst"),
        ("topaz", "A precious stone, typically yellow, blue, or pink in color.", "Sunlight illuminated the golden facets of the imperial topaz crystal.", "TOH-paz", "to-paz", "Saying 'toh-payz' with long 'a'.", "A glittering golden-yellow raw topaz crystal gemstone in sunlight"),
        ("turquoise", "A greenish-blue mineral used widely in jewelry.", "Native artisans crafted jewelry from polished sky-blue turquoise stone.", "TUR-kwoyz", "tur-quoise", "Saying 'tur-kweez' with long 'ee'.", "Polished blue-green turquoise stones set in ornate silver jewelry"),
        ("obsidian", "A hard, dark, glasslike volcanic rock formed by rapid cooling.", "Ancient hunters crafted sharp arrowheads from shiny black obsidian.", "uhb-SID-ee-uhn", "ob-sid-i-an", "Saying 'ob-sid-yan' with dropped syllable.", "A shiny piece of black volcanic glass obsidian with razor-sharp edges"),
        ("feldspar", "An abundant rock-forming mineral consisting of aluminum silicates.", "Pink feldspar crystals gave the mountain granite its warm rosy hue.", "FELD-spahr", "feld-spar", "Saying 'feld-spore' with wrong vowel.", "A sample of pink potassium feldspar mineral embedded in white quartz"),
        ("sandstone", "Sedimentary rock consisting of sand or quartz grains cemented together.", "Wind carved natural arches through the towering red sandstone cliffs.", "SAND-stohn", "sand-stone", "Saying 'send-stone' with short 'e'.", "Massive swirling red and orange layered sandstone rock formations"),
    ],
    # L26: 8+ letter structural geology & forces
    [
        ("crystallize", "To form crystals or become crystalline in structure.", "Minerals dissolved in thermal water begin to crystallize as they cool.", "KRIS-tuh-lyz", "crys-tal-lize", "Saying 'kris-tuh-lees' with wrong ending.", "Time-lapse sequence showing geometric salt crystals growing in liquid"),
        ("stratigraphy", "The branch of geology concerned with the order of rock strata.", "Stratigraphy revealed millions of years of earth history in the canyon.", "struh-TIG-ruh-fee", "stra-tig-ra-phy", "Saying 'stra-tee-gra-phy' with wrong stress.", "A canyon wall displaying colorful horizontal layered rock strata"),
        ("metamorphic", "Relating to rock that has undergone transformation by heat and pressure.", "Gneiss and schist are common types of durable metamorphic rock.", "met-uh-MOR-fik", "met-a-mor-phic", "Saying 'met-a-mor-feek' with long 'e'.", "A piece of banded metamorphic rock showing wavy alternating mineral bands"),
        ("sedimentary", "Relating to rock that has formed from sediment deposited by water or air.", "Fossils are most commonly preserved inside layers of sedimentary rock.", "sed-uh-MEN-ter-ee", "sed-i-men-ta-ry", "Saying 'sed-men-ter-ee' with dropped syllable.", "Horizontal layers of tan and brown sedimentary shale and sandstone"),
        ("weathering", "The breakdown of rocks and soil through contact with the atmosphere.", "Freeze-thaw weathering slowly cracked the giant boulders on the ridge.", "WETH-er-ing", "weath-er-ing", "Saying 'wed-der-ing' and dropping 'th'.", "A boulder split in half by natural frost and water weathering"),
        ("erosion", "The gradual destruction or diminution of rock by wind or water.", "Centuries of water erosion carved the winding river canyon.", "i-ROH-zhuhn", "e-ro-sion", "Saying 'e-roh-shun' with unvoiced 'sh'.", "Dramatic rock hoodoos carved by wind and water erosion in a desert canyon"),
        ("tectonics", "The large-scale processes affecting the structure of the earth's crust.", "Plate tectonics pushed the oceanic plate under the continent to form mountains.", "tek-TAHN-iks", "tec-ton-ics", "Saying 'tek-tone-iks' with long 'o'.", "An illustrated diagram showing tectonic plates colliding to form peaks"),
    ],
    # L27: 8+ letter mountain conservation & wilderness
    [
        ("preservation", "The act of keeping natural mountain landscapes pristine.", "The national park was created for the preservation of alpine ecosystems.", "prez-er-VAY-shuhn", "pres-er-va-tion", "Saying 'press-er-va-tion' with hard 's'.", "A protected wilderness boundary sign in front of majestic mountains"),
        ("biodiversity", "The variety of plant and animal species in an alpine region.", "The mountain valley supported rich biodiversity from floor to peak.", "by-oh-dy-VUR-si-tee", "bi-o-di-ver-si-ty", "Saying 'bee-o-di-ver-si-ty' with wrong vowels.", "A collage of diverse mountain plants, insects, birds, and mammals"),
        ("sustainability", "Maintaining ecological health without depleting resources.", "Park rangers promoted sustainability by maintaining designated trails.", "suh-stay-nuh-BIL-i-tee", "sus-tain-a-bil-i-ty", "Stumbling over the seven-syllable sequence.", "Hikers carrying out all trash to preserve a clean mountain environment"),
        ("regeneration", "The renewal and regrowth of alpine plants after disturbance.", "Wildflower meadows showed rapid natural regeneration after the winter.", "ri-jen-er-AY-shuhn", "re-gen-er-a-tion", "Saying 're-gen-ra-tion' with dropped syllable.", "Fresh green shoots emerging from rocky gravel on an alpine slope"),
        ("sanctuary", "A safe haven where wildlife is protected from hunting.", "The remote high valley served as an undisturbed sanctuary for bighorn sheep.", "SANGK-choo-air-ee", "sanc-tu-ar-y", "Saying 'sank-too-air-y' with hard 't'.", "A herd of mountain goats grazing peacefully in a designated sanctuary"),
        ("environmental", "Relating to the natural world and the impact of activity on it.", "Students measured environmental factors such as snow depth and water purity.", "en-vy-ruhn-MEN-tuhl", "en-vi-ron-men-tal", "Saying 'en-vi-ro-men-tal' and dropping 'n'.", "Scientists taking water and snow samples at an alpine research station"),
        ("conservation", "The protection and management of natural resources and wildlife.", "Alpine conservation groups protected fragile tundra mosses from trampling.", "kahn-ser-VAY-shuhn", "con-ser-va-tion", "Saying 'con-ser-va-shun' with hard 's'.", "Park volunteers building low fences to protect fragile alpine flower meadows"),
    ],
    # L28: 8+ letter echoes, acoustics & sounds
    [
        ("reverberate", "To be repeated several times as an echo throughout a space.", "The clear trumpet note reverberated across the rocky canyon walls.", "ri-VUR-buh-rayt", "re-ver-ber-ate", "Saying 're-ver-ber-et' with short 'e'.", "Sound waves echoing and reverberating between steep canyon walls"),
        ("acoustics", "The properties of a room or valley that determine sound transmission.", "The natural stone amphitheater had remarkable acoustic qualities.", "uh-KOO-stiks", "a-cous-tics", "Saying 'uh-cow-stiks' with 'ow' sound.", "A natural circular stone canyon where a musical flute sounds loudly"),
        ("resonance", "The reinforcement or prolongation of sound by reflection.", "The deep resonance of the temple bell carried for miles in the valley.", "REZ-uh-nuhns", "res-o-nance", "Saying 'ree-zo-nance' with long 'e'.", "A large bronze bell in a mountain pavilion vibrating with soundwaves"),
        ("vibrations", "Plural of vibration; rapid periodic motions of the particles of a sound.", "Vocal vibrations produce soundwaves that reflect off solid granite.", "vy-BRAY-shuhnz", "vi-bra-tions", "Saying 'vee-bra-tions' with long 'e'.", "An illustrated waveform showing acoustic vibrations traveling in air"),
        ("sonorous", "Capable of producing a deep, resonant, or ringing sound.", "The monk's sonorous chanting echoed softly through the mountain cave.", "SAHN-er-uhs", "son-o-rous", "Saying 'suh-nor-us' with wrong stress.", "A traditional large brass horn blowing a deep tone in mountain air"),
        ("harmonics", "Musical tones produced as components of an acoustic sound.", "Wind passing through the rock arches generated eerie, beautiful harmonics.", "hahr-MAHN-iks", "har-mon-ics", "Saying 'har-mone-iks' with long 'o'.", "A musical staff showing harmonic overtones above a mountain landscape"),
        ("reflection", "The throwing back by a body or surface of light, heat, or sound.", "The glassy alpine lake offered a mirror reflection of the snow peaks.", "ri-FLEK-shuhn", "re-flec-tion", "Saying 're-flek-shun' with hard 's'.", "A crystal-clear still mountain lake reflecting a snow-capped peak like glass"),
    ],
    # L29: 8+ letter mountaineering mastery & navigation
    [
        ("orienteering", "Navigating through countryside with the aid of a map and compass.", "They won the gold medal in the national alpine orienteering championship.", "or-ee-en-TEER-ing", "o-ri-en-teer-ing", "Stumbling over the initial vowels.", "A competitor running with a map and compass through mountain woods"),
        ("mountaineers", "Plural of mountaineer; people who climb mountains as a sport.", "Experienced mountaineers shared stories around the warm lodge fireplace.", "mown-tuh-NEERZ", "moun-tain-eers", "Saying 'mown-teh-neerz' with dropped syllable.", "A group of cheerful mountaineers in down jackets sharing a meal"),
        ("trailblazers", "Plural of trailblazer; pioneers who create routes through wild country.", "The early trailblazers constructed the famous Appalachian Trail.", "TRAYL-blay-zerz", "trail-blaz-ers", "Saying 'trel-blazerz' with short 'e'.", "Pioneers with surveying instruments and axes carving a path through peaks"),
        ("cartographer", "A person who draws or produces maps of geographic terrain.", "The cartographer mapped every contour line and ridge with precision.", "kahr-TAHG-ruh-fer", "car-tog-ra-pher", "Saying 'car-to-gra-pher' with wrong stress.", "A cartographer at a drawing desk with compass, ruler, and elevation map"),
        ("expeditionary", "Forming or belonging to an expedition, especially for exploration.", "The expeditionary force established three supply depots along the route.", "ek-spuh-DISH-uh-nair-ee", "ex-pe-di-tion-ar-y", "Skipping the middle 'ar' syllable.", "A large organized exploration team with pack animals and gear in mountains"),
        ("stratosphere", "The layer of the earth's atmosphere above the troposphere.", "From high peaks and airplanes, the curvature of the earth touches the stratosphere.", "STRAT-uh-sfeer", "strat-o-sphere", "Saying 'stray-to-sphere' with long 'a'.", "A view from high above mountain clouds touching the dark blue stratosphere"),
        ("triangulation", "The tracing and measurement of a series of network triangles in surveying.", "Surveyors used triangulation to calculate the precise height of the summit.", "try-ang-gyuh-LAY-shuhn", "tri-an-gu-la-tion", "Stumbling over the five-syllable sequence.", "A surveyor with a theodolite on a peak measuring angles to other summits"),
    ],
    # L30: 8+ letter mountain triumph & perseverance
    [
        ("perseverance", "Persistence in doing something despite difficulty or delay in achieving success.", "Through teamwork and perseverance, they reached the highest peak.", "pur-suh-VEER-uhns", "per-se-ver-ance", "Saying 'per-sev-rance' with dropped syllable.", "Climbers holding hands in triumph at the top of a snowy mountain peak"),
        ("accomplishment", "Something that has been achieved successfully through skill.", "Reaching the summit was an unforgettable personal accomplishment.", "uh-KAHM-plish-muhnt", "ac-com-plish-ment", "Saying 'ac-cum-plish-ment' with short 'u'.", "A smiling hiker holding up an expedition certificate on a summit"),
        ("extraordinary", "Very unusual or remarkable; exceptional.", "The panoramic view of the glowing pink clouds at sunrise was extraordinary.", "ik-STROR-di-nair-ee", "ex-traor-di-nar-y", "Saying 'extra-ordinary' in six distinct syllables.", "A breathtaking vibrant sunrise casting golden light across jagged peaks"),
        ("unshakeable", "Unable to be disputed or weakened; firm and resolute.", "Her unshakeable determination inspired the entire climbing team.", "uhn-SHAY-kuh-buhl", "un-shake-a-ble", "Saying 'un-shak-a-ble' with short 'a'.", "A determined climber with focused eyes looking upward toward a challenge"),
        ("invincible", "Too powerful to be defeated or overcome.", "Standing atop the grand summit, they felt joyful, proud, and invincible.", "in-VIN-suh-buhl", "in-vin-ci-ble", "Saying 'in-veen-ci-ble' with long 'e'.", "A victorious hiker standing with arms wide open on top of the world"),
        ("triumphant", "Having won a battle or contest; victorious and celebratory.", "The triumphant expedition waved happily from the highest ridge.", "try-UHM-fuhnt", "tri-um-phant", "Saying 'tree-um-phant' with long 'e'.", "Cheering mountaineers celebrating on a mountain peak under a blue sky"),
        ("masterpiece", "A work of outstanding artistry, skill, or workmanship.", "The dramatic mountain range was nature's sculpted masterpiece.", "MAS-ter-pees", "mas-ter-piece", "Saying 'mes-ter-piece' with short 'e'.", "A stunning artistic vista of snowy alpine peaks and crystal turquoise lakes"),
    ],
]
