"""World 7: Crystal Caverns (Levels 1 to 30, 210 unique words)."""
from __future__ import annotations

# Format: (text, meaning, sentence, hint, syllables, mistake, alt)
WORLD_7_LEVELS = [
    # L1: 4-5 letter crystal foundation
    [
        ("gem", "A precious or semiprecious stone, especially when cut and polished.", "A sparkling purple amethyst gem caught the beam of the lantern.", "JEM", "gem", "Saying 'gem' with hard 'g'.", "A cut and polished faceted purple amethyst gemstone sparkling in light"),
        ("ruby", "A precious stone consisting of corundum in color varieties of red.", "The royal ring was set with a flawless glowing red ruby.", "ROO-bee", "ru-by", "Saying 'ruh-bee' with short 'u'.", "A glittering faceted deep crimson red ruby gemstone on black velvet"),
        ("jade", "A hard, typically green stone used for ornaments and carvings.", "The ancient artisan carved a smooth dragon figurine from green jade.", "JAYD", "jade", "Saying 'jed' with short 'e'.", "A polished emerald green jade pendant carved in a circular donut ring"),
        ("opal", "A semiprecious mineral showing changing rainbow colors.", "Flashes of green, blue, and fiery red sparkled inside the Australian opal.", "OH-puhl", "o-pal", "Saying 'ah-puhl' with short 'o'.", "A natural Australian precious black opal displaying fiery rainbow flashes"),
        ("onyx", "A semiprecious variety of agate with different colors in layers.", "A sleek piece of jet-black polished onyx was set into the silver pendant.", "AHN-iks", "on-yx", "Saying 'oh-niks' with long 'o'.", "A smooth, highly polished oval black onyx cabochon gemstone"),
        ("mica", "A shiny silicate mineral with a layered structure that splits into thin sheets.", "Glittering flakes of silver mica sparkled throughout the cave wall.", "MY-kuh", "mi-ca", "Saying 'mee-kuh' with long 'e'.", "Thin flexible translucent sheets of glittering silvery muscovite mica"),
        ("gold", "A yellow precious metal, the chemical element of atomic number 79.", "Veins of pure yellow gold gleamed brightly in the white quartz rock.", "GOHLD", "gold", "Saying 'gawld' with short 'o'.", "Natural raw golden nuggets and veins embedded in white quartz rock"),
    ],
    # L2: 5-letter gems & crystal terms
    [
        ("agate", "An ornamental stone consisting of a hard variety of chalcedony.", "Concentric banded rings of blue and white decorated the polished agate slice.", "AG-it", "ag-ate", "Saying 'uh-GAYT' with wrong stress.", "A polished cross-section slice of banded blue and white lace agate"),
        ("beryl", "A mineral of great hardness, occurring in hexagonal prisms.", "Emerald and aquamarine are precious color varieties of natural beryl.", "BAIR-uhl", "ber-yl", "Saying 'buh-RYL' with wrong vowels.", "A natural hexagonal green beryl crystal embedded in white pegmatite rock"),
        ("facet", "One side of something many-sided, especially of a cut gem.", "Each flat facet of the diamond was cut with mathematical precision.", "FAS-it", "fac-et", "Saying 'fay-sit' with long 'a'.", "Close-up of geometric polished facets of a brilliant cut diamond"),
        ("glint", "Give out or reflect small flashes of light.", "Tiny flecks of pyrite began to glint like gold in the cavern wall.", "GLINT", "glint", "Saying 'gleent' with long 'e'.", "Flashes of golden light glinting off minerals inside a dark cave"),
        ("gleam", "Shine brightly, especially with reflected light.", "Polished crystal pillars gleamed with magical light in the royal hall.", "GLEEM", "gleam", "Saying 'glim' with short 'i'.", "A tall carved crystal pillar gleaming with radiant white light"),
        ("geode", "A small cavity in rock lined with crystals or other mineral matter.", "She cracked the round stone in half to reveal a sparkling purple geode.", "JEE-ohd", "ge-ode", "Saying 'gee-ahd' with hard 'g'.", "A cracked-open round stone geode filled with sparkling amethyst crystals"),
        ("shine", "To emit or reflect bright light.", "The giant crystal chandeliers shine with breathtaking rainbow colors.", "SHYN", "shine", "Saying 'sheen' with long 'e'.", "A massive crystal chandelier radiating sparkling white light in a hall"),
    ],
    # L3: 5-letter cavern subterranean features
    [
        ("vault", "A roof in the form of an arch or a series of arches in a cavern.", "The natural stone vault of the cathedral cavern rose eighty feet high.", "VAWLT", "vault", "Saying 'volt' with long 'o'.", "A majestic arched natural stone ceiling vault inside a vast cavern"),
        ("grotto", "A picturesque cave, especially with clear subterranean water.", "A crystal-clear pool of turquoise water filled the illuminated grotto.", "GRAHT-oh", "grot-to", "Saying 'groh-toh' with long 'o'.", "A glowing turquoise subterranean grotto pool surrounded by stalactites"),
        ("chasm", "A deep fissure in the earth, rock, or other surface.", "A suspension bridge of glowing crystal spanned the bottomless chasm.", "KAZ-uhm", "chasm", "Saying 'chaz-um' with 'ch' sound.", "A deep dark rock chasm spanned by an illuminated crystal footbridge"),
        ("abyss", "A deep or seemingly bottomless space in the underground world.", "A beam of light pierced downward into the mysterious cavern abyss.", "uh-BIS", "a-byss", "Saying 'ay-biss' with long 'a'.", "A beam of white light shining down into the depths of a dark cave abyss"),
        ("shaft", "A long, narrow vertical passage or channel leading underground.", "A vertical mine shaft led deep into the crystal-bearing gemstone layers.", "SHAFT", "shaft", "Saying 'sheft' with short 'e'.", "A vertical wooden-supported mine shaft with a ladder descending into rock"),
        ("torch", "A portable means of illumination, especially a flaming stick.", "The explorer held the torch high to inspect the sparkling cavern walls.", "TORCH", "torch", "Saying 'turch' with wrong vowel.", "A flaming wooden torch casting warm golden light across glittering rock"),
        ("strata", "Plural of stratum; layers of sedimentary rock or earth.", "Distinct horizontal strata of colorful minerals banded the canyon wall.", "STRAY-tuh", "stra-ta", "Saying 'strah-tah' with flat vowels.", "Banded horizontal colorful layers of rock strata inside a canyon"),
    ],
    # L4: 6-letter gemstones & minerals
    [
        ("garnet", "A precious stone, typically dark red or green in color.", "Twelve-sided crystals of deep red garnet sparkled in the schist rock.", "GAHR-nit", "gar-net", "Saying 'gor-net' with wrong vowel.", "A cluster of natural dark red dodecahedral garnet crystals on rock"),
        ("topaz", "A precious stone, typically yellow, blue, or pink in color.", "A sparkling sky-blue topaz was cut into an elegant teardrop shape.", "TOH-paz", "to-paz", "Saying 'toh-payz' with long 'a'.", "A faceted sparkling sky-blue imperial topaz gemstone on white silk"),
        ("zircon", "A mineral occurring as prismatic crystals, typically brown or blue.", "Brilliant blue zircon stones flashed with higher luster than diamonds.", "ZUR-kahn", "zir-con", "Saying 'zeer-con' with long 'e'.", "A pair of dazzling brilliant cut electric blue zircon gemstones"),
        ("quartz", "A hard mineral consisting of silica, found in hex prisms.", "A magnificent specimen of smoky quartz rose from the museum pedestal.", "KWORTS", "quartz", "Saying 'kwarz' with 'z' sound.", "A towering cluster of dark smoky quartz crystal points on a stand"),
        ("pyrite", "A shiny yellow mineral resembling gold; iron disulfide.", "Fools often mistook the brassy cubic crystals of pyrite for real gold.", "PY-ryt", "py-rite", "Saying 'pee-ryt' with long 'e'.", "A cluster of perfect metallic golden cubic pyrite crystals in rock"),
        ("copper", "A red-brown metal, used since antiquity for ornaments.", "Natural dendritic native copper formed delicate branching shapes in stone.", "KAH-per", "cop-per", "Saying 'koh-per' with long 'o'.", "A branching natural specimen of reddish-brown dendritic native copper"),
        ("silver", "A precious shiny greyish-white metallic element.", "Delicate wires of native silver curled like frost through the calcite vein.", "SIL-ver", "sil-ver", "Saying 'seel-ver' with long 'e'.", "Delicate curling wires of natural native silver embedded in white stone"),
    ],
    # L5: 6-letter cavern acoustics & light
    [
        ("echoes", "Plural of echo; sounds repeated by reflection.", "Joyful flute notes created melodious echoes in the grand crystal gallery.", "EK-ohz", "ech-oes", "Saying 'ee-chohz' with 'ch' sound.", "Soundwaves rippling and echoing between tall crystal cavern columns"),
        ("prisms", "Plural of prism; transparent bodies that refract white light.", "Chandelier prisms cast dancing rainbows of color across the stone floor.", "PRIZ-uhmz", "prisms", "Saying 'pree-zuhmz' with long 'e'.", "Multiple glass prisms refracting bright white light into rainbow beams"),
        ("chimes", "Plural of chime; tuned bells or resonant musical tubes.", "Crystal chimes hanging in the cavern breeze produced pure, sweet notes.", "CHYMZ", "chimes", "Saying 'sheemz' with 'sh' sound.", "A hanging mobile of tuned hanging quartz crystal chimes in sunlight"),
        ("lustre", "A gentle sheen or soft glow, especially that of a partly reflective surface.", "The pearls and crystals possessed a deep, enchanting iridescent lustre.", "LUHS-ter", "lus-tre", "Saying 'loo-ster' with long 'oo'.", "A close-up showing the soft pearlescent lustre sheen of a polished mineral"),
        ("sparks", "Plural of spark; tiny glowing fiery or electrical particles.", "Striking the flint produced bright sparks that illuminated the dark cave.", "SPAHRKS", "sparks", "Saying 'sporks' with wrong vowel.", "A shower of bright golden sparks flying from striking two mineral stones"),
        ("gleams", "Plural of gleam; flashes or beams of bright light.", "Faint gleams of daylight signaled the approaching exit of the cavern tunnel.", "GLEEMZ", "gleams", "Saying 'glimz' with short 'i'.", "Sunlight gleams breaking through a natural arch at the end of a cave"),
        ("pillar", "A tall vertical structure of stone, such as a joined stalactite.", "A massive crystal pillar joined the ceiling and floor of the cavern.", "PIL-er", "pil-lar", "Saying 'pee-ler' with long 'e'.", "A colossal natural limestone and crystal pillar spanning floor to ceiling"),
    ],
    # L6: 6-letter mining & lapidary tools
    [
        ("chisel", "A long-bladed hand tool with a beveled cutting edge.", "The sculptor used a tempered steel chisel to shape the marble block.", "CHIZ-uhl", "chis-el", "Saying 'shiz-uhl' with 'sh'.", "A sharp steel stone-carving chisel and a wooden mallet resting on stone"),
        ("mallet", "A hammer with a large wooden or rubber head.", "He tapped the wooden mallet gently against the chisel to split the geode.", "MAL-it", "mal-let", "Saying 'may-lit' with long 'a'.", "A traditional wooden stone-carver's round mallet on a workbench"),
        ("trowel", "A small handheld tool with a flat blade used for digging.", "The mineralogist used a small trowel to extract delicate crystal points.", "TROW-uhl", "trow-el", "Saying 'troh-uhl' with long 'o'.", "A small stainless steel pointed archaeological digging trowel on sand"),
        ("loupe", "A small magnifying glass used by jewelers and watchmakers.", "The jeweler inspected the diamond's clarity through a ten-power loupe.", "LOOP", "loupe", "Saying 'low-p' with 'ow' sound.", "A chrome jeweler's folding pocket magnifying loupe examining a gemstone"),
        ("sieves", "Plural of sieve; utensils with meshes for separating particles.", "Miners washed gravel through wire sieves to uncover raw sapphires.", "SIVZ", "sieves", "Saying 'see-vz' with long 'e'.", "Nested round brass geological sieves with gravel and water in a pan"),
        ("shovels", "Plural of shovel; broad-bladed tools for moving earth.", "Miners stacked their steel shovels neatly outside the cavern entrance.", "SHUHV-uhlz", "shov-els", "Saying 'show-velz' with long 'o'.", "A pair of sturdy steel mining shovels leaning against a wooden timber"),
        ("ropes", "Plural of rope; strong cords of twisted fibers for climbing.", "Braided climbing ropes secured the spelunkers descending into the chamber.", "ROHPS", "ropes", "Saying 'rahps' with short 'o'.", "Coils of colorful dynamic nylon spelunking climbing ropes on a tarp"),
    ],
    # L7: 7-letter precious gemstones
    [
        ("diamond", "A precious stone consisting of clear and colorless pure carbon.", "The brilliant-cut diamond dispersed white light into fiery sparkles.", "DY-muhnd", "dia-mond", "Saying 'dy-uh-mond' in three syllables.", "A flawless sparkling multifaceted brilliant cut diamond gemstone"),
        ("emerald", "A bright green precious stone consisting of a variety of beryl.", "A rich royal green Colombian emerald glowed on the velvet cushion.", "EM-er-uhld", "em-er-ald", "Saying 'eem-rald' with long 'e'.", "A radiant rectangular step-cut green emerald gemstone glowing with light"),
        ("crystal", "A clear, transparent mineral or glass resembling ice.", "A giant hexagonal quartz crystal projected from the cavern ceiling.", "KRIS-tuhl", "crys-tal", "Saying 'kris-tayl' with wrong ending.", "A transparent hexagonal quartz crystal point reflecting rainbow highlights"),
        ("sapphire", "A precious transparent stone consisting of blue corundum.", "The royal necklace featured a dazzling cornflower blue sapphire pendant.", "SAF-yr", "sap-phire", "Saying 'saf-fear' with long 'e'.", "A deep velvet royal blue faceted oval sapphire gemstone on silk"),
        ("peridot", "A transparent green variety of olivine used as a gemstone.", "Golden-green peridot crystals were forged in deep volcanic mantle rock.", "PAIR-i-daht", "per-i-dot", "Pronouncing the silent 't' as 'pair-ee-dot'.", "A faceted lime-green peridot gemstone surrounded by small diamonds"),
        ("spinel", "A hard vitreous mineral consisting of magnesium aluminum oxide.", "The famous Black Prince's Ruby is actually a magnificent red spinel.", "spi-NEL", "spi-nel", "Saying 'SPIN-el' with wrong stress.", "A vibrant hot pink faceted cushion-cut natural spinel gemstone"),
        ("tanzanite", "A rare blue and violet variety of the mineral zoisite.", "Mined only near Mount Kilimanjaro, tanzanite shifts between blue and purple.", "TAN-zuh-nyt", "tan-za-nite", "Saying 'tan-zan-eet' with long 'e'.", "A trichroic violet-blue faceted tanzanite gemstone sparkling in light"),
    ],
    # L8: 7-letter mineral optical properties
    [
        ("clarity", "The quality of being clear, transparent, or free from flaws.", "The diamond was graded flawless for its exceptional optical clarity.", "KLAIR-i-tee", "clar-i-ty", "Saying 'clay-ri-ty' with long 'a'.", "A close-up of an exceptionally clear transparent quartz crystal sphere"),
        ("faceting", "The process of cutting flat surfaces on a gemstone to reflect light.", "Master faceting revealed the maximum brilliance and fire of the gem.", "FAS-i-ting", "fac-et-ing", "Saying 'fay-sit-ing' with long 'a'.", "A lapidary gem cutter polishing a gemstone on a rotating flat lap wheel"),
        ("sparkle", "Shine with a quick, bright, flickering gleam of light.", "Millions of tiny quartz crystals caused the entire cavern wall to sparkle.", "SPAHR-kuhl", "spar-kle", "Saying 'spor-kuhl' with wrong vowel.", "A galaxy of sparkling diamond light points shimmering on a dark wall"),
        ("glimmer", "Shine faintly with a soft, wavering, or gentle light.", "The phosphorescent mineral began to glimmer softly in the dark cave.", "GLIM-er", "glim-mer", "Saying 'gleem-er' with long 'e'.", "A cluster of soft glowing green fluorite crystals glimmering in dark"),
        ("radiant", "Shining, glowing brightly, or giving off rays of light.", "The golden sunstone crystal gave off a warm, radiant copper shimmer.", "RAY-dee-uhnt", "ra-di-ant", "Saying 'rah-dee-ant' with short 'a'.", "A glowing orange sunstone gemstone radiating warm golden light rays"),
        ("shimmer", "Shine with a soft, slightly wavering light.", "The surface of the subterranean lake seemed to shimmer with silver light.", "SHIM-er", "shim-mer", "Saying 'sheem-er' with long 'e'.", "Gentle light waves shimmering across the surface of a crystal clear pool"),
        ("glitter", "Shine with a bright, shimmering, reflected light.", "Golden pyrite crystals glittered like pirate treasure inside the cavern.", "GLIT-er", "glit-ter", "Saying 'gleet-ter' with long 'e'.", "Golden metallic crystals glittering brightly under bright flashlight beams"),
    ],
    # L9: 7-letter subterranean geology
    [
        ("caverns", "Plural of cavern; vast underground caves or chambers.", "Illuminated walkways wound through the grand underground caverns.", "KAV-ernz", "cav-erns", "Saying 'kay-verns' with long 'a'.", "A vast limestone cavern with wooden tourist walkways and golden lighting"),
        ("geology", "The science of the physical structure and substance of the earth.", "Studying cavern geology reveals millions of years of mineral history.", "jee-AHL-uh-jee", "ge-ol-o-gy", "Saying 'jee-oh-lo-gy' with wrong stress.", "A geologist with a magnifying glass examining crystalline rock formations"),
        ("mineral", "A solid inorganic substance of natural occurrence.", "Each distinct mineral has a unique crystal structure and chemical formula.", "MIN-er-uhl", "min-er-al", "Saying 'mee-ner-al' with long 'e'.", "An organized display of various colorful raw mineral specimen rocks"),
        ("bedrock", "Solid rock underlying loose deposits such as soil or alluvium.", "The cavern floor was carved directly into solid limestone bedrock.", "BED-rahk", "bed-rock", "Saying 'bad-rock' with short 'a'.", "Exposed layers of solid grey limestone bedrock inside a cavern floor"),
        ("passage", "A narrow way allowing access between underground chambers.", "A narrow rocky passage connected the crystal room to the grand gallery.", "PAS-ij", "pas-sage", "Saying 'pass-ayj' with wrong ending.", "A well-lit natural stone passage tunnel leading between two large caves"),
        ("gallery", "A long underground room or balcony in a cavern system.", "The crystal gallery was lined with towering columns of sparkling selenite.", "GAL-er-ee", "gal-ler-y", "Saying 'gaw-ler-y' with wrong vowel.", "A magnificent long high-ceilinged cavern gallery lined with crystals"),
        ("chamber", "A large subterranean room or space within a cave system.", "The echo chamber was renowned for its extraordinary acoustic properties.", "CHAYM-ber", "cham-ber", "Saying 'sham-ber' with 'sh' sound.", "A vast cathedral-like subterranean cave chamber with soaring ceiling"),
    ],
    # L10: 7-letter cave formations & hydrology
    [
        ("flowstone", "Sheet-like deposits formed by water flowing over cave surfaces.", "Sheets of golden calcite flowstone resembled frozen stone waterfalls.", "FLOH-stohn", "flow-stone", "Saying 'flaw-stone' with short 'o'.", "Cascading golden-brown calcite flowstone formations on a cavern wall"),
        ("stalagm", "A short term for stalagmite; a mineral formation on cave floor.", "A massive calcite stalagmite rose twenty feet from the cavern floor.", "STAL-uhg-myt", "sta-lag-mite", "Saying 'stay-lag-mite' with long 'a'.", "A giant rounded mineral stalagmite pillar rising from the stone floor"),
        ("stalact", "A short term for stalactite; an icicle-like mineral formation on cave ceiling.", "Water dripped steadily from the pointed tip of the slender stalactite.", "stuh-LAK-tyt", "sta-lac-tite", "Saying 'stay-lack-tite' with long 'a'.", "A slender delicate soda-straw stalactite hanging from a cavern ceiling"),
        ("columns", "Plural of column; vertical stone pillars formed when stalactites meet stalagmites.", "Giant crystal columns supported the vaulted ceiling of the grand hall.", "KAHL-uhmz", "col-umns", "Pronouncing the silent 'n' as in 'col-um-nz'.", "Towering natural stone columns where ceiling and floor formations met"),
        ("drapery", "A thin, wavy sheet of cave mineral deposit hanging like cloth.", "Backlit cave drapery glowed with translucent orange and cream bands.", "DRAY-puh-ree", "drap-er-y", "Saying 'drap-ree' with short 'a'.", "Translucent wavy bacon-strip cave drapery formations glowing with light"),
        ("rimstone", "A mineral deposit formed around the edge of a cave pool.", "Terraced rimstone dams held back stepped pools of crystal-clear water.", "RIM-stohn", "rim-stone", "Saying 'reem-stone' with long 'e'.", "Stepped terraced rimstone pools filled with turquoise clear water in cave"),
        ("helictite", "A distorted, branching cave mineral formation that defies gravity.", "Curving helictite crystals twisted in all directions across the ceiling.", "huh-LIK-tyt", "he-lic-tite", "Saying 'hee-lick-tite' with long 'e'.", "Delicate curved white helictite crystal formations branching in gravity-defying curls"),
    ],
    # L11: 8+ letter rare gemstones & minerals
    [
        ("aquamarine", "A blue or cyan variety of beryl resembling seawater.", "A flawless sea-blue aquamarine was carved into an emerald-cut pendant.", "ak-wuh-muh-REEN", "aq-ua-ma-rine", "Saying 'ah-kwah-ma-ryn' with long 'i'.", "A dazzling sea-blue rectangular faceted aquamarine gemstone on white silk"),
        ("alexandrite", "A rare gemstone that shifts color from green in daylight to red in lamp light.", "Alexandrite is famous for changing from emerald green to ruby red under lamps.", "al-ig-ZAN-dryt", "al-ex-an-drite", "Saying 'al-ex-an-dree-tay' with extra vowel.", "A rare alexandrite gemstone showing green under sunlight and red under incandescent"),
        ("tourmaline", "A mineral occurring in various colors, especially black, green, and pink.", "Watermelon tourmaline displayed green outer rind and vibrant pink core.", "TOOR-muh-leen", "tour-ma-line", "Saying 'tor-ma-lyn' with long 'i'.", "A polished slice of bi-color watermelon tourmaline showing pink center and green edge"),
        ("moonstone", "A pearly and opalescent stone consisting of potassium feldspar.", "The smooth cabochon moonstone glowed with a floating blue adularescence.", "MOON-stohn", "moon-stone", "Saying 'mun-stone' with short 'u'.", "A smooth oval cabochon moonstone glowing with mystical floating blue light"),
        ("sunstone", "A plagioclase feldspar showing a spangled golden appearance.", "Golden copper platelets inside the Oregon sunstone glittered brilliantly.", "SUHN-stohn", "sun-stone", "Saying 'soon-stone' with long 'oo'.", "A glowing orange faceted sunstone gemstone displaying sparkling copper glitter"),
        ("chrysoberyl", "A yellowish-green or brown mineral, valued as a gemstone.", "Cat's eye chrysoberyl displayed a sharp, moving white line of light.", "kris-uh-BAIR-uhl", "chrys-o-ber-yl", "Saying 'chrys-o-beer-ul' with 'ch' sound.", "A golden honey cat's eye chrysoberyl gemstone with a sharp white central slit line"),
        ("malachite", "A green mineral consisting of basic copper carbonate.", "Vibrant concentric green bands decorated the polished malachite box.", "MAL-uh-kyt", "mal-a-chite", "Saying 'mal-a-cheet' with long 'e'.", "A polished slab of swirling emerald green banded malachite mineral"),
    ],
    # L12: 8+ letter optical properties of crystals
    [
        ("crystallize", "To form crystals or take on a definite crystalline structure.", "Supersaturated mineral water begins to crystallize into giant selenite points.", "KRIS-tuh-lyz", "crys-tal-lize", "Saying 'kris-tuh-lees' with wrong ending.", "A giant white selenite crystal growing in mineral-rich geothermal water"),
        ("birefringence", "The double refraction of light in a transparent, molecularly ordered material.", "Calcite crystals exhibit strong birefringence, doubling any text beneath them.", "by-ri-FRIN-juhns", "bi-re-frin-gence", "Stumbling over the five-syllable sequence.", "A clear Iceland spar calcite crystal doubling a line of text viewed through it"),
        ("pleochroism", "The phenomenon of an optical change of color when viewed in different directions.", "Iolite crystals display strong pleochroism from violet-blue to pale yellow.", "plee-AHK-roh-iz-uhm", "ple-o-chro-ism", "Stumbling over the vowel transitions.", "A rectangular crystal showing different colors when viewed from three angles"),
        ("fluorescence", "The emission of light by a substance that has absorbed light.", "Under ultraviolet light, the fluorite crystals glowed vibrant cobalt blue.", "flaw-RES-uhns", "flu-o-res-cence", "Saying 'floo-or-es-cence' with wrong stress.", "A collection of colorful minerals glowing neon under ultraviolet blacklight"),
        ("phosphorescence", "Luminescence that persists after the excitation source has ended.", "The minerals continued to glow with soft green phosphorescence for minutes.", "fahs-fuh-RES-uhns", "phos-pho-res-cence", "Stumbling over the consonant transitions.", "A darkened room showing green glowing crystals emitting phosphorescence"),
        ("refraction", "The bending of a ray of light when it passes between media.", "Prismatic refraction split the single ray of light into a spectrum.", "ri-FRAK-shuhn", "re-frac-tion", "Saying 'ree-frak-shun' with hard 's'.", "A crystal prism bending a beam of white light into a rainbow spectrum"),
        ("dispersion", "The separation of white light into colors by refraction.", "High optical dispersion gives diamonds their famous colorful fiery flashes.", "di-SPUR-zhuhn", "dis-per-sion", "Saying 'dis-per-shun' with unvoiced 'sh'.", "Close-up of a diamond dispersing light into brilliant red, blue, and yellow sparkles"),
    ],
    # L13: 8+ letter speleology & cave sciences
    [
        ("speleothem", "A structure formed in a cave by the deposition of minerals.", "Stalactites, stalagmites, and draperies are all classic types of speleothems.", "SPEE-lee-oh-them", "spe-le-o-them", "Saying 'spel-ee-oh-tam' and dropping 'th'.", "An illustrated chart showing various types of cave mineral speleothems"),
        ("speleology", "The scientific study or exploration of caves.", "Speleology combines geology, hydrology, biology, and technical rope climbing.", "spee-lee-AHL-uh-jee", "spe-le-ol-o-gy", "Stumbling over the vowel transitions.", "A team of cave scientists mapping an underground crystal cavern with lasers"),
        ("stalactites", "Plural of stalactite; icicle-like mineral structures hanging from roofs.", "Slender soda-straw stalactites hung by the thousands from the vault.", "stuh-LAK-tyts", "sta-lac-tites", "Saying 'stay-lack-tites' with long 'a'.", "A ceiling covered in thousands of glowing white soda straw stalactites"),
        ("stalagmites", "Plural of stalagmite; mineral columns rising from cave floors.", "Centuries of dripping mineral water built giant tiered stalagmites.", "stuh-LAG-myts", "sta-lag-mites", "Saying 'stay-lag-mites' with long 'a'.", "A cluster of tiered golden calcite stalagmites on a wet cave floor"),
        ("subterranean", "Existing, occurring, or done under the earth's surface.", "A vast subterranean lake stretched into the darkness of the cavern.", "suhb-tuh-RAY-nee-uhn", "sub-ter-ra-ne-an", "Skipping the 'ra' syllable.", "An underground subterranean lake with crystal turquoise water lit by lamps"),
        ("limestone", "A hard sedimentary rock composed mainly of calcium carbonate.", "Slightly acidic rainwater dissolved deep cavern chambers in the limestone.", "LYM-stohn", "lime-stone", "Saying 'leem-stone' with long 'e'.", "Massive white and cream limestone cavern walls sculpted by ancient water"),
        ("mineralogy", "The scientific study of minerals, their structure, and properties.", "Her degree in mineralogy allowed her to identify rare gemstone crystal habits.", "min-er-AHL-uh-jee", "min-er-al-o-gy", "Saying 'min-ra-lo-gy' with dropped syllable.", "A mineralogist using an optical polarizing microscope to study crystal thin sections"),
    ],
    # L14: 8+ letter crystal geometries & chemistry
    [
        ("hexagonal", "Having six sides and six angles; the crystal system of quartz.", "Beryl and quartz crystals grow in elegant, symmetrical hexagonal prisms.", "hek-SAG-uh-nuhl", "hex-ag-o-nal", "Saying 'hex-ay-goh-nuhl' with wrong stress.", "A perfect six-sided hexagonal quartz crystal point showing natural terminations"),
        ("octahedral", "Having eight plane faces; the crystal habit of diamonds and fluorite.", "Fluorite and diamond naturally crystallize in perfect octahedral shapes.", "ahk-tuh-HEE-druhl", "oc-ta-he-dral", "Saying 'ahk-tah-heed-ral' with wrong vowels.", "A purple fluorite crystal formed in a natural eight-sided octahedral shape"),
        ("tetrahedral", "Having four triangular faces; a common molecular geometry.", "Silica and oxygen atoms arrange in strong tetrahedral units in quartz.", "tet-ruh-HEE-druhl", "tet-ra-he-dral", "Skipping the 'ra' syllable.", "A molecular model of a silicon-oxygen tetrahedron crystal building block"),
        ("dodecahedron", "A three-dimensional shape having twelve flat faces.", "Deep red garnet crystals naturally form symmetrical dodecahedron stones.", "doh-dek-uh-HEE-druhn", "do-dec-a-he-dron", "Stumbling over the five-syllable sequence.", "A dark red garnet gemstone crystal naturally shaped with twelve diamond faces"),
        ("crystallography", "The branch of science concerned with the structure and properties of crystals.", "X-ray crystallography revealed the exact atomic arrangements within diamonds.", "kris-tuh-LAHG-ruh-fee", "crys-tal-log-ra-phy", "Saying 'crys-tah-loh-gra-phy' with wrong stress.", "An X-ray diffraction spot pattern displaying crystal atomic symmetry on screen"),
        ("luminescence", "The emission of light by a substance not resulting from heat.", "The glowing crystal pillars filled the chamber with soft green luminescence.", "loo-mi-NES-uhns", "lu-mi-nes-cence", "Saying 'lu-meen-es-cence' with long 'e'.", "Pillars of translucent selenite glowing with magical soft green light"),
        ("calcite", "A white or clear mineral consisting of calcium carbonate.", "Pure crystalline calcite crystals lined the edges of the subterranean pool.", "KAL-syt", "cal-cite", "Saying 'kal-seet' with long 'e'.", "Sparkling clear rhombic calcite crystals encrusting the edge of a cave pool"),
    ],
    # L15: 8+ letter lapidary artistry & jewelry
    [
        ("silversmith", "A person who makes or repairs silver objects and jewelry.", "The master silversmith set the raw sapphire into an ornate silver pendant.", "SIL-ver-smith", "sil-ver-smith", "Saying 'seel-ver-smeet' and dropping 'th'.", "A silversmith at a wooden workbench setting a gemstone with small tools"),
        ("goldsmith", "A person who makes gold articles and fine jewelry.", "The skilled goldsmith forged a filigree gold crown studded with diamonds.", "GOHLD-smith", "gold-smith", "Dropping the 'th' sound.", "A goldsmith soldering intricate golden filigree wires with a jewelers torch"),
        ("gemologist", "An expert qualified to identify, grade, and evaluate gemstones.", "The certified gemologist verified the authenticity of the Burmese ruby.", "jem-AHL-uh-jist", "gem-ol-o-gist", "Saying 'gem-o-lo-gist' with hard 'g'.", "A gemologist using a refractometer and microscope to test gemstone authenticity"),
        ("masterpiece", "A work of outstanding artistry, skill, or workmanship.", "The carved crystal cathedral was celebrated as a timeless architectural masterpiece.", "MAS-ter-pees", "mas-ter-piece", "Saying 'mes-ter-piece' with short 'e'.", "A breathtaking intricately carved translucent crystal palace sculpture"),
        ("craftsmanship", "The quality of design and work shown in something made by hand.", "The intricate jewelry showcased centuries of exceptional royal craftsmanship.", "KRAFTS-muhn-ship", "crafts-man-ship", "Saying 'krefts-man-ship' with short 'e'.", "An ornate golden royal chalice inlaid with sparkling diamonds and sapphires"),
        ("authenticity", "The quality of being genuine, real, or authentic.", "A laboratory certificate accompanied the diamond to confirm its authenticity.", "aw-then-TIS-i-tee", "au-then-tic-i-ty", "Saying 'ow-then-ti-ci-ty' with wrong vowels.", "An official embossed gemstone grading laboratory certificate of authenticity"),
        ("magnificence", "The quality of being magnificent; splendid beauty or grandeur.", "Visitors gasped in delight at the sheer magnificence of the gemstone hall.", "mag-NIF-i-suhns", "mag-nif-i-cence", "Saying 'mag-neef-i-cence' with wrong vowel.", "A magnificent display hall filled with glowing giant geodes and cut gemstones"),
    ],
    # L16: 8+ letter acoustic resonance & sound mastery
    [
        ("reverberate", "To be repeated several times as an echo throughout a space.", "Every spoken vowel reverberated like music throughout the crystal dome.", "ri-VUR-buh-rayt", "re-ver-ber-ate", "Saying 're-ver-ber-et' with short 'e'.", "Concentric sound waves rippling and echoing between smooth crystal pillars"),
        ("reverberation", "Prolongation of a sound; resonance in an enclosed hall.", "The long reverberation time in the crystal hall enriched every vocal harmony.", "ri-vur-buh-RAY-shuhn", "re-ver-ber-a-tion", "Skipping the 'ber' syllable.", "A visual sound spectrogram showing a warm multi-layered harmonic decay tail"),
        ("resonance", "The reinforcement or prolongation of sound by synchronous vibration.", "The singing bowl created pure acoustic resonance that filled the entire room.", "REZ-uh-nuhns", "res-o-nance", "Saying 'ree-zo-nance' with long 'e'.", "A quartz crystal singing bowl vibrating with visible harmonic soundwaves"),
        ("acoustics", "The properties or qualities of a room that determine sound transmission.", "The natural crystal dome possessed world-class acoustic perfection for singing.", "uh-KOO-stiks", "a-cous-tics", "Saying 'uh-cow-stiks' with 'ow' sound.", "A vocal soloist singing in a grand natural crystal cavern with clear sound waves"),
        ("harmonics", "Musical tones produced as components of an acoustic sound wave.", "The crystal chimes produced enchanting overtones and rich natural harmonics.", "hahr-MAHN-iks", "har-mon-ics", "Saying 'har-mone-iks' with long 'o'.", "A musical score displaying rich harmonic overtones above a cavern landscape"),
        ("sonorous", "Capable of producing a deep, resonant, or ringing sound.", "The bronze and crystal bell produced a sonorous, noble ringing chime.", "SAHN-er-uhs", "son-o-rous", "Saying 'suh-nor-us' with wrong stress.", "A grand bronze and crystal bell chiming with visible radiant sound vibrations"),
        ("vibrations", "Plural of vibration; rapid periodic motions producing clear sound.", "Vocal cord vibrations resonated through the crystal chamber in harmony.", "vy-BRAY-shuhnz", "vi-bra-tions", "Saying 'vee-bra-tions' with long 'e'.", "An illustrated waveform showing acoustic sound vibrations in crystal air"),
    ],
    # L17: 8+ letter crystal lighting & luminescence
    [
        ("bioluminescence", "Light emitted by living organisms in the deep earth.", "Colonies of glowing cave fungi produced eerie turquoise bioluminescence.", "by-oh-loo-mi-NES-uhns", "bi-o-lu-mi-nes-cence", "Stumbling over the six-syllable sequence.", "Glowing blue and green bioluminescent mushrooms growing on cavern rocks"),
        ("phosphorescence", "Luminescence that persists after excitation has ceased.", "The calcite crystals continued to glow with pale green phosphorescence.", "fahs-fuh-RES-uhns", "phos-pho-res-cence", "Stumbling over the consonant transitions.", "A darkened cavern glowing with soft green natural mineral phosphorescence"),
        ("electroluminescence", "Luminescence created by the application of an electric field.", "Modern crystal research displays utilize efficient electroluminescence.", "i-lek-troh-loo-mi-NES-uhns", "e-lec-tro-lu-mi-nes-cence", "Stumbling over the seven-syllable sequence.", "A glowing thin-film electroluminescent crystal panel emitting cyan light"),
        ("triboluminescence", "Light generated when asymmetrical bonds in crystals are broken.", "Crushing wintergreen candies produces bright flashes of triboluminescence.", "try-boh-loo-mi-NES-uhns", "tri-bo-lu-mi-nes-cence", "Stumbling over the seven-syllable sequence.", "Bright blue flashes of light sparks appearing as crystals are struck together"),
        ("luminescent", "Emitting light not caused by heat; glowing with cool radiance.", "The luminescent crystal columns guided explorers safely through the dark.", "loo-mi-NES-uhnt", "lu-mi-nes-cent", "Saying 'lu-meen-es-cent' with long 'e'.", "Towering translucent white selenite crystals glowing with internal light"),
        ("iridescence", "Luminous colors that change depending on the viewing angle.", "The labradorescence in the spectrolite stone displayed dazzling iridescence.", "eer-i-DES-uhns", "ir-i-des-cence", "Saying 'eye-ri-des-cence' with long 'i'.", "A polished piece of labradorite mineral displaying peacock blue and gold iridescence"),
        ("opalescence", "The visual property of exhibiting play of colors like an opal.", "The milky quartz showed a gentle, floating blue-white opalescence in sun.", "oh-puh-LES-uhns", "o-pal-es-cence", "Saying 'ah-pah-les-cence' with short 'o'.", "A translucent white chalcedony stone glowing with soft blue opalescence"),
    ],
    # L18: 8+ letter cavern exploration & navigation
    [
        ("spelunker", "A person who explores caves as a hobby or sport.", "The experienced spelunker checked her harness carabiners and LED headlamp.", "spih-LUHNG-ker", "spe-lunk-er", "Saying 'spee-lunk-er' with long 'e'.", "A caver in a yellow jumpsuit and helmet with headlamp descending on a rope"),
        ("expeditions", "Plural of expedition; organized journeys for underground discovery.", "Cave diving expeditions explored miles of flooded crystal water passages.", "ek-spuh-DISH-uhnz", "ex-pe-di-tions", "Saying 'ex-pree-di-shuns' with wrong vowels.", "A team of cave explorers with equipment cases gathered at a cave entrance"),
        ("exploration", "The action of traveling in or through an unfamiliar area in order to learn.", "Underground exploration reveals hidden geological wonders deep in the earth.", "ek-spluh-RAY-shuhn", "ex-plo-ra-tion", "Saying 'ex-plur-ay-shun' with wrong vowel.", "Explorers in helmets looking up in awe at a towering underground crystal hall"),
        ("navigation", "The process of accurately planning and following a subterranean route.", "Survey lasers and 3D mapping made underground cavern navigation precise.", "nav-i-GAY-shuhn", "nav-i-ga-tion", "Saying 'nay-vi-ga-tion' with long 'a'.", "A 3D laser-scanned digital map of a complex underground cave network"),
        ("orienteering", "The practice of navigating through unknown country with map and compass.", "Cave orienteering requires careful tracking of compass bearings and depths.", "or-ee-en-TEER-ing", "o-ri-en-teer-ing", "Stumbling over the initial vowels.", "A cave mapper recording distance and azimuth compass readings in a notebook"),
        ("cartography", "The science or practice of drawing maps of underground caves.", "Subterranean cartography produced detailed cross-sections of the cavern system.", "kahr-TAHG-ruh-fee", "car-tog-ra-phy", "Saying 'car-to-gra-phy' with wrong stress.", "A detailed architectural cross-section blueprint map of a multi-level cave"),
        ("trailblazer", "A pioneer who creates a new pathway through uncharted territory.", "The cave trailblazer found a safe bypass around the bottomless chasm.", "TRAYL-blay-zer", "trail-blaz-er", "Saying 'trel-blazer' with short 'e'.", "An explorer placing reflective trail marker tags along a subterranean path"),
    ],
    # L19: 8+ letter eloquence, speech & articulation
    [
        ("articulation", "The formation of clear and distinct sounds in speech.", "Practicing articulation exercises ensures every consonant is heard crisply.", "ahr-tik-yuh-LAY-shuhn", "ar-tic-u-la-tion", "Skipping the 'yuh' syllable.", "A diagram illustrating the palate, tongue, and teeth articulating speech sounds"),
        ("pronunciation", "The correct way in which a word or a language is spoken.", "Her flawless pronunciation earned top marks in the national speech contest.", "pruh-nuhn-see-AY-shuhn", "pro-nun-ci-a-tion", "Saying 'pro-nown-ci-a-tion' with 'noun'.", "A speech soundwave symbol glowing with crystal-clear magical resonance"),
        ("enunciation", "The act of pronouncing words clearly and distinctly.", "Clear enunciation is essential for public speaking and singing performances.", "i-nuhn-see-AY-shuhn", "e-nun-ci-a-tion", "Saying 'ee-nun-see-ay-shun' with long 'e'.", "A confident speaker addressing an audience with clear vocal projection"),
        ("eloquence", "Fluent or persuasive speaking or writing.", "The ambassador spoke with such natural eloquence that everyone was moved.", "EL-uh-kwuhns", "el-o-quence", "Saying 'el-oh-kwens' with wrong vowels.", "An orator holding a podium delivering an inspiring, expressive speech"),
        ("articulacy", "The ability to express ideas clearly and effectively in speech.", "Developing articulacy empowers students to share their ideas with confidence.", "ahr-TIK-yuh-luh-see", "ar-tic-u-la-cy", "Stumbling over the five-syllable sequence.", "A young student speaking articulately and confidently at a podium"),
        ("expressive", "Effectively conveying thought or feeling in speech or art.", "Her expressive storytelling brought the ancient crystal legends to life.", "ik-SPRES-iv", "ex-pres-sive", "Saying 'ex-pray-siv' with long 'a'.", "An animated storyteller using expressive hand gestures and facial expressions"),
        ("persuasive", "Good at persuading someone to do or believe something through reasoning.", "His persuasive speech presented clear facts, logic, and inspiring visions.", "per-SWAY-siv", "per-sua-sive", "Saying 'per-swah-siv' with flat 'a'.", "A speaker gesturing persuasively with clear infographics displayed behind"),
    ],
    # L20: 8+ letter linguistic mastery & vocabulary
    [
        ("vocabulary", "The body of words used in a particular language or by a person.", "Reading diverse books expands your vocabulary and communication skills.", "voh-KAB-yuh-lair-ee", "vo-cab-u-lar-y", "Saying 'voh-kab-lah-ree' with dropped syllable.", "An open magical illuminated dictionary book with glowing words rising up"),
        ("comprehension", "The action or capability of understanding something fully.", "Her reading comprehension improved dramatically with daily practice.", "kahm-pri-HEN-shuhn", "com-pre-hen-sion", "Saying 'com-pree-hen-shun' with long 'e'.", "A student smiling with understanding while reading an illustrated textbook"),
        ("communication", "The imparting or exchanging of information or ideas.", "Clear spoken communication builds understanding and friendship between people.", "kuh-myoo-ni-KAY-shuhn", "com-mu-ni-ca-tion", "Skipping the 'ni' syllable.", "Two smiling people conversing warmly with speech bubbles connecting them"),
        ("understanding", "The ability to understand something; comprehension of meaning.", "Compassionate listening leads to deep mutual understanding between friends.", "uhn-der-STAND-ing", "un-der-stand-ing", "Dropping the 'nd' in stand.", "Two friends smiling and nodding in mutual agreement and understanding"),
        ("intelligible", "Able to be understood; clear and comprehensible in speech.", "His microphone settings ensured every whisper remained fully intelligible.", "in-TEL-i-juh-buhl", "in-tel-li-gi-ble", "Saying 'in-tel-lee-jee-ble' with long 'e'.", "A sound engineer monitoring clean, clear vocal audio levels on a mixer"),
        ("distinction", "A difference or contrast between similar things or phonemes.", "Trained ears hear the subtle phonetic distinction between short vowels.", "di-STINGK-shuhn", "dis-tinc-tion", "Saying 'dis-tink-shun' and dropping 'ng'.", "An illustrated chart showing distinct acoustic waveforms of two vowels"),
        ("linguistics", "The scientific study of language and its structure.", "Linguistics explores phonetics, grammar, syntax, and word origins.", "ling-GWIS-tiks", "lin-guis-tics", "Saying 'lin-gees-tiks' with hard 'g'.", "A university library desk with grammar books, phonetic alphabets, and notes"),
    ],
    # L21: 8+ letter crystal cathedral architecture
    [
        ("crystalcathedral", "A monumental subterranean temple constructed of pure crystal.", "The crystal cathedral glowed with thousand-foot spires of purple amethyst.", "KRIS-tuhl-kuh-THEE-druhl", "crys-tal-ca-the-dral", "Stumbling over the six-syllable sequence.", "A breathtaking subterranean cathedral with towering glowing purple crystal spires"),
        ("sanctuaries", "Plural of sanctuary; places of safety, beauty, and quiet contemplation.", "Subterranean sanctuaries offered tranquil spaces for reflection and study.", "SANGK-choo-air-eez", "sanc-tu-ar-ies", "Saying 'sank-too-air-eez' with hard 't'.", "An illuminated peaceful stone chamber with reflecting pools and crystal arches"),
        ("colonnade", "A row of columns supporting a roof, an entablature, or arcade.", "A magnificent colonnade of selenite pillars lined the grand ceremonial hall.", "kahl-uh-NAYD", "col-on-nade", "Saying 'caw-luh-nod' with wrong vowel.", "A grand perspective view down a colonnade of glowing white crystal pillars"),
        ("amphitheater", "An open-air venue used for entertainment and acoustic performances.", "The natural crystal amphitheater amplified every musical note with clarity.", "AM-fuh-thee-uh-ter", "am-phi-the-a-ter", "Saying 'am-pee-thee-a-ter' with 'p' sound.", "A tiered stone and crystal semicircular amphitheater with central stage"),
        ("magnificence", "The quality of being magnificent; splendid and imposing beauty.", "The sheer magnificence of the subterranean cavern left visitors speechless.", "mag-NIF-i-suhns", "mag-nif-i-cence", "Saying 'mag-neef-i-cence' with wrong vowel.", "A panoramic view of an enormous glowing crystal cavern filled with light"),
        ("monumental", "Great in importance, extent, or size; majestic in scale.", "The monumental stalagmite pillar had been growing for two million years.", "mahn-yuh-MEN-tuhl", "mon-u-men-tal", "Skipping the 'u' syllable.", "A colossal mineral stalagmite towering sixty feet above a human explorer"),
        ("architectural", "Relating to the art or practice of designing buildings.", "Natural architectural arches spanned the ceiling of the cavern cathedral.", "ahr-ki-TEK-cher-uhl", "ar-chi-tec-tur-al", "Saying 'ar-chee-tek-choor-al' with 'ch'.", "Natural stone and crystal flying buttresses supporting a cavern ceiling"),
    ],
    # L22: 8+ letter mineralogy & crystal structures
    [
        ("crystallography", "The scientific study of crystal structures and atomic lattices.", "Modern crystallography utilizes synchrotron radiation to map proteins.", "kris-tuh-LAHG-ruh-fee", "crys-tal-log-ra-phy", "Saying 'crys-tah-loh-gra-phy' with wrong stress.", "A 3D computer model of a diamond carbon crystal lattice structure"),
        ("mineralogical", "Relating to mineralogy, the scientific study of minerals.", "The university museum displayed five thousand mineralogical specimens.", "min-er-uh-LAHJ-i-kuhl", "min-er-a-log-i-cal", "Skipping the 'a' syllable.", "Glass display cases filled with cataloged colorful mineral crystals"),
        ("petrological", "Relating to petrology, the branch of science studying rocks.", "Petrological analysis confirmed the metamorphic origin of the marble.", "pet-ruh-LAHJ-i-kuhl", "pet-ro-log-i-cal", "Saying 'pet-roh-lo-ji-cal' with wrong stress.", "A petrologist using a polarized light microscope to study rock thin slices"),
        ("fluorescence", "The emission of light by a mineral that has absorbed UV radiation.", "Fluorescence revealed glowing neon patterns in the raw mineral vein.", "flaw-RES-uhns", "flu-o-res-cence", "Saying 'floo-or-es-cence' with wrong stress.", "A rock glowing with brilliant green and orange fluorescent mineral bands"),
        ("phosphorescence", "Luminescence that persists long after the excitation source ends.", "Mineral phosphorescence cast a gentle turquoise glow across the hall.", "fahs-fuh-RES-uhns", "phos-pho-res-cence", "Stumbling over the consonant transitions.", "A dark cavern illuminated by self-glowing phosphorescent mineral stalactites"),
        ("luminescent", "Emitting light not caused by heat; glowing with soft light.", "Luminescent crystals lit the subterranean pathway without need for torches.", "loo-mi-NES-uhnt", "lu-mi-nes-cent", "Saying 'lu-meen-es-cent' with long 'e'.", "Luminescent crystal stepping stones glowing softly on an underground path"),
        ("iridescent", "Showing luminous colors that change when seen from different angles.", "The iridescent surface of the mother-of-pearl shell shimmered brightly.", "eer-i-DES-uhnt", "ir-i-des-cent", "Saying 'eye-ri-des-cent' with long 'i'.", "An iridescent abalone shell displaying swirling rainbow peacock colors"),
    ],
    # L23: 8+ letter environmental conservation & ethics
    [
        ("sustainability", "The ability to maintain natural resources without ecological harm.", "Responsible ecotourism ensures the sustainability of delicate cave formations.", "suh-stay-nuh-BIL-i-tee", "sus-tain-a-bil-i-ty", "Stumbling over the seven-syllable sequence.", "A group of cave visitors walking strictly on raised pathways to protect formations"),
        ("preservation", "The act of keeping natural geological wonders safe from damage.", "Cave preservation guidelines prohibit touching fragile growing stalactites.", "prez-er-VAY-shuhn", "pres-er-va-tion", "Saying 'press-er-va-tion' with hard 's'.", "A protective railing surrounding a pristine white cave mineral formation"),
        ("conservation", "The protection and management of natural subterranean resources.", "Bat conservation groups protected critical underground winter hibernacula.", "kahn-ser-VAY-shuhn", "con-ser-va-tion", "Saying 'con-ser-va-shun' with hard 's'.", "A cave gate with bat-friendly horizontal bars allowing bats to fly freely"),
        ("environmental", "Relating to the natural world and human impact upon ecosystems.", "Environmental sensors monitored airflow, humidity, and carbon dioxide in caves.", "en-vy-ruhn-MEN-tuhl", "en-vi-ron-men-tal", "Saying 'en-vi-ro-men-tal' and dropping 'n'.", "A digital environmental monitoring station mounted inside a cave chamber"),
        ("biodiversity", "The variety of specialized cave-dwelling organisms in nature.", "Blind cave fish and salamanders demonstrate remarkable subterranean biodiversity.", "by-oh-dy-VUR-si-tee", "bi-o-di-ver-si-ty", "Saying 'bee-o-di-ver-si-ty' with long 'e'.", "A transparent blind cave tetra fish swimming in clean subterranean water"),
        ("rehabilitation", "The restoration of a damaged habitat to good condition.", "Restoration teams worked on the rehabilitation of the old mining cavern.", "ree-huh-bil-i-TAY-shuhn", "re-ha-bil-i-ta-tion", "Skipping the 'bil' syllable.", "Workers cleaning graffiti and installing gentle LED lights in a cave"),
        ("regeneration", "The natural renewal or regrowth of living ecosystems.", "Crystalline mineral regeneration slowly mends fractures over geological time.", "ri-jen-er-AY-shuhn", "re-gen-er-a-tion", "Saying 're-gen-ra-tion' with dropped syllable.", "New tiny crystal needles growing over an old fractured rock surface"),
    ],
    # L24: 8+ letter linguistic articulacy & public speaking
    [
        ("persuasiveness", "The quality of being able to convince others through reason.", "Her persuasiveness stemmed from clear facts and passionate delivery.", "per-SWAY-siv-nis", "per-sua-sive-ness", "Saying 'per-swah-siv-ness' with flat 'a'.", "A speaker presenting compelling data charts to an engaged audience"),
        ("articulateness", "The quality of expressing ideas clearly and fluently.", "His natural articulateness made him a favorite debate team captain.", "ahr-TIK-yuh-lit-nis", "ar-tic-u-late-ness", "Skipping the 'yuh' syllable.", "A confident student speaking articulately with clear pronunciation"),
        ("expressiveness", "The quality of effectively conveying thought or emotion in speech.", "Her vocal expressiveness brought depth, humor, and emotion to the poem.", "ik-SPRES-iv-nis", "ex-pres-sive-ness", "Saying 'ex-pray-siv-ness' with long 'a'.", "An actor on stage delivering an emotional monologue with expressive delivery"),
        ("intelligibility", "The state or quality of being easily understood in speech.", "High vocal intelligibility ensures that every word reaches every listener.", "in-tel-i-juh-BIL-i-tee", "in-tel-li-gi-bil-i-ty", "Stumbling over the seven-syllable sequence.", "A sound engineer adjusting equalizer frequencies to maximize vocal clarity"),
        ("pronunciation", "The correct way in which words are articulated and voiced.", "Consistent daily practice perfected her English pronunciation.", "pruh-nuhn-see-AY-shuhn", "pro-nun-ci-a-tion", "Saying 'pro-nown-ci-a-tion' with 'noun'.", "A speech soundwave symbol glowing with crystal energy and clean harmonics"),
        ("articulation", "The clear and distinct formation of speech sounds.", "Crisp consonant articulation gave her presentation professional polish.", "ahr-tik-yuh-LAY-shuhn", "ar-tic-u-la-tion", "Skipping the 'yuh' syllable.", "An anatomical graphic of vocal cords and tongue producing speech sounds"),
        ("enunciation", "The act of pronouncing every syllable distinctly.", "Careful enunciation helped the international audience understand the lecture.", "i-nuhn-see-AY-shuhn", "e-nun-ci-a-tion", "Saying 'ee-nun-see-ay-shun' with long 'e'.", "A speaker enunciating clearly into a broadcast microphone in a studio"),
    ],
    # L25: 8+ letter scholarship, literature & wisdom
    [
        ("scholarship", "Academic study or achievement; learning of a high level.", "Her outstanding scholarship earned her a full university academic award.", "SKAH-ler-ship", "schol-ar-ship", "Saying 'so-ler-ship' and dropping 'k'.", "A graduation cap and rolled diploma ribbon resting on open leather books"),
        ("encyclopedia", "A comprehensive reference work containing information on all branches of knowledge.", "He looked up the history of gemstone mining in the illustrated encyclopedia.", "en-sy-kluh-PEE-dee-uh", "en-cy-clo-pe-di-a", "Skipping the 'clo' syllable.", "A heavy leather-bound volume of an illustrated color encyclopedia on a desk"),
        ("manuscripts", "Plural of manuscript; books, documents, or music written by hand.", "Ancient illuminated manuscripts were preserved inside climate-controlled vaults.", "MAN-yuh-skripts", "man-u-scripts", "Dropping the 'p' in scripts.", "Antique illuminated parchment manuscripts with gold leaf and red calligraphy"),
        ("philosophy", "The study of the fundamental nature of knowledge, reality, and existence.", "Moral philosophy explores principles of justice, ethics, and virtue.", "fi-LAHS-uh-fee", "phi-los-o-phy", "Saying 'fee-lo-so-phy' with long 'e'.", "A classic stone bust sculpture of an ancient Greek philosopher thinker"),
        ("literature", "Written works, especially those considered of superior or lasting artistic merit.", "Studying world literature opens windows into diverse cultures and minds.", "LIT-er-uh-cher", "lit-er-a-ture", "Saying 'lit-rah-choor' with dropped syllables.", "A stack of classic hardcover literary novels on a polished mahogany table"),
        ("dictionaries", "Plural of dictionary; reference books containing words and meanings.", "Etymological dictionaries explain the fascinating historical origins of words.", "DIK-shuh-nair-eez", "dic-tion-ar-ies", "Skipping the 'ar' syllable.", "Multiple large open dictionaries with highlighted vocabulary entries on a desk"),
        ("anthologies", "Plural of anthology; published collections of poems or writings.", "Anthologies of ancient poetry celebrated the beauty of nature and courage.", "an-THAHL-uh-jeez", "an-thol-o-gies", "Saying 'an-to-lo-gies' and dropping 'th'.", "A beautifully bound leather book anthology of poetry with a silk ribbon bookmark"),
    ],
    # L26: 8+ letter crystal acoustics & resonance
    [
        ("reverberations", "Plural of reverberation; prolongations of sound by reflection.", "Musical reverberations resonated softly in the vaulted crystal cathedral.", "ri-vur-buh-RAY-shuhnz", "re-ver-ber-a-tions", "Skipping the 'ber' syllable.", "An acoustic graphic showing multi-layered soundwave reverberations in a hall"),
        ("sonorousness", "The quality of having a deep, full, and rich sound.", "The rich sonorousness of the grand organ filled the subterranean space.", "SAHN-er-uhs-nis", "son-o-rous-ness", "Saying 'suh-nor-us-ness' with wrong stress.", "A grand pipe organ console vibrating with visible acoustic sound energy"),
        ("crystallized", "Formed into crystals; made clear and definite.", "Her thoughts and pronunciation crystallized into confident, fluid speech.", "KRIS-tuh-lyzd", "crys-tal-lized", "Saying 'kris-tuh-leezd' with long 'e'.", "A clear quartz crystal cluster with sparkling facets on a velvet stand"),
        ("harmonics", "Musical overtones produced alongside a fundamental pitch.", "The violin harmonics rang out sweet and pure like singing crystal.", "hahr-MAHN-iks", "har-mon-ics", "Saying 'har-mone-iks' with long 'o'.", "A violin string vibrating and showing natural harmonic nodes and waveforms"),
        ("resonance", "The condition in which an object vibrates at its natural frequency.", "Acoustic resonance amplified the singer's voice naturally throughout the cave.", "REZ-uh-nuhns", "res-o-nance", "Saying 'ree-zo-nance' with long 'e'.", "A crystal chalice vibrating and singing with pure acoustic tone in resonance"),
        ("luminescence", "Light emitted by a substance without high temperature.", "Phosphorescent minerals provided a tranquil blue luminescence along the trail.", "loo-mi-NES-uhns", "lu-mi-nes-cence", "Saying 'lu-meen-es-cence' with long 'e'.", "A cluster of fluorite crystals glowing with soft neon blue luminescence"),
        ("iridescence", "A rainbow-like play of colors that shifts with viewing angle.", "The labradorescence of the polished gemstone flashed with vivid iridescence.", "eer-i-DES-uhns", "ir-i-des-cence", "Saying 'eye-ri-des-cence' with long 'i'.", "A polished gemstone surface flashing with rainbow peacock blue iridescence"),
    ],
    # L27: 8+ letter determination, resilience & perseverance
    [
        ("perseverance", "Persistence in doing something despite difficulty or delay in success.", "Through patient perseverance, the student conquered all seven realms.", "pur-suh-VEER-uhns", "per-se-ver-ance", "Saying 'per-sev-rance' with dropped syllable.", "A student holding a graduation torch standing atop a mountain of books"),
        ("determination", "Firmness of purpose; resoluteness in achieving a noble goal.", "Her unwavering determination inspired everyone in her pronunciation class.", "di-tur-mi-NAY-shuhn", "de-ter-mi-na-tion", "Saying 'de-ter-mee-na-tion' with long 'e'.", "A focused student practicing speech with headphones and microphone"),
        ("accomplishment", "Something that has been achieved successfully through effort.", "Completing the 1,470-word curriculum was a monumental accomplishment.", "uh-KAHM-plish-muhnt", "ac-com-plish-ment", "Saying 'ac-cum-plish-ment' with short 'u'.", "A student proudly holding a golden achievement trophy certificate"),
        ("resourcefulness", "The ability to find clever ways to overcome challenges.", "Her linguistic resourcefulness allowed her to navigate any pronunciation puzzle.", "ri-SORS-fuhl-nis", "re-source-ful-ness", "Saying 'ree-source-ful-ness' with wrong stress.", "A student solving an interactive phonetics puzzle on a digital screen"),
        ("extraordinary", "Very unusual or remarkable; exceptional in quality.", "The student demonstrated extraordinary progress across all seven worlds.", "ik-STROR-di-nair-ee", "ex-traor-di-nar-y", "Saying 'extra-ordinary' in six distinct syllables.", "A glowing gold and crystal graduation medal reflecting sparkling light"),
        ("magnificent", "Impressively beautiful, elaborate, or grand in scale.", "The final Crystal Caverns realm was a magnificent triumph of sound and light.", "mag-NIF-i-suhnt", "mag-nif-i-cent", "Saying 'mag-neef-i-cent' with wrong vowel.", "A panoramic view of glowing crystalline towers rising inside a grand cavern"),
        ("monumental", "Great in importance, extent, or size; historic in scale.", "This final production build stands as a monumental milestone in learning.", "mahn-yuh-MEN-tuhl", "mon-u-men-tal", "Skipping the 'u' syllable.", "A grand marble and crystal monument arch commemorating language mastery"),
    ],
    # L28: 8+ letter linguistic championships & achievements
    [
        ("championship", "The position or title of a champion; supreme victory in contest.", "She claimed the first-place gold trophy in the pronunciation championship.", "CHAM-pee-uhn-ship", "cham-pi-on-ship", "Saying 'chem-py-on-ship' with short 'e'.", "A gleaming golden championship cup trophy with crystal gemstone accents"),
        ("triumphant", "Having won a victory; victorious, celebratory, and joyful.", "The triumphant adventurer stood at the pinnacle of the Crystal Caverns.", "try-UHM-fuhnt", "tri-um-phant", "Saying 'tree-um-phant' with long 'e'.", "A triumphant student raising arms victoriously under celebratory confetti"),
        ("invincible", "Too powerful to be defeated; resolute, brave, and strong.", "With clear voice and courage, the student felt confident and invincible.", "in-VIN-suh-buhl", "in-vin-ci-ble", "Saying 'in-veen-ci-ble' with long 'e'.", "Two young adventurers with glowing crystal staff standing atop a peak"),
        ("unshakeable", "Unable to be disputed, shaken, or weakened; steadfast.", "His unshakeable confidence grew with every word mastered along the journey.", "uhn-SHAY-kuh-buhl", "un-shake-a-ble", "Saying 'un-shak-a-ble' with short 'a'.", "A student smiling with steady, calm, unshakeable confidence at a podium"),
        ("masterpieces", "Plural of masterpiece; works of outstanding artistry and perfection.", "Every spoken sentence in the final level shone like polished masterpieces.", "MAS-ter-pee-siz", "mas-ter-piec-es", "Saying 'mes-ter-piec-es' with short 'e'.", "A museum gallery displaying illuminated crystal sculptures of open books"),
        ("resplendent", "Attractive and impressive through being richly colorful and bright.", "The Golden Phoenix companion was resplendent in radiant amber feathers.", "ri-SPLEN-duhnt", "re-splen-dent", "Saying 're-splan-dent' with short 'a'.", "A magnificent Golden Phoenix companion radiating warm golden feather light"),
        ("flourishing", "Thriving, developing rapidly, and succeeding in every realm.", "The student's communication skills were flourishing with clarity and joy.", "FLUR-ish-ing", "flour-ish-ing", "Saying 'floor-ish-ing' with wrong vowel.", "A vibrant garden of blooming crystal flowers glowing in rainbow colors"),
    ],
    # L29: 8+ letter eloquence, articulacy & phonetics mastery
    [
        ("articulateness", "The quality of speaking clearly, fluently, and effectively.", "Her remarkable articulateness made her an inspiring leader and communicator.", "ahr-TIK-yuh-lit-nis", "ar-tic-u-late-ness", "Skipping the 'yuh' syllable.", "A smiling student articulating speech clearly into a silver microphone"),
        ("expressiveness", "The quality of effectively conveying meaning and feeling.", "Vocal expressiveness turns ordinary words into captivating adventure stories.", "ik-SPRES-iv-nis", "ex-pres-sive-ness", "Saying 'ex-pray-siv-ness' with long 'a'.", "An expressive storyteller reading to an engaged circle of smiling children"),
        ("intelligibility", "The quality of being easily understood by all listeners.", "Crystal-clear enunciation ensures one hundred percent speech intelligibility.", "in-tel-i-juh-BIL-i-tee", "in-tel-li-gi-bil-i-ty", "Stumbling over the seven-syllable sequence.", "A digital speech visualizer display showing perfect 100 percent recognition clarity"),
        ("persuasiveness", "The ability to persuade through eloquent reason and warmth.", "Her persuasiveness and kindness inspired everyone to practice daily.", "per-SWAY-siv-nis", "per-sua-sive-ness", "Saying 'per-swah-siv-ness' with flat 'a'.", "A student presenting an engaging project with confidence and warmth"),
        ("pronunciation", "The clear, accurate, and articulate voicing of words.", "Clear pronunciation is the key that unlocks every adventure realm.", "pruh-nuhn-see-AY-shuhn", "pro-nun-ci-a-tion", "Saying 'pro-nown-ci-a-tion' with 'noun'.", "A glowing soundwave symbol radiating crystal energy and pure sound"),
        ("articulation", "The formation of clear, distinct, and accurate speech sounds.", "Daily articulation warm-ups strengthen vocal clarity and speech agility.", "ahr-tik-yuh-LAY-shuhn", "ar-tic-u-la-tion", "Skipping the 'yuh' syllable.", "A vocal coach guiding a student through fun articulation vowel warm-ups"),
        ("enunciation", "The act of speaking every word and syllable distinctly.", "Crisp enunciation ensures that every vowel and consonant rings out true.", "i-nuhn-see-AY-shuhn", "e-nun-ci-a-tion", "Saying 'ee-nun-see-ay-shun' with long 'e'.", "A young orator speaking into a microphone with clear distinct enunciation"),
    ],
    # L30: 8+ letter Ultimate Grand Champion & Graduation
    [
        ("pronunciation", "The act or result of articulating words correctly and clearly.", "Flawless pronunciation crowned their journey as master of the seven realms.", "pruh-nuhn-see-AY-shuhn", "pro-nun-ci-a-tion", "Saying 'pro-nown-ci-a-tion' with 'noun'.", "A majestic golden soundwave crest glowing in the center of the crystal dome"),
        ("accomplishment", "A grand achievement completed through hard work, study, and skill.", "Conquering all 1,470 words was a historic educational accomplishment.", "uh-KAHM-plish-muhnt", "ac-com-plish-ment", "Saying 'ac-cum-plish-ment' with short 'u'.", "A student in a graduation gown holding a golden Pronunciation Adventure diploma"),
        ("extraordinary", "Remarkable, exceptional, and beyond the ordinary in every way.", "Your progress from simple sounds to master vocabulary has been extraordinary!", "ik-STROR-di-nair-ee", "ex-traor-di-nar-y", "Saying 'extra-ordinary' in six distinct syllables.", "A radiant fireworks celebration bursting over the Crystal Caverns castle"),
        ("unshakeable", "Steadfast, confident, and impossible to defeat or discourage.", "With unshakeable confidence in your voice, you are ready for any future challenge.", "uhn-SHAY-kuh-buhl", "un-shake-a-ble", "Saying 'un-shak-a-ble' with short 'a'.", "A confident young graduate looking out toward a bright horizon with a smile"),
        ("invincible", "Too powerful and resilient to be overcome; triumphant.", "Armed with clear speech and knowledge, your potential is truly invincible!", "in-VIN-suh-buhl", "in-vin-ci-ble", "Saying 'in-veen-ci-ble' with long 'e'.", "Two student adventurers holding hands high in victory on the grand crystal throne"),
        ("championship", "The supreme title of champion; the ultimate victory in adventure.", "You have earned the grand championship crown of Spoken English Mastery!", "CHAM-pee-uhn-ship", "cham-pi-on-ship", "Saying 'chem-py-on-ship' with short 'e'.", "A magnificent golden crown adorned with sapphires, rubies, and emeralds"),
        ("masterpiece", "An outstanding work of artistry, education, skill, and triumph.", "Pronunciation Adventure is complete: a shining, joyful learning masterpiece!", "MAS-ter-pees", "mas-ter-piece", "Saying 'mes-ter-piece' with short 'e'.", "A glorious panoramic illustration of all seven adventure worlds united in harmony"),
    ],
]
